Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ContentTypeDetector",
            "name": "ContentTypeDetector",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ContentTypeDetector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ContentTypeDetector\u003A\u003AdetectFromResponse\u0028\u0029",
            "name": "detectFromResponse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ContentTypeDetector.html#method_detectFromResponse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ContentTypeDetector\u003A\u003AdetectFromHeader\u0028\u0029",
            "name": "detectFromHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ContentTypeDetector.html#method_detectFromHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\from_dynamic_http_requests\u0028\u0029",
            "name": "from_dynamic_http_requests",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_from_dynamic_http_requests"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\from_static_http_requests\u0028\u0029",
            "name": "from_static_http_requests",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_from_static_http_requests"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\from_http_paginated\u0028\u0029",
            "name": "from_http_paginated",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_from_http_paginated"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_page_number\u0028\u0029",
            "name": "http_pagination_page_number",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_page_number"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_offset\u0028\u0029",
            "name": "http_pagination_offset",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_offset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_cursor\u0028\u0029",
            "name": "http_pagination_cursor",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_cursor"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_next_url\u0028\u0029",
            "name": "http_pagination_next_url",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_next_url"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_link_header\u0028\u0029",
            "name": "http_pagination_link_header",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_link_header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_pagination_last_record_cursor\u0028\u0029",
            "name": "http_pagination_last_record_cursor",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_pagination_last_record_cursor"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_request_option_query\u0028\u0029",
            "name": "http_request_option_query",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_request_option_query"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_request_option_header\u0028\u0029",
            "name": "http_request_option_header",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_request_option_header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_request_option_body\u0028\u0029",
            "name": "http_request_option_body",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_request_option_body"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_request_option_uri\u0028\u0029",
            "name": "http_request_option_uri",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_request_option_uri"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_path_missing\u0028\u0029",
            "name": "http_stop_when_path_missing",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_path_missing"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_empty_path\u0028\u0029",
            "name": "http_stop_when_empty_path",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_empty_path"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_flag_false\u0028\u0029",
            "name": "http_stop_when_flag_false",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_flag_false"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_flag_true\u0028\u0029",
            "name": "http_stop_when_flag_true",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_flag_true"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_total_reached\u0028\u0029",
            "name": "http_stop_when_total_reached",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_total_reached"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_max_pages\u0028\u0029",
            "name": "http_stop_when_max_pages",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_max_pages"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\http_stop_when_max_results\u0028\u0029",
            "name": "http_stop_when_max_results",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_http_stop_when_max_results"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor\\NextRequestFactory",
            "name": "NextRequestFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-DynamicExtractor-NextRequestFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor\\NextRequestFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-DynamicExtractor-NextRequestFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpEncoder",
            "name": "HttpEncoder",
            "summary": "Decodes\u0020an\u0020HTTP\u0020exchange\u0020into\u0020raw\u0020row\u0020values.\u0020The\u0020response\/request\u0020body\u0020is\u0020decoded\u0020once,\u0020content\u002Dtype\u0020aware,\ninto\u0020a\u0020navigable\u0020nested\u0020map\u0020\u0028JSON\u0020via\u0020json_decode,\u0020XML\u0020via\u0020\u007B\u0040see\u0020XMLConverter\u007D\u0029\u003B\u0020the\u0020extractor\u0027s\u0020Hydrator\u0020types\nthe\u0020Row\u0020from\u0020it\u0020and\u0020pagination\u0020reads\u0020the\u0020same\u0020map.",
            "url": "classes/Flow-ETL-Adapter-Http-HttpEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpExchange",
            "name": "HttpExchange",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpExchange.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpExchange\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpExchange.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpExchange\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpExchange.html#property_request"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\HttpExchange\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-HttpExchange.html#property_response"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse",
            "name": "DecodedResponse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse\u003A\u003Abody\u0028\u0029",
            "name": "body",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html#method_body"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html#method_header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse\u003A\u003Aresponse\u0028\u0029",
            "name": "response",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html#method_response"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\DecodedResponse\u003A\u003AstatusCode\u0028\u0029",
            "name": "statusCode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-DecodedResponse.html#method_statusCode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\InjectInto",
            "name": "InjectInto",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-InjectInto.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\InjectInto\u003A\u003AQueryParam",
            "name": "QueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-InjectInto.html#enumcase_QueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\InjectInto\u003A\u003AHeader",
            "name": "Header",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-InjectInto.html#enumcase_Header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\InjectInto\u003A\u003ABodyPath",
            "name": "BodyPath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-InjectInto.html#enumcase_BodyPath"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\InjectInto\u003A\u003AReplaceUri",
            "name": "ReplaceUri",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-InjectInto.html#enumcase_ReplaceUri"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\LinkHeaderParser",
            "name": "LinkHeaderParser",
            "summary": "Minimal\u0020RFC\u00208288\u0020\u0060Link\u0060\u0020header\u0020parser.\u0020Malformed\u0020input\u0020yields\u0020no\u0020match\u0020\u0028never\u0020throws\u0029.",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-LinkHeaderParser.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\LinkHeaderParser\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-LinkHeaderParser.html#method_next"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PageState",
            "name": "PageState",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PageState.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PageState\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PageState.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PageState\u003A\u003Aadvance\u0028\u0029",
            "name": "advance",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PageState.html#method_advance"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PageState\u003A\u003A\u0024pagesFetched",
            "name": "pagesFetched",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PageState.html#property_pagesFetched"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PageState\u003A\u003A\u0024resultsFetched",
            "name": "resultsFetched",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PageState.html#property_resultsFetched"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PaginationStrategy",
            "name": "PaginationStrategy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PaginationStrategy.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PaginationStrategy\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PaginationStrategy.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\PaginationStrategy\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-PaginationStrategy.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Paginator",
            "name": "Paginator",
            "summary": "Orchestrates\u0020a\u0020\u007B\u0040see\u0020PaginationStrategy\u007D\u003A\u0020stop\u0020conditions,\u0020\u0060\u003E\u003D400\u0060\u0020handling,\u0020identical\u002Drequest\u0020loop\u0020guard\u0020and\npage\u002Dstate\u0020advancement.\u0020Implement\u0020\u007B\u0040see\u0020PaginationStrategy\u007D\u0020to\u0020add\u0020a\u0020new\u0020pagination\u0020style\u003B\u0020drop\u0020to\n\u007B\u0040see\u0020\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor\\NextRequestFactory\u007D\u0020for\u0020fully\u0020bespoke\u0020request\u0020derivation.",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Paginator.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Paginator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Paginator.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Paginator\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Paginator.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Paginator\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Paginator.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RelativeUriResolver",
            "name": "RelativeUriResolver",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RelativeUriResolver.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RelativeUriResolver\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RelativeUriResolver.html#method_resolve"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestComparator",
            "name": "RequestComparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestComparator.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestComparator\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestComparator.html#method_equals"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption",
            "name": "RequestOption",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003AbodyPath\u0028\u0029",
            "name": "bodyPath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#method_bodyPath"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#method_header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003AqueryParam\u0028\u0029",
            "name": "queryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#method_queryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003AreplaceUri\u0028\u0029",
            "name": "replaceUri",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#method_replaceUri"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003Aapply\u0028\u0029",
            "name": "apply",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#method_apply"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003A\u0024into",
            "name": "into",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#property_into"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\RequestOption\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-RequestOption.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\ResultCounter",
            "name": "ResultCounter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-ResultCounter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\ResultCounter\u003A\u003AcountResults\u0028\u0029",
            "name": "countResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-ResultCounter.html#method_countResults"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AllOf",
            "name": "AllOf",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AllOf.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AllOf\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AllOf.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AllOf\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AllOf.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AnyOf",
            "name": "AnyOf",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AnyOf.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AnyOf\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AnyOf.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\AnyOf\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-AnyOf.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\EmptyPath",
            "name": "EmptyPath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-EmptyPath.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\EmptyPath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-EmptyPath.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\EmptyPath\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-EmptyPath.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\EmptyResponseBody",
            "name": "EmptyResponseBody",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-EmptyResponseBody.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\EmptyResponseBody\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-EmptyResponseBody.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagFalse",
            "name": "FlagFalse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagFalse.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagFalse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagFalse.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagFalse\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagFalse.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagTrue",
            "name": "FlagTrue",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagTrue.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagTrue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagTrue.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\FlagTrue\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-FlagTrue.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxPages",
            "name": "MaxPages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxPages.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxPages\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxPages.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxPages\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxPages.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxResults",
            "name": "MaxResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxResults.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxResults\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxResults.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\MaxResults\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-MaxResults.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\NeverStop",
            "name": "NeverStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-NeverStop.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\NeverStop\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-NeverStop.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\PathMissing",
            "name": "PathMissing",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-PathMissing.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\PathMissing\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-PathMissing.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\PathMissing\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-PathMissing.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\TotalReached",
            "name": "TotalReached",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-TotalReached.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\TotalReached\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-TotalReached.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\\TotalReached\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen-TotalReached.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen",
            "name": "StopWhen",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\u003A\u003AshouldStop\u0028\u0029",
            "name": "shouldStop",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen.html#method_shouldStop"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\u003A\u003Aand\u0028\u0029",
            "name": "and",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen.html#method_and"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen\u003A\u003Aor\u0028\u0029",
            "name": "or",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-StopWhen.html#method_or"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\CursorFromBody",
            "name": "CursorFromBody",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-CursorFromBody.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\CursorFromBody\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-CursorFromBody.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\CursorFromBody\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-CursorFromBody.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\CursorFromBody\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-CursorFromBody.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LastRecordCursor",
            "name": "LastRecordCursor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LastRecordCursor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LastRecordCursor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LastRecordCursor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LastRecordCursor\u003A\u003AcountResults\u0028\u0029",
            "name": "countResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LastRecordCursor.html#method_countResults"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LastRecordCursor\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LastRecordCursor.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LastRecordCursor\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LastRecordCursor.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LinkHeader",
            "name": "LinkHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LinkHeader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LinkHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LinkHeader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LinkHeader\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LinkHeader.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\LinkHeader\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-LinkHeader.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\NextUrlFromBody",
            "name": "NextUrlFromBody",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-NextUrlFromBody.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\NextUrlFromBody\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-NextUrlFromBody.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\NextUrlFromBody\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-NextUrlFromBody.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\NextUrlFromBody\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-NextUrlFromBody.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\OffsetLimit",
            "name": "OffsetLimit",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-OffsetLimit.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\OffsetLimit\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-OffsetLimit.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\OffsetLimit\u003A\u003AcountResults\u0028\u0029",
            "name": "countResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-OffsetLimit.html#method_countResults"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\OffsetLimit\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-OffsetLimit.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\OffsetLimit\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-OffsetLimit.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\PageNumber",
            "name": "PageNumber",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-PageNumber.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\PageNumber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-PageNumber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\PageNumber\u003A\u003AcountResults\u0028\u0029",
            "name": "countResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-PageNumber.html#method_countResults"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\PageNumber\u003A\u003AinitialRequest\u0028\u0029",
            "name": "initialRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-PageNumber.html#method_initialRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy\\PageNumber\u003A\u003AnextRequest\u0028\u0029",
            "name": "nextRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-Pagination-Strategy-PageNumber.html#method_nextRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor",
            "name": "PsrHttpClientDynamicExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003AwithPostRequest\u0028\u0029",
            "name": "withPostRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_withPostRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003AwithPreRequest\u0028\u0029",
            "name": "withPreRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_withPreRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor",
            "name": "PsrHttpClientPaginatedExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor\u003A\u003AwithPostRequest\u0028\u0029",
            "name": "withPostRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html#method_withPostRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor\u003A\u003AwithPreRequest\u0028\u0029",
            "name": "withPreRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html#method_withPreRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientPaginatedExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientPaginatedExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor",
            "name": "PsrHttpClientStaticExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003AwithPostRequest\u0028\u0029",
            "name": "withPostRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_withPostRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003AwithPreRequest\u0028\u0029",
            "name": "withPreRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_withPreRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType",
            "name": "ResponseType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AHTML",
            "name": "HTML",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_HTML"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_JSON"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_TEXT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AXML",
            "name": "XML",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_XML"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor",
            "name": "DynamicExtractor",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http-dynamicextractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination",
            "name": "Pagination",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http-pagination.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\StopWhen",
            "name": "StopWhen",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http-pagination-stopwhen.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\Pagination\\Strategy",
            "name": "Strategy",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http-pagination-strategy.html"
        }            ]
);
