Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ContentTypeDetector",
            "name": "ContentTypeDetector",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ContentTypeDetector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ContentTypeDetector\u003A\u003AdetectFromResponse\u0028\u0029",
            "name": "detectFromResponse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ContentTypeDetector.html#method_detectFromResponse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\from_dynamic_http_requests\u0028\u0029",
            "name": "from_dynamic_http_requests",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_from_dynamic_http_requests"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\from_static_http_requests\u0028\u0029",
            "name": "from_static_http_requests",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html#function_from_static_http_requests"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor\\NextRequestFactory",
            "name": "NextRequestFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-DynamicExtractor-NextRequestFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor\\NextRequestFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-DynamicExtractor-NextRequestFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor",
            "name": "PsrHttpClientDynamicExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003AwithPostRequest\u0028\u0029",
            "name": "withPostRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_withPostRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientDynamicExtractor\u003A\u003AwithPreRequest\u0028\u0029",
            "name": "withPreRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientDynamicExtractor.html#method_withPreRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor",
            "name": "PsrHttpClientStaticExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003AwithPostRequest\u0028\u0029",
            "name": "withPostRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_withPostRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\PsrHttpClientStaticExtractor\u003A\u003AwithPreRequest\u0028\u0029",
            "name": "withPreRequest",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-PsrHttpClientStaticExtractor.html#method_withPreRequest"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\RequestEntriesFactory",
            "name": "RequestEntriesFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-RequestEntriesFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\RequestEntriesFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-RequestEntriesFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseEntriesFactory",
            "name": "ResponseEntriesFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseEntriesFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseEntriesFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseEntriesFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType",
            "name": "ResponseType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AHTML",
            "name": "HTML",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_HTML"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_JSON"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_TEXT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\ResponseType\u003A\u003AXML",
            "name": "XML",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Http-ResponseType.html#enumcase_XML"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Http\\DynamicExtractor",
            "name": "DynamicExtractor",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-http-dynamicextractor.html"
        }            ]
);
