Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart",
            "name": "BarChart",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html#method_collect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart\u003A\u003Adata\u0028\u0029",
            "name": "data",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html#method_data"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart\u003A\u003AsetDatasetOptions\u0028\u0029",
            "name": "setDatasetOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html#method_setDatasetOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\BarChart\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-BarChart.html#method_setOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart",
            "name": "LineChart",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html#method_collect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart\u003A\u003Adata\u0028\u0029",
            "name": "data",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html#method_data"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart\u003A\u003AsetDatasetOptions\u0028\u0029",
            "name": "setDatasetOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html#method_setDatasetOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\LineChart\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-LineChart.html#method_setOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart",
            "name": "PieChart",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html#method_collect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart\u003A\u003Adata\u0028\u0029",
            "name": "data",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html#method_data"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart\u003A\u003AsetDatasetOptions\u0028\u0029",
            "name": "setDatasetOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html#method_setDatasetOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\\PieChart\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart-PieChart.html#method_setOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart",
            "name": "Chart",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart.html#method_collect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\u003A\u003Adata\u0028\u0029",
            "name": "data",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart.html#method_data"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\u003A\u003AsetDatasetOptions\u0028\u0029",
            "name": "setDatasetOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart.html#method_setDatasetOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart\u003A\u003AsetOptions\u0028\u0029",
            "name": "setOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-Chart.html#method_setOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader",
            "name": "ChartJSLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003AwithOutputPath\u0028\u0029",
            "name": "withOutputPath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method_withOutputPath"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003AwithOutputVar\u0028\u0029",
            "name": "withOutputVar",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method_withOutputVar"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\ChartJSLoader\u003A\u003AwithTemplate\u0028\u0029",
            "name": "withTemplate",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-ChartJS-ChartJSLoader.html#method_withTemplate"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\bar_chart\u0028\u0029",
            "name": "bar_chart",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_bar_chart"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\line_chart\u0028\u0029",
            "name": "line_chart",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_line_chart"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\pie_chart\u0028\u0029",
            "name": "pie_chart",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_pie_chart"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\to_chartjs\u0028\u0029",
            "name": "to_chartjs",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_to_chartjs"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\to_chartjs_file\u0028\u0029",
            "name": "to_chartjs_file",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_to_chartjs_file"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\to_chartjs_var\u0028\u0029",
            "name": "to_chartjs_var",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html#function_to_chartjs_var"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS\\Chart",
            "name": "Chart",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs-chart.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\ChartJS",
            "name": "ChartJS",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-chartjs.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
