Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\Columns",
            "name": "Columns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-Columns.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\Columns\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-Columns.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\Columns\u003A\u003A\u0024sheetName",
            "name": "sheetName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-Columns.html#property_sheetName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\Columns\u003A\u003A\u0024startColumn",
            "name": "startColumn",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-Columns.html#property_startColumn"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\Columns\u003A\u003A\u0024endColumn",
            "name": "endColumn",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-Columns.html#property_endColumn"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\from_google_sheet\u0028\u0029",
            "name": "from_google_sheet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-googlesheet.html#function_from_google_sheet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\from_google_sheet_columns\u0028\u0029",
            "name": "from_google_sheet_columns",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-googlesheet.html#function_from_google_sheet_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor",
            "name": "GoogleSheetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003AwithDropExtraColumns\u0028\u0029",
            "name": "withDropExtraColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method_withDropExtraColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003AwithOptions\u0028\u0029",
            "name": "withOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method_withOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\GoogleSheetExtractor\u003A\u003AwithRowsPerPage\u0028\u0029",
            "name": "withRowsPerPage",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-GoogleSheetExtractor.html#method_withRowsPerPage"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange",
            "name": "SheetRange",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003AnextRows\u0028\u0029",
            "name": "nextRows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#method_nextRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#method_toString"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003A\u0024columnRange",
            "name": "columnRange",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#property_columnRange"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003A\u0024startRow",
            "name": "startRow",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#property_startRow"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet\\SheetRange\u003A\u003A\u0024endRow",
            "name": "endRow",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-GoogleSheet-SheetRange.html#property_endRow"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\GoogleSheet",
            "name": "GoogleSheet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-googlesheet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
