Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig",
            "name": "RequestConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003AbodySizeLimit\u0028\u0029",
            "name": "bodySizeLimit",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_bodySizeLimit"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003AincludeBody\u0028\u0029",
            "name": "includeBody",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_includeBody"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003AincludeHeaders\u0028\u0029",
            "name": "includeHeaders",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_includeHeaders"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003AincludeMethod\u0028\u0029",
            "name": "includeMethod",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_includeMethod"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003AincludeUri\u0028\u0029",
            "name": "includeUri",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_includeUri"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\RequestConfig\u003A\u003Asanitizers\u0028\u0029",
            "name": "sanitizers",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-RequestConfig.html#method_sanitizers"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig",
            "name": "ResponseConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AbodySizeLimit\u0028\u0029",
            "name": "bodySizeLimit",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_bodySizeLimit"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AexcludeStatusCodes\u0028\u0029",
            "name": "excludeStatusCodes",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_excludeStatusCodes"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AincludeBody\u0028\u0029",
            "name": "includeBody",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_includeBody"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AincludeHeaders\u0028\u0029",
            "name": "includeHeaders",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_includeHeaders"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AincludeReasonPhrase\u0028\u0029",
            "name": "includeReasonPhrase",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_includeReasonPhrase"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003AincludeStatus\u0028\u0029",
            "name": "includeStatus",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_includeStatus"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\\ResponseConfig\u003A\u003Asanitizers\u0028\u0029",
            "name": "sanitizers",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config-ResponseConfig.html#method_sanitizers"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config.html#property_request"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Config.html#property_response"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\DSL\\mask\u0028\u0029",
            "name": "mask",
            "summary": "Create\u0020a\u0020new\u0020Mask\u0020sanitizer.",
            "url": "namespaces/flow-bridge-monolog-http-dsl.html#function_mask"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Exception\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Exception-Exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\PSR7Processor",
            "name": "PSR7Processor",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-PSR7Processor.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\PSR7Processor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-PSR7Processor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\PSR7Processor\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-PSR7Processor.html#method___invoke"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Mask",
            "name": "Mask",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Mask.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Mask\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Mask.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Mask\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "Create\u0020a\u0020Mask\u0020sanitizer\u0020from\u0020an\u0020array\u0020representation.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Mask.html#method_fromArray"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Mask\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Return\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020sanitizer.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Mask.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Mask\u003A\u003Asanitize\u0028\u0029",
            "name": "sanitize",
            "summary": "Sanitize\u0020a\u0020string\u0020value.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Mask.html#method_sanitize"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Sanitizer",
            "name": "Sanitizer",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Sanitizer.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Sanitizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Return\u0020an\u0020array\u0020representation\u0020of\u0020the\u0020sanitizer.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Sanitizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\Sanitizer\u003A\u003Asanitize\u0028\u0029",
            "name": "sanitize",
            "summary": "Sanitize\u0020a\u0020string\u0020value.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-Sanitizer.html#method_sanitize"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\SanitizerFactory",
            "name": "SanitizerFactory",
            "summary": "",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-SanitizerFactory.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization\\SanitizerFactory\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "Create\u0020a\u0020sanitizer\u0020from\u0020an\u0020array\u0020representation.",
            "url": "classes/Flow-Bridge-Monolog-Http-Sanitization-SanitizerFactory.html#method_fromArray"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Config",
            "name": "Config",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog-http-config.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog-http.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog",
            "name": "Monolog",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog-http-dsl.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog-http-exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Monolog\\Http\\Sanitization",
            "name": "Sanitization",
            "summary": "",
            "url": "namespaces/flow-bridge-monolog-http-sanitization.html"
        }            ]
);
