Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\from_text\u0028\u0029",
            "name": "from_text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html#function_from_text"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\to_text\u0028\u0029",
            "name": "to_text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html#function_to_text"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor",
            "name": "TextExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader",
            "name": "TextLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003AwithNewLineSeparator\u0028\u0029",
            "name": "withNewLineSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_withNewLineSeparator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text",
            "name": "Text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
