Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\from_text\u0028\u0029",
            "name": "from_text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html#function_from_text"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\to_text\u0028\u0029",
            "name": "to_text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html#function_to_text"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextEncoder",
            "name": "TextEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextEncoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextEncoder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor",
            "name": "TextExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003ApartitionSchema\u0028\u0029",
            "name": "partitionSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_partitionSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003Astatistics\u0028\u0029",
            "name": "statistics",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_statistics"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextFileBatches",
            "name": "TextFileBatches",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextFileBatches.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextFileBatches\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextFileBatches.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextFileBatches\u003A\u003Abatches\u0028\u0029",
            "name": "batches",
            "summary": "The\u0020lines\u0020into\u0020the\u0020\u0022text\u0022\u0020column\u003B\u0020any\u0020other\u0020column\u0020\u0024body\u0020declares\u0020is\u0020padded\u0020as\u0020matchTo\u0028\u0029\u0020pads\u0020it.",
            "url": "classes/Flow-ETL-Adapter-Text-TextFileBatches.html#method_batches"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextFileBatches\u003A\u003Abatch\u0028\u0029",
            "name": "batch",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextFileBatches.html#method_batch"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader",
            "name": "TextLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003ApartitionBy\u0028\u0029",
            "name": "partitionBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_partitionBy"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Adiscard\u0028\u0029",
            "name": "discard",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_discard"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_open"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003AsaveMode\u0028\u0029",
            "name": "saveMode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_saveMode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextLoader\u003A\u003AwithNewLineSeparator\u0028\u0029",
            "name": "withNewLineSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextLoader.html#method_withNewLineSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextOpenSink",
            "name": "TextOpenSink",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextOpenSink.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextOpenSink\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextOpenSink.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextOpenSink\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "The\u0020stream\u0020belongs\u0020to\u0020the\u0020FilesSink\u0020that\u0020opened\u0020it.",
            "url": "classes/Flow-ETL-Adapter-Text-TextOpenSink.html#method_close"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text\\TextOpenSink\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Text-TextOpenSink.html#method_write"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Text",
            "name": "Text",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-text.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
