Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\DocumentDataSource",
            "name": "DocumentDataSource",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-DocumentDataSource.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\DocumentDataSource\u003A\u003Afields",
            "name": "fields",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-DocumentDataSource.html#enumcase_fields"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\DocumentDataSource\u003A\u003Asource",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-DocumentDataSource.html#enumcase_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchExtractor",
            "name": "ElasticsearchExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchExtractor\u003A\u003AwithPointInTime\u0028\u0029",
            "name": "withPointInTime",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchExtractor.html#method_withPointInTime"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchLoader",
            "name": "ElasticsearchLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchLoader\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchLoader.html#method_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\ElasticsearchLoader\u003A\u003AwithParameters\u0028\u0029",
            "name": "withParameters",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-ElasticsearchLoader.html#method_withParameters"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\HitsIntoRowsTransformer",
            "name": "HitsIntoRowsTransformer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-HitsIntoRowsTransformer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\HitsIntoRowsTransformer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-HitsIntoRowsTransformer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\HitsIntoRowsTransformer\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-HitsIntoRowsTransformer.html#method_transform"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\PointInTime",
            "name": "PointInTime",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-PointInTime.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\PointInTime\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-PointInTime.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\PointInTime\u003A\u003Aid\u0028\u0029",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-PointInTime.html#method_id"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams",
            "name": "SearchParams",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003AasArray\u0028\u0029",
            "name": "asArray",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method_asArray"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003AhasSort\u0028\u0029",
            "name": "hasSort",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method_hasSort"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method_remove"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchParams\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchParams.html#method_setBody"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults",
            "name": "SearchResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003AlastHitSort\u0028\u0029",
            "name": "lastHitSort",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method_lastHitSort"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method_pages"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method_size"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003AtoRows\u0028\u0029",
            "name": "toRows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method_toRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP\\SearchResults\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-ElasticsearchPHP-SearchResults.html#method_total"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\EntryIdFactory",
            "name": "EntryIdFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-EntryIdFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\EntryIdFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-EntryIdFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\EntryIdFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-EntryIdFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\HashIdFactory",
            "name": "HashIdFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-HashIdFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\HashIdFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-HashIdFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\HashIdFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-HashIdFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory\\HashIdFactory\u003A\u003AwithAlgorithm\u0028\u0029",
            "name": "withAlgorithm",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-EntryIdFactory-HashIdFactory.html#method_withAlgorithm"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\to_es_bulk_index\u0028\u0029",
            "name": "to_es_bulk_index",
            "summary": "https\u003A\/\/www.elastic.co\/guide\/en\/elasticsearch\/reference\/master\/docs\u002Dbulk.html.",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_to_es_bulk_index"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\entry_id_factory\u0028\u0029",
            "name": "entry_id_factory",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_entry_id_factory"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\hash_id_factory\u0028\u0029",
            "name": "hash_id_factory",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_hash_id_factory"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\to_es_bulk_update\u0028\u0029",
            "name": "to_es_bulk_update",
            "summary": "https\u003A\/\/www.elastic.co\/guide\/en\/elasticsearch\/reference\/master\/docs\u002Dbulk.html.",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_to_es_bulk_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\es_hits_to_rows\u0028\u0029",
            "name": "es_hits_to_rows",
            "summary": "Transforms\u0020elasticsearch\u0020results\u0020into\u0020clear\u0020Flow\u0020Rows\u0020using\u0020\u005B\u0027hits\u0027\u005D\u005B\u0027hits\u0027\u005D\u005Bx\u005D\u005B\u0027_source\u0027\u005D.",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_es_hits_to_rows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\from_es\u0028\u0029",
            "name": "from_es",
            "summary": "Extractor\u0020will\u0020automatically\u0020try\u0020to\u0020iterate\u0020over\u0020whole\u0020index\u0020using\u0020one\u0020of\u0020the\u0020two\u0020iteration\u0020methods\u003A.",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html#function_from_es"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\IdFactory",
            "name": "IdFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-IdFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\IdFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Elasticsearch-IdFactory.html#method_create"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\ElasticsearchPHP",
            "name": "ElasticsearchPHP",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-elasticsearch-elasticsearchphp.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch\\EntryIdFactory",
            "name": "EntryIdFactory",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-elasticsearch-entryidfactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Elasticsearch",
            "name": "Elasticsearch",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-elasticsearch.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
