Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL\\schema_to_openapi_specification\u0028\u0029",
            "name": "schema_to_openapi_specification",
            "summary": "Convert\u0020Flow\u0020Schema\u0020to\u0020OpenAPI\u0020specification\u0020format.",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html#function_schema_to_openapi_specification"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL\\schema_from_openapi_specification\u0028\u0029",
            "name": "schema_from_openapi_specification",
            "summary": "Convert\u0020OpenAPI\u0020specification\u0020to\u0020Flow\u0020Schema.",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html#function_schema_from_openapi_specification"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-Exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter",
            "name": "OpenAPIConverter",
            "summary": "Bidirectional\u0020converter\u0020between\u0020Flow\u0020PHP\u0020schemas\u0020and\u0020OpenAPI\u00203.0\u0020specifications.",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter\u003A\u003AfromOpenAPI\u0028\u0029",
            "name": "fromOpenAPI",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html#method_fromOpenAPI"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter\u003A\u003AtoOpenAPI\u0028\u0029",
            "name": "toOpenAPI",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html#method_toOpenAPI"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata",
            "name": "OpenAPIMetadata",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Adefault\u0028\u0029",
            "name": "default",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_default"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Adeprecated\u0028\u0029",
            "name": "deprecated",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_deprecated"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Adescription\u0028\u0029",
            "name": "description",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_description"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Aexample\u0028\u0029",
            "name": "example",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_example"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Aexamples\u0028\u0029",
            "name": "examples",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_examples"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Aformat\u0028\u0029",
            "name": "format",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_format"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Anullable\u0028\u0029",
            "name": "nullable",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_nullable"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AreadOnly\u0028\u0029",
            "name": "readOnly",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_readOnly"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003Atitle\u0028\u0029",
            "name": "title",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_title"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AwriteOnly\u0028\u0029",
            "name": "writeOnly",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#method_writeOnly"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_DEFAULT"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003ADEPRECATED",
            "name": "DEPRECATED",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_DEPRECATED"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003ADESCRIPTION",
            "name": "DESCRIPTION",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_DESCRIPTION"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AEXAMPLE",
            "name": "EXAMPLE",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_EXAMPLE"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AEXAMPLES",
            "name": "EXAMPLES",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_EXAMPLES"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AFORMAT",
            "name": "FORMAT",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_FORMAT"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003ANULLABLE",
            "name": "NULLABLE",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_NULLABLE"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AREAD_ONLY",
            "name": "READ_ONLY",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_READ_ONLY"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003ATITLE",
            "name": "TITLE",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_TITLE"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIMetadata\u003A\u003AWRITE_ONLY",
            "name": "WRITE_ONLY",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIMetadata.html#enumcase_WRITE_ONLY"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification-exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification",
            "name": "Specification",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI",
            "name": "OpenAPI",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
