Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL\\schema_to_openapi_specification\u0028\u0029",
            "name": "schema_to_openapi_specification",
            "summary": "Convert\u0020Flow\u0020Schema\u0020to\u0020OpenAPI\u0020specification\u0020format.",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html#function_schema_to_openapi_specification"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL\\schema_from_openapi_specification\u0028\u0029",
            "name": "schema_from_openapi_specification",
            "summary": "Convert\u0020OpenAPI\u0020specification\u0020to\u0020Flow\u0020Schema.",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html#function_schema_from_openapi_specification"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-Exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter",
            "name": "OpenAPIConverter",
            "summary": "Bidirectional\u0020converter\u0020between\u0020Flow\u0020PHP\u0020schemas\u0020and\u0020OpenAPI\u00203.0\u0020specifications.",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter\u003A\u003AfromOpenAPI\u0028\u0029",
            "name": "fromOpenAPI",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html#method_fromOpenAPI"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\OpenAPIConverter\u003A\u003AtoOpenAPI\u0028\u0029",
            "name": "toOpenAPI",
            "summary": "",
            "url": "classes/Flow-Bridge-OpenAPI-Specification-OpenAPIConverter.html#method_toOpenAPI"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification-dsl.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification-exception.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI\\Specification",
            "name": "Specification",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi-specification.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\OpenAPI",
            "name": "OpenAPI",
            "summary": "",
            "url": "namespaces/flow-bridge-openapi.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
