Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap",
            "name": "EntryTypesMap",
            "summary": "Maps\u0020between\u0020Flow\u0020ETL\u0020types\u0020and\u0020PostgreSQL\u0020types.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Maps\u0020a\u0020column\u0020value\u0020\u002B\u0020Flow\u0020type\u0020to\u0020a\u0020TypedValue\u0020suitable\u0020for\u0020PostgreSQL\u0020queries.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html#method_map"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap\u003A\u003AtoColumnType\u0028\u0029",
            "name": "toColumnType",
            "summary": "Maps\u0020a\u0020Flow\u0020type\u0020to\u0020a\u0020PostgreSQL\u0020DDL\u0020column\u0020type.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html#method_toColumnType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "Maps\u0020a\u0020PostgreSQL\u0020DDL\u0020column\u0020type\u0020back\u0020to\u0020a\u0020canonical\u0020Flow\u0020type.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\EntryTypesMap\u003A\u003ADEFAULT_TYPES",
            "name": "DEFAULT_TYPES",
            "summary": "Default\u0020mapping\u0020of\u0020Flow\u0020type\u0020classes\u0020to\u0020PostgreSQL\u0020value\u0020types.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-EntryTypesMap.html#constant_DEFAULT_TYPES"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException",
            "name": "TypeMappingException",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException\u003A\u003AambiguousEntryType\u0028\u0029",
            "name": "ambiguousEntryType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html#method_ambiguousEntryType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException\u003A\u003AunsupportedColumnType\u0028\u0029",
            "name": "unsupportedColumnType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html#method_unsupportedColumnType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException\u003A\u003AunsupportedEntryType\u0028\u0029",
            "name": "unsupportedEntryType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html#method_unsupportedEntryType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException\u003A\u003AunmappedColumn\u0028\u0029",
            "name": "unmappedColumn",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html#method_unmappedColumn"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception\\TypeMappingException\u003A\u003AunsupportedFlowType\u0028\u0029",
            "name": "unsupportedFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Exception-TypeMappingException.html#method_unsupportedFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\from_pgsql_cursor\u0028\u0029",
            "name": "from_pgsql_cursor",
            "summary": "Create\u0020a\u0020PostgreSQL\u0020cursor\u0020extractor\u0020using\u0020server\u002Dside\u0020cursors\u0020for\u0020memory\u002Defficient\u0020extraction.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_from_pgsql_cursor"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\from_pgsql_limit_offset\u0028\u0029",
            "name": "from_pgsql_limit_offset",
            "summary": "Create\u0020a\u0020PostgreSQL\u0020extractor\u0020using\u0020LIMIT\/OFFSET\u0020pagination.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_from_pgsql_limit_offset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\from_pgsql_key_set\u0028\u0029",
            "name": "from_pgsql_key_set",
            "summary": "Create\u0020a\u0020PostgreSQL\u0020extractor\u0020using\u0020keyset\u0020\u0028cursor\u002Dbased\u0029\u0020pagination.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_from_pgsql_key_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_pagination_key_asc\u0028\u0029",
            "name": "pgsql_pagination_key_asc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_pagination_key_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_pagination_key_desc\u0028\u0029",
            "name": "pgsql_pagination_key_desc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_pagination_key_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_pagination_key_set\u0028\u0029",
            "name": "pgsql_pagination_key_set",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_pagination_key_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\to_pgsql_table\u0028\u0029",
            "name": "to_pgsql_table",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_to_pgsql_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\to_pgsql_transaction\u0028\u0029",
            "name": "to_pgsql_transaction",
            "summary": "Execute\u0020multiple\u0020loaders\u0020within\u0020PostgreSQL\u0020transactions.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_to_pgsql_transaction"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_insert_options\u0028\u0029",
            "name": "pgsql_insert_options",
            "summary": "Create\u0020insert\u0020options\u0020for\u0020PostgreSQL\u0020loader.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_update_options\u0028\u0029",
            "name": "pgsql_update_options",
            "summary": "Create\u0020update\u0020options\u0020for\u0020PostgreSQL\u0020loader.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_update_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_delete_options\u0028\u0029",
            "name": "pgsql_delete_options",
            "summary": "Create\u0020delete\u0020options\u0020for\u0020PostgreSQL\u0020loader.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_delete_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\to_pgsql_schema_table\u0028\u0029",
            "name": "to_pgsql_schema_table",
            "summary": "Convert\u0020a\u0020Flow\u0020Schema\u0020into\u0020a\u0020PostgreSQL\u0020table\u0020definition.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_to_pgsql_schema_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_table_to_flow_schema\u0028\u0029",
            "name": "pgsql_table_to_flow_schema",
            "summary": "Convert\u0020a\u0020PostgreSQL\u0020table\u0020definition\u0020into\u0020a\u0020Flow\u0020Schema.",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_table_to_flow_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\pgsql_schema_sort_by_type\u0028\u0029",
            "name": "pgsql_schema_sort_by_type",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html#function_pgsql_schema_sort_by_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\DeleteOptions",
            "name": "DeleteOptions",
            "summary": "Configuration\u0020options\u0020for\u0020DELETE\u0020operations\u0020in\u0020PostgreSQL\u0020loader.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-DeleteOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\DeleteOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-DeleteOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\DeleteOptions\u003A\u003A\u0024primaryKeys",
            "name": "primaryKeys",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-DeleteOptions.html#property_primaryKeys"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions",
            "name": "InsertOptions",
            "summary": "Configuration\u0020options\u0020for\u0020INSERT\u0020operations\u0020in\u0020PostgreSQL\u0020loader.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003A\u0024skipConflicts",
            "name": "skipConflicts",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#property_skipConflicts"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003AupsertOnColumns\u0028\u0029",
            "name": "upsertOnColumns",
            "summary": "Create\u0020options\u0020for\u0020upserting\u0020on\u0020specific\u0020columns.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#method_upsertOnColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003AupsertOnConstraint\u0028\u0029",
            "name": "upsertOnConstraint",
            "summary": "Create\u0020options\u0020for\u0020upserting\u0020on\u0020a\u0020constraint.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#method_upsertOnConstraint"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003AhasConflictHandling\u0028\u0029",
            "name": "hasConflictHandling",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#method_hasConflictHandling"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003A\u0024conflictColumns",
            "name": "conflictColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#property_conflictColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003A\u0024conflictConstraint",
            "name": "conflictConstraint",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#property_conflictConstraint"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\InsertOptions\u003A\u003A\u0024updateColumns",
            "name": "updateColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-InsertOptions.html#property_updateColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\UpdateOptions",
            "name": "UpdateOptions",
            "summary": "Configuration\u0020options\u0020for\u0020UPDATE\u0020operations\u0020in\u0020PostgreSQL\u0020loader.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-UpdateOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\UpdateOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-UpdateOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions\\UpdateOptions\u003A\u003A\u0024primaryKeys",
            "name": "primaryKeys",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-LoaderOptions-UpdateOptions.html#property_primaryKeys"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Operation",
            "name": "Operation",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Operation.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Operation\u003A\u003ADELETE",
            "name": "DELETE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Operation.html#enumcase_DELETE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Operation\u003A\u003AINSERT",
            "name": "INSERT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Operation.html#enumcase_INSERT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Operation\u003A\u003AUPDATE",
            "name": "UPDATE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Operation.html#enumcase_UPDATE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key",
            "name": "Key",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003Aasc\u0028\u0029",
            "name": "asc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#method_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003Adesc\u0028\u0029",
            "name": "desc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#method_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003AtoKeysetColumn\u0028\u0029",
            "name": "toKeysetColumn",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#method_toKeysetColumn"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#property_column"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Key\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Key.html#property_order"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\KeySet",
            "name": "KeySet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-KeySet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\KeySet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-KeySet.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\KeySet\u003A\u003AtoKeysetColumns\u0028\u0029",
            "name": "toKeysetColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-KeySet.html#method_toKeysetColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\KeySet\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-KeySet.html#property_keys"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Order.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Order\u003A\u003AtoSortOrder\u0028\u0029",
            "name": "toSortOrder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Order.html#method_toSortOrder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Order\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Order.html#enumcase_ASC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination\\Order\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Pagination-Order.html#enumcase_DESC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor",
            "name": "PostgreSqlCursorExtractor",
            "summary": "PostgreSQL\u0020extractor\u0020using\u0020server\u002Dside\u0020cursors\u0020for\u0020memory\u002Defficient\u0020extraction.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003AwithCursorName\u0028\u0029",
            "name": "withCursorName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method_withCursorName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003AwithFetchSize\u0028\u0029",
            "name": "withFetchSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method_withFetchSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlCursorExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlCursorExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlEncoder",
            "name": "PostgreSqlEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor",
            "name": "PostgreSqlKeySetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor\u003A\u003AwithPageSize\u0028\u0029",
            "name": "withPageSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html#method_withPageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlKeySetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlKeySetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor",
            "name": "PostgreSqlLimitOffsetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor\u003A\u003AwithPageSize\u0028\u0029",
            "name": "withPageSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html#method_withPageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLimitOffsetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLimitOffsetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader",
            "name": "PostgreSqlLoader",
            "summary": "PostgreSQL\u0020loader\u0020for\u0020ETL\u0020pipelines.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003AwithDeleteOptions\u0028\u0029",
            "name": "withDeleteOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_withDeleteOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003AwithInsertOptions\u0028\u0029",
            "name": "withInsertOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_withInsertOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003AwithOperation\u0028\u0029",
            "name": "withOperation",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_withOperation"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003AwithTypesMap\u0028\u0029",
            "name": "withTypesMap",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_withTypesMap"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlLoader\u003A\u003AwithUpdateOptions\u0028\u0029",
            "name": "withUpdateOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlLoader.html#method_withUpdateOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata",
            "name": "PostgreSqlMetadata",
            "summary": "Per\u002Dcolumn\u0020metadata\u0020keys\u0020understood\u0020by\u0020\u007B\u0040see\u0020SchemaConverter\u007D\u0020when\u0020converting\u0020a\u0020Flow\u0020Schema\u0020to\u0020a\nPostgreSQL\u0020table.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Adefault\u0028\u0029",
            "name": "default",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_default"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Agenerated\u0028\u0029",
            "name": "generated",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_generated"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Aidentity\u0028\u0029",
            "name": "identity",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_identity"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_index"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AindexUnique\u0028\u0029",
            "name": "indexUnique",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_indexUnique"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_length"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Aprecision\u0028\u0029",
            "name": "precision",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_precision"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AprimaryKey\u0028\u0029",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_primaryKey"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_scale"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_DEFAULT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AGENERATED",
            "name": "GENERATED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_GENERATED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AIDENTITY",
            "name": "IDENTITY",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_IDENTITY"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AINDEX",
            "name": "INDEX",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_INDEX"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003AINDEX_UNIQUE",
            "name": "INDEX_UNIQUE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_INDEX_UNIQUE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003ALENGTH",
            "name": "LENGTH",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_LENGTH"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003APRECISION",
            "name": "PRECISION",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_PRECISION"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003APRIMARY_KEY",
            "name": "PRIMARY_KEY",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_PRIMARY_KEY"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003ASCALE",
            "name": "SCALE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_SCALE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\PostgreSqlMetadata\u003A\u003ATYPE",
            "name": "TYPE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-PostgreSqlMetadata.html#enumcase_TYPE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\DeleteQueryBuilder",
            "name": "DeleteQueryBuilder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-DeleteQueryBuilder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\DeleteQueryBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-DeleteQueryBuilder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\DeleteQueryBuilder\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-DeleteQueryBuilder.html#method_build"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\InsertQueryBuilder",
            "name": "InsertQueryBuilder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-InsertQueryBuilder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\InsertQueryBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-InsertQueryBuilder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\InsertQueryBuilder\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-InsertQueryBuilder.html#method_build"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\UpdateQueryBuilder",
            "name": "UpdateQueryBuilder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-UpdateQueryBuilder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\UpdateQueryBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-UpdateQueryBuilder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder\\UpdateQueryBuilder\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-QueryBuilder-UpdateQueryBuilder.html#method_build"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Schema\\SortingStrategy\\TypeStrategy",
            "name": "TypeStrategy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Schema-SortingStrategy-TypeStrategy.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Schema\\SortingStrategy\\TypeStrategy\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Schema-SortingStrategy-TypeStrategy.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Schema\\SortingStrategy\\TypeStrategy\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-Schema-SortingStrategy-TypeStrategy.html#method_compare"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "Converts\u0020between\u0020a\u0020Flow\u0020\u007B\u0040see\u0020Schema\u007D\u0020and\u0020a\u0020PostgreSQL\u0020\u007B\u0040see\u0020Table\u007D.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\SchemaConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-SchemaConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\SchemaConverter\u003A\u003AtoFlowSchema\u0028\u0029",
            "name": "toFlowSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-SchemaConverter.html#method_toFlowSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\SchemaConverter\u003A\u003AtoPostgreSqlTable\u0028\u0029",
            "name": "toPostgreSqlTable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-SchemaConverter.html#method_toPostgreSqlTable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader",
            "name": "TransactionalPostgreSqlLoader",
            "summary": "Execute\u0020multiple\u0020loaders\u0020within\u0020PostgreSQL\u0020transactions.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "Rows\u0020a\u0020wrapped\u0020Transformation\u0020buffered\u0020\u0028blocking\u0020operations\u0020\u002D\u0020sortBy,\u0020aggregate,\u0020groupBy\u002D\u003Eaggregate,\npivot,\u0020window\u0020functions,\u0020collect,\u0020join\u0029\u0020are\u0020delivered\u0020during\u0020the\u0020forwarded\u0020closure\u0028\u0029\u0020drain,\u0020so\u0020delivery\nhere\u0020must\u0020be\u0020transactional\u0020too\u003A\u0020one\u0020transaction\u0020over\u0020everything\u0020the\u0020drain\u0020flushes,\u0020rolled\u0020back\u0020when\u0020it\u0020fails.",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader\u003A\u003Aloaders\u0028\u0029",
            "name": "loaders",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html#method_loaders"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\TransactionalPostgreSqlLoader\u003A\u003AwithIsolationLevel\u0028\u0029",
            "name": "withIsolationLevel",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-TransactionalPostgreSqlLoader.html#method_withIsolationLevel"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\EnumConverter",
            "name": "EnumConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-EnumConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\EnumConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-EnumConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\EnumConverter\u003A\u003AsupportedTypes\u0028\u0029",
            "name": "supportedTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-EnumConverter.html#method_supportedTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\EnumConverter\u003A\u003AtoDatabase\u0028\u0029",
            "name": "toDatabase",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-EnumConverter.html#method_toDatabase"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\HTMLConverter",
            "name": "HTMLConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-HTMLConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\HTMLConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-HTMLConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\HTMLConverter\u003A\u003AsupportedTypes\u0028\u0029",
            "name": "supportedTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-HTMLConverter.html#method_supportedTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\HTMLConverter\u003A\u003AtoDatabase\u0028\u0029",
            "name": "toDatabase",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-HTMLConverter.html#method_toDatabase"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\XMLConverter",
            "name": "XMLConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-XMLConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\XMLConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-XMLConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\XMLConverter\u003A\u003AsupportedTypes\u0028\u0029",
            "name": "supportedTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-XMLConverter.html#method_supportedTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter\\XMLConverter\u003A\u003AtoDatabase\u0028\u0029",
            "name": "toDatabase",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-PostgreSql-ValueConverter-XMLConverter.html#method_toDatabase"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql",
            "name": "PostgreSql",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-exception.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\LoaderOptions",
            "name": "LoaderOptions",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-loaderoptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Pagination",
            "name": "Pagination",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-pagination.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\QueryBuilder",
            "name": "QueryBuilder",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-querybuilder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Schema\\SortingStrategy",
            "name": "SortingStrategy",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-schema-sortingstrategy.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\Schema",
            "name": "Schema",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-schema.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\PostgreSql\\ValueConverter",
            "name": "ValueConverter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-postgresql-valueconverter.html"
        }            ]
);
