Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntries",
            "name": "DirectoryEntries",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntries.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntries\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntries.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntries\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntries.html#method_getIterator"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry",
            "name": "DirectoryEntry",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003Afile\u0028\u0029",
            "name": "file",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#method_file"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003Asubdirectory\u0028\u0029",
            "name": "subdirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#method_subdirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#property_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003A\u0024isDirectory",
            "name": "isDirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#property_isDirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#property_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003A\u0024modifiedAt",
            "name": "modifiedAt",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#property_modifiedAt"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryEntry\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryEntry.html#property_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryListing",
            "name": "DirectoryListing",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryListing.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryListing\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryListing.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DirectoryListing\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-DirectoryListing.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DSL\\sftp_client\u0028\u0029",
            "name": "sftp_client",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp-dsl.html#function_sftp_client"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DSL\\sftp_filesystem\u0028\u0029",
            "name": "sftp_filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp-dsl.html#function_sftp_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DSL\\sftp_filesystem_options\u0028\u0029",
            "name": "sftp_filesystem_options",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp-dsl.html#function_sftp_filesystem_options"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AblockFactory\u0028\u0029",
            "name": "blockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_blockFactory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AblockSize\u0028\u0029",
            "name": "blockSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_blockSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AreadChunkSize\u0028\u0029",
            "name": "readChunkSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_readChunkSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AtmpDir\u0028\u0029",
            "name": "tmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_tmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AwithBlockFactory\u0028\u0029",
            "name": "withBlockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_withBlockFactory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AwithBlockSize\u0028\u0029",
            "name": "withBlockSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_withBlockSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AwithReadChunkSize\u0028\u0029",
            "name": "withReadChunkSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_withReadChunkSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003AwithTmpDir\u0028\u0029",
            "name": "withTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#method_withTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003ADEFAULT_BLOCK_SIZE",
            "name": "DEFAULT_BLOCK_SIZE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#constant_DEFAULT_BLOCK_SIZE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\Options\u003A\u003ADEFAULT_READ_CHUNK_SIZE",
            "name": "DEFAULT_READ_CHUNK_SIZE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-Options.html#constant_DEFAULT_READ_CHUNK_SIZE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\SFTPBlockLifecycle",
            "name": "SFTPBlockLifecycle",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-SFTPBlockLifecycle.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\SFTPBlockLifecycle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-SFTPBlockLifecycle.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\SFTPBlockLifecycle\u003A\u003Afilled\u0028\u0029",
            "name": "filled",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-SFTPBlockLifecycle.html#method_filled"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\SFTPBlockLifecycle\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-SFTPBlockLifecycle.html#property_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteMode",
            "name": "WriteMode",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteMode.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteMode\u003A\u003AAPPEND",
            "name": "APPEND",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteMode.html#enumcase_APPEND"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteMode\u003A\u003ABLANK",
            "name": "BLANK",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteMode.html#enumcase_BLANK"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteOffset",
            "name": "WriteOffset",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteOffset.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteOffset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteOffset.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteOffset\u003A\u003Aadvance\u0028\u0029",
            "name": "advance",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteOffset.html#method_advance"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\\WriteOffset\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream-WriteOffset.html#method_current"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream",
            "name": "SFTPDestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003AopenAppend\u0028\u0029",
            "name": "openAppend",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_openAppend"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003AopenBlank\u0028\u0029",
            "name": "openBlank",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_openBlank"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPDestinationStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem",
            "name": "SFTPFilesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Amount\u0028\u0029",
            "name": "mount",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_mount"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_supports"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPFilesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPFilesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream",
            "name": "SFTPSourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPSourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-SFTP-SFTPSourceStream.html#method_size"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP",
            "name": "SFTP",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge.html"
        },                {
            "fqsen": "\\Flow\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp-dsl.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\SFTP\\SFTPDestinationStream",
            "name": "SFTPDestinationStream",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-sftp-sftpdestinationstream.html"
        }            ]
);
