Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory",
            "name": "DbalDataFrameFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003AfromConnection\u0028\u0029",
            "name": "fromConnection",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_fromConnection"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_from"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor",
            "name": "DbalKeySetExtractor",
            "summary": "Extractor\u0020implementing\u0020keyset\u0020pagination\u0020for\u0020Doctrine\u0020DBAL\u0020queries.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithKeyAliasSuffix\u0028\u0029",
            "name": "withKeyAliasSuffix",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withKeyAliasSuffix"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "Sets\u0020the\u0020maximum\u0020number\u0020of\u0020rows\u0020to\u0020fetch.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithPageSize\u0028\u0029",
            "name": "withPageSize",
            "summary": "Sets\u0020the\u0020number\u0020of\u0020rows\u0020per\u0020page.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withPageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "Sets\u0020the\u0020schema\u0020for\u0020the\u0020extracted\u0020rows.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor",
            "name": "DbalLimitOffsetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003Atable\u0028\u0029",
            "name": "table",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithOffset\u0028\u0029",
            "name": "withOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithPageSize\u0028\u0029",
            "name": "withPageSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withPageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader",
            "name": "DbalLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AfromConnection\u0028\u0029",
            "name": "fromConnection",
            "summary": "Since\u0020Connection\u003A\u003AgetParams\u0028\u0029\u0020is\u0020marked\u0020as\u0020an\u0020internal\u0020method,\u0020please\nuse\u0020this\u0020constructor\u0020with\u0020caution.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_fromConnection"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AwithOperation\u0028\u0029",
            "name": "withOperation",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_withOperation"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AwithOperationOptions\u0028\u0029",
            "name": "withOperationOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_withOperationOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata",
            "name": "DbalMetadata",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AcolumnDefinition\u0028\u0029",
            "name": "columnDefinition",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_columnDefinition"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Acomment\u0028\u0029",
            "name": "comment",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_comment"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Adefault\u0028\u0029",
            "name": "default",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_default"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Afixed\u0028\u0029",
            "name": "fixed",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_fixed"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_index"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AindexUnique\u0028\u0029",
            "name": "indexUnique",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_indexUnique"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_length"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AplatformOptions\u0028\u0029",
            "name": "platformOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_platformOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aprecision\u0028\u0029",
            "name": "precision",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_precision"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AprimaryKey\u0028\u0029",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_primaryKey"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_scale"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aunsigned\u0028\u0029",
            "name": "unsigned",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_unsigned"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACOLUMN_DEFINITION",
            "name": "COLUMN_DEFINITION",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_COLUMN_DEFINITION"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACOMMENT",
            "name": "COMMENT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_COMMENT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACUSTOM_SCHEMA_OPTIONS",
            "name": "CUSTOM_SCHEMA_OPTIONS",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_CUSTOM_SCHEMA_OPTIONS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_DEFAULT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AFIXED",
            "name": "FIXED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_FIXED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AINDEX",
            "name": "INDEX",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_INDEX"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AINDEX_UNIQUE",
            "name": "INDEX_UNIQUE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_INDEX_UNIQUE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ALENGTH",
            "name": "LENGTH",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_LENGTH"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APLATFORM_OPTIONS",
            "name": "PLATFORM_OPTIONS",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PLATFORM_OPTIONS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APRECISION",
            "name": "PRECISION",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PRECISION"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APRIMARY_KEY",
            "name": "PRIMARY_KEY",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PRIMARY_KEY"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ASCALE",
            "name": "SCALE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_SCALE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ATYPE",
            "name": "TYPE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_TYPE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AUNSIGNED",
            "name": "UNSIGNED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_UNSIGNED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor",
            "name": "DbalQueryExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003Asingle\u0028\u0029",
            "name": "single",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_single"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithParameters\u0028\u0029",
            "name": "withParameters",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withParameters"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithTypes\u0028\u0029",
            "name": "withTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_dataframe_factory\u0028\u0029",
            "name": "dbal_dataframe_factory",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_dataframe_factory"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_limit_offset\u0028\u0029",
            "name": "from_dbal_limit_offset",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_limit_offset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_limit_offset_qb\u0028\u0029",
            "name": "from_dbal_limit_offset_qb",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_limit_offset_qb"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_key_set_qb\u0028\u0029",
            "name": "from_dbal_key_set_qb",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_key_set_qb"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_queries\u0028\u0029",
            "name": "from_dbal_queries",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_queries"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_from_queries\u0028\u0029",
            "name": "dbal_from_queries",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_from_queries"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_query\u0028\u0029",
            "name": "from_dbal_query",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_query"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_from_query\u0028\u0029",
            "name": "dbal_from_query",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_from_query"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_insert\u0028\u0029",
            "name": "to_dbal_table_insert",
            "summary": "Insert\u0020new\u0020rows\u0020into\u0020a\u0020database\u0020table.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_insert"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_update\u0028\u0029",
            "name": "to_dbal_table_update",
            "summary": "Update\u0020existing\u0020rows\u0020in\u0020database.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_delete\u0028\u0029",
            "name": "to_dbal_table_delete",
            "summary": "Delete\u0020rows\u0020from\u0020database\u0020table\u0020based\u0020on\u0020the\u0020provided\u0020data.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_delete"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_schema_table\u0028\u0029",
            "name": "to_dbal_schema_table",
            "summary": "Converts\u0020a\u0020Flow\\ETL\\Schema\u0020to\u0020a\u0020Doctrine\\DBAL\\Schema\\Table.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_schema_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\table_schema_to_flow_schema\u0028\u0029",
            "name": "table_schema_to_flow_schema",
            "summary": "Converts\u0020a\u0020Doctrine\\DBAL\\Schema\\Table\u0020to\u0020a\u0020Flow\\ETL\\Schema.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_table_schema_to_flow_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\postgresql_insert_options\u0028\u0029",
            "name": "postgresql_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_postgresql_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\mysql_insert_options\u0028\u0029",
            "name": "mysql_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_mysql_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\sqlite_insert_options\u0028\u0029",
            "name": "sqlite_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_sqlite_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\postgresql_update_options\u0028\u0029",
            "name": "postgresql_update_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_postgresql_update_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_asc\u0028\u0029",
            "name": "pagination_key_asc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_desc\u0028\u0029",
            "name": "pagination_key_desc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_set\u0028\u0029",
            "name": "pagination_key_set",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter",
            "name": "LiteralParameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html#enumcase_ASC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html#enumcase_DESC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy",
            "name": "OrderBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#property_column"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#property_order"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages",
            "name": "Pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#method_pages"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A\u0024total",
            "name": "total",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#property_total"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A\u0024pageSize",
            "name": "pageSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#property_pageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key",
            "name": "Key",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003Aasc\u0028\u0029",
            "name": "asc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003Adesc\u0028\u0029",
            "name": "desc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_column"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_order"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet",
            "name": "KeySet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html#property_keys"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html#enumcase_ASC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html#enumcase_DESC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter",
            "name": "Parameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Aasciis\u0028\u0029",
            "name": "asciis",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_asciis"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Aints\u0028\u0029",
            "name": "ints",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_ints"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Astrings\u0028\u0029",
            "name": "strings",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_strings"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet",
            "name": "ParametersSet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html#method_all"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter",
            "name": "QueryParameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003AtoDbalTable\u0028\u0029",
            "name": "toDbalTable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method_toDbalTable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003AtoFlowSchema\u0028\u0029",
            "name": "toFlowSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method_toFlowSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003ADEFAULT_TYPES",
            "name": "DEFAULT_TYPES",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#constant_DEFAULT_TYPES"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table",
            "name": "Table",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#property_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap",
            "name": "TypesMap",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AtoDbalType\u0028\u0029",
            "name": "toDbalType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method_toDbalType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003ADBAL_TYPES",
            "name": "DBAL_TYPES",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#constant_DBAL_TYPES"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AFLOW_TYPES",
            "name": "FLOW_TYPES",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#constant_FLOW_TYPES"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine",
            "name": "Doctrine",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination",
            "name": "Pagination",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine-pagination.html"
        }            ]
);
