Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory",
            "name": "DbalDataFrameFactory",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003AfromConnection\u0028\u0029",
            "name": "fromConnection",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_fromConnection"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_from"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalDataFrameFactory\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalDataFrameFactory.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalEncoder",
            "name": "DbalEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor",
            "name": "DbalKeySetExtractor",
            "summary": "Extractor\u0020implementing\u0020keyset\u0020pagination\u0020for\u0020Doctrine\u0020DBAL\u0020queries.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithKeyAliasSuffix\u0028\u0029",
            "name": "withKeyAliasSuffix",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withKeyAliasSuffix"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "Sets\u0020the\u0020maximum\u0020number\u0020of\u0020rows\u0020to\u0020fetch.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalKeySetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "Sets\u0020the\u0020schema\u0020for\u0020the\u0020extracted\u0020rows.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalKeySetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor",
            "name": "DbalLimitOffsetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003Atable\u0028\u0029",
            "name": "table",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithMaximum\u0028\u0029",
            "name": "withMaximum",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withMaximum"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithOffset\u0028\u0029",
            "name": "withOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLimitOffsetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLimitOffsetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader",
            "name": "DbalLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AfromConnection\u0028\u0029",
            "name": "fromConnection",
            "summary": "Since\u0020Connection\u003A\u003AgetParams\u0028\u0029\u0020is\u0020marked\u0020as\u0020an\u0020internal\u0020method,\u0020please\nuse\u0020this\u0020constructor\u0020with\u0020caution.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_fromConnection"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AwithOperation\u0028\u0029",
            "name": "withOperation",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_withOperation"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AwithOperationOptions\u0028\u0029",
            "name": "withOperationOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_withOperationOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalLoader\u003A\u003AwithTypesMap\u0028\u0029",
            "name": "withTypesMap",
            "summary": "Set\u0020custom\u0020types\u0020map\u0020for\u0020Flow\u0020Type\u0020to\u0020DBAL\u0020Type\u0020conversion.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalLoader.html#method_withTypesMap"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata",
            "name": "DbalMetadata",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AcolumnDefinition\u0028\u0029",
            "name": "columnDefinition",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_columnDefinition"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Acomment\u0028\u0029",
            "name": "comment",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_comment"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Adefault\u0028\u0029",
            "name": "default",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_default"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Afixed\u0028\u0029",
            "name": "fixed",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_fixed"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_index"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AindexUnique\u0028\u0029",
            "name": "indexUnique",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_indexUnique"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_length"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AplatformOptions\u0028\u0029",
            "name": "platformOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_platformOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aprecision\u0028\u0029",
            "name": "precision",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_precision"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AprimaryKey\u0028\u0029",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_primaryKey"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Ascale\u0028\u0029",
            "name": "scale",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_scale"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003Aunsigned\u0028\u0029",
            "name": "unsigned",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#method_unsigned"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACOLUMN_DEFINITION",
            "name": "COLUMN_DEFINITION",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_COLUMN_DEFINITION"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACOMMENT",
            "name": "COMMENT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_COMMENT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ACUSTOM_SCHEMA_OPTIONS",
            "name": "CUSTOM_SCHEMA_OPTIONS",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_CUSTOM_SCHEMA_OPTIONS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ADEFAULT",
            "name": "DEFAULT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_DEFAULT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AFIXED",
            "name": "FIXED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_FIXED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AINDEX",
            "name": "INDEX",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_INDEX"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AINDEX_UNIQUE",
            "name": "INDEX_UNIQUE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_INDEX_UNIQUE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ALENGTH",
            "name": "LENGTH",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_LENGTH"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APLATFORM_OPTIONS",
            "name": "PLATFORM_OPTIONS",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PLATFORM_OPTIONS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APRECISION",
            "name": "PRECISION",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PRECISION"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003APRIMARY_KEY",
            "name": "PRIMARY_KEY",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_PRIMARY_KEY"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ASCALE",
            "name": "SCALE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_SCALE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003ATYPE",
            "name": "TYPE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_TYPE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalMetadata\u003A\u003AUNSIGNED",
            "name": "UNSIGNED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalMetadata.html#enumcase_UNSIGNED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor",
            "name": "DbalQueryExtractor",
            "summary": "batchSize\u0028\u0029\u0020is\u0020a\u0020yield\u0020cap,\u0020not\u0020a\u0020fetch\u0020size\u003A\u0020fetchAllAssociative\u0028\u0029\u0020materialises\u0020the\u0020whole\u0020result\u0020set\u0020per\nparameter\u0020set,\u0020so\u0020lowering\u0020it\u0020cannot\u0020lower\u0020peak\u0020memory.\u0020The\u0020paginating\u0020extractors\u0020default\u0020to\u00201000\u0020because\ntheir\u0020number\u0020IS\u0020a\u0020round\u0020trip.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003Asingle\u0028\u0029",
            "name": "single",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_single"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithParameters\u0028\u0029",
            "name": "withParameters",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withParameters"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalQueryExtractor\u003A\u003AwithTypes\u0028\u0029",
            "name": "withTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalQueryExtractor.html#method_withTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalResultSchema",
            "name": "DbalResultSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalResultSchema.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DbalResultSchema\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "The\u0020one\u0020schema\u0020a\u0020read\u0020has\u003A\u0020extract\u0028\u0029\u0020asks\u0020for\u0020it\u0020before\u0020the\u0020first\u0020row\u0020and\u0020never\u0020falls\u0020back\u0020to\nper\u002Dbatch\u0020typing,\u0020so\u0020a\u0020query\u0020that\u0020cannot\u0020be\u0020described\u0020does\u0020not\u0020run.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DbalResultSchema.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DescribeQuery",
            "name": "DescribeQuery",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DescribeQuery.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\DescribeQuery\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-DescribeQuery.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_dataframe_factory\u0028\u0029",
            "name": "dbal_dataframe_factory",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_dataframe_factory"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_limit_offset\u0028\u0029",
            "name": "from_dbal_limit_offset",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_limit_offset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_limit_offset_qb\u0028\u0029",
            "name": "from_dbal_limit_offset_qb",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_limit_offset_qb"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_key_set_qb\u0028\u0029",
            "name": "from_dbal_key_set_qb",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_key_set_qb"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_queries\u0028\u0029",
            "name": "from_dbal_queries",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_queries"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_from_queries\u0028\u0029",
            "name": "dbal_from_queries",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_from_queries"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\from_dbal_query\u0028\u0029",
            "name": "from_dbal_query",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_from_dbal_query"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\dbal_from_query\u0028\u0029",
            "name": "dbal_from_query",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_dbal_from_query"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_insert\u0028\u0029",
            "name": "to_dbal_table_insert",
            "summary": "Insert\u0020new\u0020rows\u0020into\u0020a\u0020database\u0020table.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_insert"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_update\u0028\u0029",
            "name": "to_dbal_table_update",
            "summary": "Update\u0020existing\u0020rows\u0020in\u0020database.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_table_delete\u0028\u0029",
            "name": "to_dbal_table_delete",
            "summary": "Delete\u0020rows\u0020from\u0020database\u0020table\u0020based\u0020on\u0020the\u0020provided\u0020data.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_table_delete"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_schema_table\u0028\u0029",
            "name": "to_dbal_schema_table",
            "summary": "Converts\u0020a\u0020Flow\\ETL\\Schema\u0020to\u0020a\u0020Doctrine\\DBAL\\Schema\\Table.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_schema_table"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\table_schema_to_flow_schema\u0028\u0029",
            "name": "table_schema_to_flow_schema",
            "summary": "Converts\u0020a\u0020Doctrine\\DBAL\\Schema\\Table\u0020to\u0020a\u0020Flow\\ETL\\Schema.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_table_schema_to_flow_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\postgresql_insert_options\u0028\u0029",
            "name": "postgresql_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_postgresql_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\mysql_insert_options\u0028\u0029",
            "name": "mysql_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_mysql_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\sqlite_insert_options\u0028\u0029",
            "name": "sqlite_insert_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_sqlite_insert_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\postgresql_update_options\u0028\u0029",
            "name": "postgresql_update_options",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_postgresql_update_options"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\to_dbal_transaction\u0028\u0029",
            "name": "to_dbal_transaction",
            "summary": "Execute\u0020multiple\u0020loaders\u0020within\u0020database\u0020transactions.",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_to_dbal_transaction"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_asc\u0028\u0029",
            "name": "pagination_key_asc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_desc\u0028\u0029",
            "name": "pagination_key_desc",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\pagination_key_set\u0028\u0029",
            "name": "pagination_key_set",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html#function_pagination_key_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter",
            "name": "LiteralParameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\LiteralParameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-LiteralParameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliPlaceholders",
            "name": "MysqliPlaceholders",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliPlaceholders.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliPlaceholders\u003A\u003Aplaceholder\u0028\u0029",
            "name": "placeholder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliPlaceholders.html#method_placeholder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliPlaceholders\u003A\u003AusesBackslashEscapes\u0028\u0029",
            "name": "usesBackslashEscapes",
            "summary": "Whether\u0020the\u0020driver\u0020reads\u0020a\u0020backslash\u0020inside\u0020a\u0020string\u0020literal\u0020as\u0020an\u0020escape,\u0020which\u0020decides\u0020how\nDBAL\u0027s\u0020parser\u0020tokenises\u0020string\u0020literals.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliPlaceholders.html#method_usesBackslashEscapes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliResultColumns",
            "name": "MysqliResultColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliResultColumns.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliResultColumns\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliResultColumns.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliTypesMap",
            "name": "MysqliTypesMap",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliTypesMap.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\MysqliTypesMap\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "mysqli_result\u003A\u003Afetch_fields\u0028\u0029\u0020reports\u0020an\u0020integer\u0020type\u0020constant\u0020per\u0020column.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-MysqliTypesMap.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\NativePlaceholders",
            "name": "NativePlaceholders",
            "summary": "Rewrites\u0020DBAL\u0027s\u0020\u003Aname\u0020\/\u0020\u003F\u0020placeholders\u0020into\u0020a\u0020driver\u002Dnative\u0020dialect,\u0020using\u0020DBAL\u0027s\u0020own\u0020SQL\u0020parser.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-NativePlaceholders.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\NativePlaceholders\u003A\u003AtoMysqli\u0028\u0029",
            "name": "toMysqli",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-NativePlaceholders.html#method_toMysqli"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\NativePlaceholders\u003A\u003AtoPostgreSql\u0028\u0029",
            "name": "toPostgreSql",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-NativePlaceholders.html#method_toPostgreSql"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\NativeTypes",
            "name": "NativeTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-NativeTypes.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\NativeTypes\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-NativeTypes.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html#enumcase_ASC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Order\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Order.html#enumcase_DESC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy",
            "name": "OrderBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#property_column"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\OrderBy\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-OrderBy.html#property_order"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages",
            "name": "Pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#method_pages"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A\u0024total",
            "name": "total",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#property_total"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pages\u003A\u003A\u0024pageSize",
            "name": "pageSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pages.html#property_pageSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key",
            "name": "Key",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003Aasc\u0028\u0029",
            "name": "asc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method_asc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003Adesc\u0028\u0029",
            "name": "desc",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#method_desc"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024column",
            "name": "column",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_column"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024order",
            "name": "order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_order"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Key\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Key.html#property_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet",
            "name": "KeySet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\KeySet\u003A\u003A\u0024keys",
            "name": "keys",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-KeySet.html#property_keys"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order\u003A\u003AASC",
            "name": "ASC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html#enumcase_ASC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination\\Order\u003A\u003ADESC",
            "name": "DESC",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Pagination-Order.html#enumcase_DESC"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter",
            "name": "Parameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Aasciis\u0028\u0029",
            "name": "asciis",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_asciis"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Aints\u0028\u0029",
            "name": "ints",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_ints"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Astrings\u0028\u0029",
            "name": "strings",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_strings"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Parameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Parameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet",
            "name": "ParametersSet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ParametersSet\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ParametersSet.html#method_all"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PdoSqliteColumnNames",
            "name": "PdoSqliteColumnNames",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PdoSqliteColumnNames.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PdoSqliteColumnNames\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PdoSqliteColumnNames.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PgSqlResultColumns",
            "name": "PgSqlResultColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PgSqlResultColumns.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PgSqlResultColumns\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PgSqlResultColumns.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PgSqlTypesMap",
            "name": "PgSqlTypesMap",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PgSqlTypesMap.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PgSqlTypesMap\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PgSqlTypesMap.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PlaceholderDialect",
            "name": "PlaceholderDialect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PlaceholderDialect.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PlaceholderDialect\u003A\u003Aplaceholder\u0028\u0029",
            "name": "placeholder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PlaceholderDialect.html#method_placeholder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PlaceholderDialect\u003A\u003AusesBackslashEscapes\u0028\u0029",
            "name": "usesBackslashEscapes",
            "summary": "Whether\u0020the\u0020driver\u0020reads\u0020a\u0020backslash\u0020inside\u0020a\u0020string\u0020literal\u0020as\u0020an\u0020escape,\u0020which\u0020decides\u0020how\nDBAL\u0027s\u0020parser\u0020tokenises\u0020string\u0020literals.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PlaceholderDialect.html#method_usesBackslashEscapes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PostgreSqlPlaceholders",
            "name": "PostgreSqlPlaceholders",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PostgreSqlPlaceholders.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PostgreSqlPlaceholders\u003A\u003Aplaceholder\u0028\u0029",
            "name": "placeholder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PostgreSqlPlaceholders.html#method_placeholder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\PostgreSqlPlaceholders\u003A\u003AusesBackslashEscapes\u0028\u0029",
            "name": "usesBackslashEscapes",
            "summary": "Whether\u0020the\u0020driver\u0020reads\u0020a\u0020backslash\u0020inside\u0020a\u0020string\u0020literal\u0020as\u0020an\u0020escape,\u0020which\u0020decides\u0020how\nDBAL\u0027s\u0020parser\u0020tokenises\u0020string\u0020literals.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-PostgreSqlPlaceholders.html#method_usesBackslashEscapes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter",
            "name": "QueryParameter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003AqueryParamName\u0028\u0029",
            "name": "queryParamName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_queryParamName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003AtoQueryParam\u0028\u0029",
            "name": "toQueryParam",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_toQueryParam"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\QueryParameter\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-QueryParameter.html#method_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ResultColumn",
            "name": "ResultColumn",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ResultColumn.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ResultColumn\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ResultColumn.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ResultColumn\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ResultColumn.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\ResultColumn\u003A\u003A\u0024native",
            "name": "native",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-ResultColumn.html#property_native"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\RewrittenSql",
            "name": "RewrittenSql",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-RewrittenSql.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\RewrittenSql\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-RewrittenSql.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\RewrittenSql\u003A\u003A\u0024sql",
            "name": "sql",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-RewrittenSql.html#property_sql"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\RewrittenSql\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-RewrittenSql.html#property_parameters"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003AtoDbalTable\u0028\u0029",
            "name": "toDbalTable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method_toDbalTable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SchemaConverter\u003A\u003AtoFlowSchema\u0028\u0029",
            "name": "toFlowSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SchemaConverter.html#method_toFlowSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Sqlite3ColumnNames",
            "name": "Sqlite3ColumnNames",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Sqlite3ColumnNames.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Sqlite3ColumnNames\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Sqlite3ColumnNames.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SqliteResultSchema",
            "name": "SqliteResultSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SqliteResultSchema.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SqliteResultSchema\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SqliteResultSchema.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SqliteTypes",
            "name": "SqliteTypes",
            "summary": "SQLite\u0020has\u0020no\u0020per\u002Dcolumn\u0020type\u003A\u0020SQLite3Result\u003A\u003AcolumnType\u0028\u0029\u0020describes\u0020the\u0020value,\u0020not\u0020the\u0020column,\nand\u0020sqlite3_column_decltype\u0028\u0029\u0020is\u0020not\u0020bound\u0020in\u0020PHP.\u0020An\u0020all\u002Dstring\u0020schema\u0020is\u0020a\u0020true\u0020statement\u0020about\nit\u0020rather\u0020than\u0020a\u0020floor,\u0020and\u0020the\u0020read\u0020casts\u0020values\u0020to\u0020match.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SqliteTypes.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\SqliteTypes\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-SqliteTypes.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table",
            "name": "Table",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Table\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-Table.html#property_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader",
            "name": "TransactionalDbalLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003AfromConnection\u0028\u0029",
            "name": "fromConnection",
            "summary": "Since\u0020Connection\u003A\u003AgetParams\u0028\u0029\u0020is\u0020marked\u0020as\u0020an\u0020internal\u0020method,\u0020please\nuse\u0020this\u0020constructor\u0020with\u0020caution.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method_fromConnection"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "Rows\u0020a\u0020wrapped\u0020Transformation\u0020buffered\u0020\u0028blocking\u0020operations\u0020\u002D\u0020sortBy,\u0020aggregate,\u0020groupBy\u002D\u003Eaggregate,\npivot,\u0020window\u0020functions,\u0020collect,\u0020join\u0029\u0020are\u0020delivered\u0020during\u0020the\u0020forwarded\u0020closure\u0028\u0029\u0020drain,\u0020so\u0020delivery\nhere\u0020must\u0020be\u0020transactional\u0020too\u003A\u0020one\u0020transaction\u0020over\u0020everything\u0020the\u0020drain\u0020flushes,\u0020rolled\u0020back\u0020when\u0020it\u0020fails.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003Aloaders\u0028\u0029",
            "name": "loaders",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method_loaders"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TransactionalDbalLoader\u003A\u003AwithIsolationLevel\u0028\u0029",
            "name": "withIsolationLevel",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TransactionalDbalLoader.html#method_withIsolationLevel"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypedColumns",
            "name": "TypedColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypedColumns.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypedColumns\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "Every\u0020column\u0020is\u0020nullable\u003A\u0020result\u0020metadata\u0020cannot\u0020prove\u0020NOT\u0020NULL,\u0020and\u0020an\u0020outer\u0020join\u0020or\u0020an\nexpression\u0020can\u0020always\u0020produce\u0020null.\u0020Duplicate\u0020output\u0020names\u0020collapse\u0020last\u002Dwins,\u0020matching\u0020what\nfetchAssociative\u0028\u0029\u0020does\u0020to\u0020the\u0020row\u0020itself.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypedColumns.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap",
            "name": "TypesMap",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AflowSchemaTypes\u0028\u0029",
            "name": "flowSchemaTypes",
            "summary": "Build\u0020DBAL\u0020types\u0020array\u0020from\u0020a\u0020schema\u0027s\u0020definitions.",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method_flowSchemaTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AtoDbalType\u0028\u0029",
            "name": "toDbalType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method_toDbalType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AtoFlowType\u0028\u0029",
            "name": "toFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#method_toFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003ADBAL_TYPES",
            "name": "DBAL_TYPES",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#constant_DBAL_TYPES"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\TypesMap\u003A\u003AFLOW_TYPES",
            "name": "FLOW_TYPES",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Doctrine-TypesMap.html#constant_FLOW_TYPES"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine",
            "name": "Doctrine",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Doctrine\\Pagination",
            "name": "Pagination",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-doctrine-pagination.html"
        }            ]
);
