Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\CLI\\Arguments\\FilePathArgument",
            "name": "FilePathArgument",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-FilePathArgument.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\FilePathArgument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-FilePathArgument.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\FilePathArgument\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-FilePathArgument.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\FilePathArgument\u003A\u003AgetExisting\u0028\u0029",
            "name": "getExisting",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-FilePathArgument.html#method_getExisting"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\FilePathArgument\u003A\u003AgetNotExisting\u0028\u0029",
            "name": "getNotExisting",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-FilePathArgument.html#method_getNotExisting"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument",
            "name": "TypedArgument",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument\u003A\u003AasInt\u0028\u0029",
            "name": "asInt",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html#method_asInt"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument\u003A\u003AasIntNullable\u0028\u0029",
            "name": "asIntNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html#method_asIntNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument\u003A\u003AasString\u0028\u0029",
            "name": "asString",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html#method_asString"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments\\TypedArgument\u003A\u003AasStringNullable\u0028\u0029",
            "name": "asStringNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Arguments-TypedArgument.html#method_asStringNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileAnalyzeCommand",
            "name": "FileAnalyzeCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileAnalyzeCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileAnalyzeCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileAnalyzeCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileConvertCommand",
            "name": "FileConvertCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileConvertCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileConvertCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileConvertCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileReadCommand",
            "name": "FileReadCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileReadCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileReadCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileReadCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileRowsCountCommand",
            "name": "FileRowsCountCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileRowsCountCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileRowsCountCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileRowsCountCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileSchemaCommand",
            "name": "FileSchemaCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileSchemaCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\FileSchemaCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-FileSchemaCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\PipelineRunCommand",
            "name": "PipelineRunCommand",
            "summary": "",
            "url": "classes/Flow-CLI-Command-PipelineRunCommand.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\PipelineRunCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-CLI-Command-PipelineRunCommand.html#method_configure"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\PipelineRunCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/Flow-CLI-Command-PipelineRunCommand.html#method_execute"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits\\ConfigOptions",
            "name": "ConfigOptions",
            "summary": "",
            "url": "classes/Flow-CLI-Command-Traits-ConfigOptions.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits\\CSVOptions",
            "name": "CSVOptions",
            "summary": "",
            "url": "classes/Flow-CLI-Command-Traits-CSVOptions.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits\\JSONOptions",
            "name": "JSONOptions",
            "summary": "",
            "url": "classes/Flow-CLI-Command-Traits-JSONOptions.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits\\ParquetOptions",
            "name": "ParquetOptions",
            "summary": "",
            "url": "classes/Flow-CLI-Command-Traits-ParquetOptions.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits\\XMLOptions",
            "name": "XMLOptions",
            "summary": "",
            "url": "classes/Flow-CLI-Command-Traits-XMLOptions.html"
        },                {
            "fqsen": "\\Flow\\CLI\\option_bool\u0028\u0029",
            "name": "option_bool",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_bool"
        },                {
            "fqsen": "\\Flow\\CLI\\option_bool_nullable\u0028\u0029",
            "name": "option_bool_nullable",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_bool_nullable"
        },                {
            "fqsen": "\\Flow\\CLI\\option_string\u0028\u0029",
            "name": "option_string",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_string"
        },                {
            "fqsen": "\\Flow\\CLI\\option_string_nullable\u0028\u0029",
            "name": "option_string_nullable",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_string_nullable"
        },                {
            "fqsen": "\\Flow\\CLI\\option_int\u0028\u0029",
            "name": "option_int",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_int"
        },                {
            "fqsen": "\\Flow\\CLI\\option_int_nullable\u0028\u0029",
            "name": "option_int_nullable",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_int_nullable"
        },                {
            "fqsen": "\\Flow\\CLI\\option_list_of_strings\u0028\u0029",
            "name": "option_list_of_strings",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_list_of_strings"
        },                {
            "fqsen": "\\Flow\\CLI\\option_list_of_strings_nullable\u0028\u0029",
            "name": "option_list_of_strings_nullable",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_option_list_of_strings_nullable"
        },                {
            "fqsen": "\\Flow\\CLI\\argument_string\u0028\u0029",
            "name": "argument_string",
            "summary": "",
            "url": "namespaces/flow-cli.html#function_argument_string"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVExtractorFactory",
            "name": "CSVExtractorFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVExtractorFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVExtractorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVExtractorFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVExtractorFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVExtractorFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVLoaderFactory",
            "name": "CSVLoaderFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVLoaderFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVLoaderFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVLoaderFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\CSVLoaderFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-CSVLoaderFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ExtractorFactory",
            "name": "ExtractorFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ExtractorFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ExtractorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ExtractorFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ExtractorFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ExtractorFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonExtractorFactory",
            "name": "JsonExtractorFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonExtractorFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonExtractorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonExtractorFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonExtractorFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonExtractorFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonLoaderFactory",
            "name": "JsonLoaderFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonLoaderFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonLoaderFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonLoaderFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\JsonLoaderFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-JsonLoaderFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\LoaderFactory",
            "name": "LoaderFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-LoaderFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\LoaderFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-LoaderFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\LoaderFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-LoaderFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetExtractorFactory",
            "name": "ParquetExtractorFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetExtractorFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetExtractorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetExtractorFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetExtractorFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetExtractorFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetLoaderFactory",
            "name": "ParquetLoaderFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetLoaderFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetLoaderFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetLoaderFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\ParquetLoaderFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-ParquetLoaderFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLExtractorFactory",
            "name": "XMLExtractorFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLExtractorFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLExtractorFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLExtractorFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLExtractorFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLExtractorFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLLoaderFactory",
            "name": "XMLLoaderFactory",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLLoaderFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLLoaderFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLLoaderFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory\\XMLLoaderFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Factory-XMLLoaderFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\ConfigOption",
            "name": "ConfigOption",
            "summary": "",
            "url": "classes/Flow-CLI-Options-ConfigOption.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\ConfigOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Options-ConfigOption.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\ConfigOption\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Options-ConfigOption.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat",
            "name": "FileFormat",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#method_isValid"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003ACSV",
            "name": "CSV",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#enumcase_CSV"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#enumcase_JSON"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003APARQUET",
            "name": "PARQUET",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#enumcase_PARQUET"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#enumcase_TEXT"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormat\u003A\u003AXML",
            "name": "XML",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormat.html#enumcase_XML"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormatOption",
            "name": "FileFormatOption",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormatOption.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormatOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormatOption.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\FileFormatOption\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-CLI-Options-FileFormatOption.html#method_get"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption",
            "name": "TypedOption",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasBool\u0028\u0029",
            "name": "asBool",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asBool"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasBoolNullable\u0028\u0029",
            "name": "asBoolNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asBoolNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasInt\u0028\u0029",
            "name": "asInt",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asInt"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasIntNullable\u0028\u0029",
            "name": "asIntNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asIntNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasListOfStrings\u0028\u0029",
            "name": "asListOfStrings",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asListOfStrings"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasListOfStringsNullable\u0028\u0029",
            "name": "asListOfStringsNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asListOfStringsNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasString\u0028\u0029",
            "name": "asString",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asString"
        },                {
            "fqsen": "\\Flow\\CLI\\Options\\TypedOption\u003A\u003AasStringNullable\u0028\u0029",
            "name": "asStringNullable",
            "summary": "",
            "url": "classes/Flow-CLI-Options-TypedOption.html#method_asStringNullable"
        },                {
            "fqsen": "\\Flow\\CLI\\PipelineFactory",
            "name": "PipelineFactory",
            "summary": "",
            "url": "classes/Flow-CLI-PipelineFactory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\PipelineFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-PipelineFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\PipelineFactory\u003A\u003AfromJson\u0028\u0029",
            "name": "fromJson",
            "summary": "",
            "url": "classes/Flow-CLI-PipelineFactory.html#method_fromJson"
        },                {
            "fqsen": "\\Flow\\CLI\\PipelineFactory\u003A\u003AfromPHP\u0028\u0029",
            "name": "fromPHP",
            "summary": "",
            "url": "classes/Flow-CLI-PipelineFactory.html#method_fromPHP"
        },                {
            "fqsen": "\\Flow\\CLI\\Style\\FlowStyle",
            "name": "FlowStyle",
            "summary": "",
            "url": "classes/Flow-CLI-Style-FlowStyle.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Style\\FlowStyle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-CLI-Style-FlowStyle.html#method___construct"
        },                {
            "fqsen": "\\Flow\\CLI\\Style\\FlowStyle\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Flow-CLI-Style-FlowStyle.html#method_clear"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Arguments",
            "name": "Arguments",
            "summary": "",
            "url": "namespaces/flow-cli-arguments.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/flow-cli-command.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Command\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/flow-cli-command-traits.html"
        },                {
            "fqsen": "\\Flow\\CLI",
            "name": "CLI",
            "summary": "",
            "url": "namespaces/flow-cli.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Factory",
            "name": "Factory",
            "summary": "",
            "url": "namespaces/flow-cli-factory.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Options",
            "name": "Options",
            "summary": "",
            "url": "namespaces/flow-cli-options.html"
        },                {
            "fqsen": "\\Flow\\CLI\\Style",
            "name": "Style",
            "summary": "",
            "url": "namespaces/flow-cli-style.html"
        }            ]
);
