Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\from_json\u0028\u0029",
            "name": "from_json",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-json.html#function_from_json"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\from_json_lines\u0028\u0029",
            "name": "from_json_lines",
            "summary": "Used\u0020to\u0020read\u0020from\u0020a\u0020JSON\u0020lines\u0020https\u003A\/\/jsonlines.org\/\u0020formatted\u0020file.",
            "url": "namespaces/flow-etl-adapter-json.html#function_from_json_lines"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\to_json\u0028\u0029",
            "name": "to_json",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-json.html#function_to_json"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\to_json_lines\u0028\u0029",
            "name": "to_json_lines",
            "summary": "Used\u0020to\u0020write\u0020to\u0020a\u0020JSON\u0020lines\u0020https\u003A\/\/jsonlines.org\/\u0020formatted\u0020file.",
            "url": "namespaces/flow-etl-adapter-json.html#function_to_json_lines"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader",
            "name": "JsonLinesLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003AwithFlags\u0028\u0029",
            "name": "withFlags",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_withFlags"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLinesLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLinesLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader",
            "name": "JsonLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003AwithFlags\u0028\u0029",
            "name": "withFlags",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_withFlags"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003AwithRowsInNewLines\u0028\u0029",
            "name": "withRowsInNewLines",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_withRowsInNewLines"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JsonLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JsonLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor",
            "name": "JsonExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor\u003A\u003AwithPointer\u0028\u0029",
            "name": "withPointer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html#method_withPointer"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor",
            "name": "JsonLinesExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor\u003A\u003AwithPointer\u0028\u0029",
            "name": "withPointer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html#method_withPointer"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine\\JsonLinesExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-JSONMachine-JsonLinesExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer\\EntryNormalizer",
            "name": "EntryNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer-EntryNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer\\EntryNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer-EntryNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer\\EntryNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer-EntryNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-JSON-RowsNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON",
            "name": "JSON",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-json.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\JSONMachine",
            "name": "JSONMachine",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-json-jsonmachine.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\JSON\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-json-rowsnormalizer.html"
        }            ]
);
