Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Filesystem\\DestinationStream",
            "name": "DestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-DestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-DestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-DestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\protocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "namespaces/flow-filesystem-dsl.html#function_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\partition\u0028\u0029",
            "name": "partition",
            "summary": "",
            "url": "namespaces/flow-filesystem-dsl.html#function_partition"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\partitions\u0028\u0029",
            "name": "partitions",
            "summary": "",
            "url": "namespaces/flow-filesystem-dsl.html#function_partitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\path\u0028\u0029",
            "name": "path",
            "summary": "Path\u0020supports\u0020glob\u0020patterns.",
            "url": "namespaces/flow-filesystem-dsl.html#function_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\path_stdout\u0028\u0029",
            "name": "path_stdout",
            "summary": "Create\u0020a\u0020path\u0020to\u0020php\u0020stdout\u0020stream.",
            "url": "namespaces/flow-filesystem-dsl.html#function_path_stdout"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\path_memory\u0028\u0029",
            "name": "path_memory",
            "summary": "Create\u0020a\u0020path\u0020to\u0020php\u0020memory\u0020stream.",
            "url": "namespaces/flow-filesystem-dsl.html#function_path_memory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\path_real\u0028\u0029",
            "name": "path_real",
            "summary": "Resolve\u0020real\u0020path\u0020from\u0020given\u0020path.",
            "url": "namespaces/flow-filesystem-dsl.html#function_path_real"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\native_local_filesystem\u0028\u0029",
            "name": "native_local_filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem-dsl.html#function_native_local_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\stdout_filesystem\u0028\u0029",
            "name": "stdout_filesystem",
            "summary": "Write\u002Donly\u0020filesystem\u0020useful\u0020when\u0020we\u0020just\u0020want\u0020to\u0020write\u0020the\u0020output\u0020to\u0020stdout.",
            "url": "namespaces/flow-filesystem-dsl.html#function_stdout_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\memory_filesystem\u0028\u0029",
            "name": "memory_filesystem",
            "summary": "Create\u0020a\u0020new\u0020memory\u0020filesystem\u0020and\u0020writes\u0020data\u0020to\u0020it\u0020in\u0020memory.",
            "url": "namespaces/flow-filesystem-dsl.html#function_memory_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL\\fstab\u0028\u0029",
            "name": "fstab",
            "summary": "Create\u0020a\u0020new\u0020filesystem\u0020table\u0020with\u0020given\u0020filesystems.",
            "url": "namespaces/flow-filesystem-dsl.html#function_fstab"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-Exception.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\InvalidSchemeException",
            "name": "InvalidSchemeException",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-InvalidSchemeException.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\InvalidSchemeException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-InvalidSchemeException.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\MissingOptionException",
            "name": "MissingOptionException",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-MissingOptionException.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "",
            "url": "classes/Flow-Filesystem-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FileStatus",
            "name": "FileStatus",
            "summary": "",
            "url": "classes/Flow-Filesystem-FileStatus.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FileStatus\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-FileStatus.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FileStatus\u003A\u003AisDirectory\u0028\u0029",
            "name": "isDirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-FileStatus.html#method_isDirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FileStatus\u003A\u003AisFile\u0028\u0029",
            "name": "isFile",
            "summary": "",
            "url": "classes/Flow-Filesystem-FileStatus.html#method_isFile"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FileStatus\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-FileStatus.html#property_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Filesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "Open\u0020destination\u0020stream\u0020for\u0020writing,\u0020if\u0020file\u0020already\u0020exists\u0020it\u0020will\u0020be\u0020overwritten.",
            "url": "classes/Flow-Filesystem-Filesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FilesystemTable",
            "name": "FilesystemTable",
            "summary": "",
            "url": "classes/Flow-Filesystem-FilesystemTable.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FilesystemTable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-FilesystemTable.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FilesystemTable\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-Filesystem-FilesystemTable.html#method_for"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FilesystemTable\u003A\u003Amount\u0028\u0029",
            "name": "mount",
            "summary": "",
            "url": "classes/Flow-Filesystem-FilesystemTable.html#method_mount"
        },                {
            "fqsen": "\\Flow\\Filesystem\\FilesystemTable\u003A\u003Aunmount\u0028\u0029",
            "name": "unmount",
            "summary": "",
            "url": "classes/Flow-Filesystem-FilesystemTable.html#method_unmount"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory",
            "name": "Memory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method___destruct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method_for"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method_has"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\Memory\u003A\u003Apaths\u0028\u0029",
            "name": "paths",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-Memory.html#method_paths"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream",
            "name": "MemoryStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method___destruct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "We\u0020are\u0020not\u0020closing\u0020memory\u0020streams,\u0020in\u0020order\u0020to\u0020cleanup\u0020memory\u0020use\u0020rm\u0020on\u0020Memory\u0020Filesystem.",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory\\MemoryStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-Memory-MemoryStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem",
            "name": "MemoryFilesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\MemoryFilesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "Open\u0020destination\u0020stream\u0020for\u0020writing,\u0020if\u0020file\u0020already\u0020exists\u0020it\u0020will\u0020be\u0020overwritten.",
            "url": "classes/Flow-Filesystem-Local-MemoryFilesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem",
            "name": "NativeLocalFilesystem",
            "summary": "This\u0020implementation\u0020is\u0020based\u0020on\u0020the\u0020native\u0020PHP\u0020filesystem\u0020functions\u0020documented\u0020here\u003A\u0020https\u003A\/\/www.php.net\/manual\/en\/book.filesystem.php\nAdditionally,\u0020in\u0020order\u0020to\u0020support\u0020glob\u0020pattern\u0020\u0060\\\/\u002A\u002A\\\/\u0060\u0020for\u0020matching\u0020zero\u0020or\u0020more\u0020directories\u0020it\u0027s\u0020using\u0020webmozart\/glob\u0020library.",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\NativeLocalFilesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "Open\u0020destination\u0020stream\u0020for\u0020writing,\u0020if\u0020file\u0020already\u0020exists\u0020it\u0020will\u0020be\u0020overwritten.",
            "url": "classes/Flow-Filesystem-Local-NativeLocalFilesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream",
            "name": "StdOutDestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut\\StdOutDestinationStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOut-StdOutDestinationStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem",
            "name": "StdOutFilesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOutFilesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "Open\u0020destination\u0020stream\u0020for\u0020writing,\u0020if\u0020file\u0020already\u0020exists\u0020it\u0020will\u0020be\u0020overwritten.",
            "url": "classes/Flow-Filesystem-Local-StdOutFilesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StreamFilter\\Intercept",
            "name": "Intercept",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StreamFilter-Intercept.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StreamFilter\\Intercept\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StreamFilter-Intercept.html#method_filter"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StreamFilter\\Intercept\u003A\u003A\u0024buffer",
            "name": "buffer",
            "summary": "",
            "url": "classes/Flow-Filesystem-Local-StreamFilter-Intercept.html#property_buffer"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition",
            "name": "Partition",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method_fromArray"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003AfromUri\u0028\u0029",
            "name": "fromUri",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method_fromUri"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003AvalueFromRow\u0028\u0029",
            "name": "valueFromRow",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method_valueFromRow"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003Aid\u0028\u0029",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method_id"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003Areference\u0028\u0029",
            "name": "reference",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#method_reference"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#property_name"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partition\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partition.html#property_value"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions",
            "name": "Partitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_count"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_get"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_getIterator"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_has"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003Aid\u0028\u0029",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_id"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_offsetExists"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_offsetGet"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_offsetSet"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_offsetUnset"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Partitions\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Flow-Filesystem-Partitions.html#method_toArray"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\Filters",
            "name": "Filters",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-Filters.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\Filters\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-Filters.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\Filters\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-Filters.html#method_accept"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\Filters\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-Filters.html#method_add"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\KeepAll",
            "name": "KeepAll",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-KeepAll.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\KeepAll\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-KeepAll.html#method_accept"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\OnlyFiles",
            "name": "OnlyFiles",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-OnlyFiles.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\\OnlyFiles\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter-OnlyFiles.html#method_accept"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter",
            "name": "Filter",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter\u003A\u003Aaccept\u0028\u0029",
            "name": "accept",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Filter.html#method_accept"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options\u003A\u003AassertHas\u0028\u0029",
            "name": "assertHas",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html#method_assertHas"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options\u003A\u003AgetAsString\u0028\u0029",
            "name": "getAsString",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html#method_getAsString"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html#method_has"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Options\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-Options.html#method_toArray"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath",
            "name": "UnixPath",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Arealpath\u0028\u0029",
            "name": "realpath",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_realpath"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AaddPartitions\u0028\u0029",
            "name": "addPartitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_addPartitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Abasename\u0028\u0029",
            "name": "basename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_basename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AbasenamePrefix\u0028\u0029",
            "name": "basenamePrefix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_basenamePrefix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AendsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_endsWith"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Aextension\u0028\u0029",
            "name": "extension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_extension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Afilename\u0028\u0029",
            "name": "filename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_filename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AisEqual\u0028\u0029",
            "name": "isEqual",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_isEqual"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AisPattern\u0028\u0029",
            "name": "isPattern",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_isPattern"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_matches"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Aoptions\u0028\u0029",
            "name": "options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_options"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AparentDirectory\u0028\u0029",
            "name": "parentDirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_parentDirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Apartitions\u0028\u0029",
            "name": "partitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_partitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003ApartitionsPaths\u0028\u0029",
            "name": "partitionsPaths",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_partitionsPaths"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Arandomize\u0028\u0029",
            "name": "randomize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_randomize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003ArootDirectoryName\u0028\u0029",
            "name": "rootDirectoryName",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_rootDirectoryName"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AsetExtension\u0028\u0029",
            "name": "setExtension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_setExtension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AskipDirectories\u0028\u0029",
            "name": "skipDirectories",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_skipDirectories"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003AstaticPart\u0028\u0029",
            "name": "staticPart",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_staticPart"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Asuffix\u0028\u0029",
            "name": "suffix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_suffix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\UnixPath\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-UnixPath.html#method_uri"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath",
            "name": "WindowsPath",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Arealpath\u0028\u0029",
            "name": "realpath",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_realpath"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AaddPartitions\u0028\u0029",
            "name": "addPartitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_addPartitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Abasename\u0028\u0029",
            "name": "basename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_basename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AbasenamePrefix\u0028\u0029",
            "name": "basenamePrefix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_basenamePrefix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AendsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_endsWith"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Aextension\u0028\u0029",
            "name": "extension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_extension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Afilename\u0028\u0029",
            "name": "filename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_filename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AisEqual\u0028\u0029",
            "name": "isEqual",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_isEqual"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AisPattern\u0028\u0029",
            "name": "isPattern",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_isPattern"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_matches"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Aoptions\u0028\u0029",
            "name": "options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_options"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AparentDirectory\u0028\u0029",
            "name": "parentDirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_parentDirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Apartitions\u0028\u0029",
            "name": "partitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_partitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003ApartitionsPaths\u0028\u0029",
            "name": "partitionsPaths",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_partitionsPaths"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Arandomize\u0028\u0029",
            "name": "randomize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_randomize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003ArootDirectoryName\u0028\u0029",
            "name": "rootDirectoryName",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_rootDirectoryName"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AsetExtension\u0028\u0029",
            "name": "setExtension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_setExtension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AskipDirectories\u0028\u0029",
            "name": "skipDirectories",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_skipDirectories"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003AstaticPart\u0028\u0029",
            "name": "staticPart",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_staticPart"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Asuffix\u0028\u0029",
            "name": "suffix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_suffix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\WindowsPath\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path-WindowsPath.html#method_uri"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path",
            "name": "Path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Arealpath\u0028\u0029",
            "name": "realpath",
            "summary": "Turn\u0020relative\u0020path\u0020into\u0020absolute\u0020paths\u0020even\u0020when\u0020path\u0020does\u0020not\u0020exists\u0020or\u0020it\u0027s\u0020glob\u0020pattern.",
            "url": "classes/Flow-Filesystem-Path.html#method_realpath"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AaddPartitions\u0028\u0029",
            "name": "addPartitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_addPartitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Abasename\u0028\u0029",
            "name": "basename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_basename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AbasenamePrefix\u0028\u0029",
            "name": "basenamePrefix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_basenamePrefix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Acontext\u0028\u0029",
            "name": "context",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_context"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AendsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_endsWith"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Aextension\u0028\u0029",
            "name": "extension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_extension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Afilename\u0028\u0029",
            "name": "filename",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_filename"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AisEqual\u0028\u0029",
            "name": "isEqual",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_isEqual"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AisLocal\u0028\u0029",
            "name": "isLocal",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_isLocal"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AisPattern\u0028\u0029",
            "name": "isPattern",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_isPattern"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_matches"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Aoptions\u0028\u0029",
            "name": "options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_options"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AparentDirectory\u0028\u0029",
            "name": "parentDirectory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_parentDirectory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Apartitions\u0028\u0029",
            "name": "partitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_partitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003ApartitionsPaths\u0028\u0029",
            "name": "partitionsPaths",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_partitionsPaths"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "Difference\u0020between\u0020Path\u003A\u003Auri\u0020and\u0020Path\u003A\u003Apath\u0020is\u0020that\u0020Path\u003A\u003Auri\u0020returns\u0020path\u0020with\u0020scheme\u0020and\u0020Path\u003A\u003Apath\u0020returns\u0020path\u0020without\u0020scheme.",
            "url": "classes/Flow-Filesystem-Path.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Arandomize\u0028\u0029",
            "name": "randomize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_randomize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003ArootDirectoryName\u0028\u0029",
            "name": "rootDirectoryName",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_rootDirectoryName"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AsetExtension\u0028\u0029",
            "name": "setExtension",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_setExtension"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AskipDirectories\u0028\u0029",
            "name": "skipDirectories",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_skipDirectories"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003AstaticPart\u0028\u0029",
            "name": "staticPart",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_staticPart"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Asuffix\u0028\u0029",
            "name": "suffix",
            "summary": "",
            "url": "classes/Flow-Filesystem-Path.html#method_suffix"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Difference\u0020between\u0020Path\u003A\u003Auri\u0020and\u0020Path\u003A\u003Apath\u0020is\u0020that\u0020Path\u003A\u003Auri\u0020returns\u0020path\u0020with\u0020scheme\u0020and\u0020Path\u003A\u003Apath\u0020returns\u0020path\u0020without\u0020scheme.",
            "url": "classes/Flow-Filesystem-Path.html#method_uri"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Paths",
            "name": "Paths",
            "summary": "",
            "url": "classes/Flow-Filesystem-Paths.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Paths\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Paths.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Paths\u003A\u003Apartitions\u0028\u0029",
            "name": "partitions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Paths.html#method_partitions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol",
            "name": "Protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol\u003A\u003Ais\u0028\u0029",
            "name": "is",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html#method_is"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol\u003A\u003Ascheme\u0028\u0029",
            "name": "scheme",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html#method_scheme"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol\u003A\u003AvalidateScheme\u0028\u0029",
            "name": "validateScheme",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html#method_validateScheme"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Protocol\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-Filesystem-Protocol.html#property_name"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits",
            "name": "SizeUnits",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AgbToBytes\u0028\u0029",
            "name": "gbToBytes",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#method_gbToBytes"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AkbToBytes\u0028\u0029",
            "name": "kbToBytes",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#method_kbToBytes"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AmbToBytes\u0028\u0029",
            "name": "mbToBytes",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#method_mbToBytes"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AGiB_SIZE",
            "name": "GiB_SIZE",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#constant_GiB_SIZE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AKiB_SIZE",
            "name": "KiB_SIZE",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#constant_KiB_SIZE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SizeUnits\u003A\u003AMiB_SIZE",
            "name": "MiB_SIZE",
            "summary": "",
            "url": "classes/Flow-Filesystem-SizeUnits.html#constant_MiB_SIZE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream",
            "name": "SourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\SourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-SourceStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\BlockVoidLifecycle",
            "name": "BlockVoidLifecycle",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-BlockVoidLifecycle.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\BlockVoidLifecycle\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-BlockVoidLifecycle.html#method_create"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\BlockVoidLifecycle\u003A\u003Afilled\u0028\u0029",
            "name": "filled",
            "summary": "Method\u0020called\u0020by\u0020the\u0020Blocks\u0020collection\u0020when\u0020the\u0020block\u0020is\u0020filled\u0020with\u0020data\u0020and\ncan\u0020be\u0020uploaded\u0020to\u0020the\u0020remote\u0020filesystem.",
            "url": "classes/Flow-Filesystem-Stream-Block-BlockVoidLifecycle.html#method_filled"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalFileBlocksFactory",
            "name": "NativeLocalFileBlocksFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalFileBlocksFactory.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalFileBlocksFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalFileBlocksFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalFileBlocksFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalFileBlocksFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock",
            "name": "NativeLocalStreamBlock",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003Aid\u0028\u0029",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method_id"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\\NativeLocalStreamBlock\u003A\u003AspaceLeft\u0028\u0029",
            "name": "spaceLeft",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block-NativeLocalStreamBlock.html#method_spaceLeft"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block",
            "name": "Block",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003Aid\u0028\u0029",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_id"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "Current\u0020block\u0020size\u0020in\u0020bytes.",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block\u003A\u003AspaceLeft\u0028\u0029",
            "name": "spaceLeft",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Block.html#method_spaceLeft"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\BlockFactory",
            "name": "BlockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-BlockFactory.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\BlockFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-BlockFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\BlockLifecycle",
            "name": "BlockLifecycle",
            "summary": "A\u0020callback\u0020interface\u0020representing\u0020block\u0020of\u0020data\u0020lifecycle.",
            "url": "classes/Flow-Filesystem-Stream-BlockLifecycle.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\BlockLifecycle\u003A\u003Afilled\u0028\u0029",
            "name": "filled",
            "summary": "Method\u0020called\u0020by\u0020the\u0020Blocks\u0020collection\u0020when\u0020the\u0020block\u0020is\u0020filled\u0020with\u0020data\u0020and\ncan\u0020be\u0020uploaded\u0020to\u0020the\u0020remote\u0020filesystem.",
            "url": "classes/Flow-Filesystem-Stream-BlockLifecycle.html#method_filled"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks",
            "name": "Blocks",
            "summary": "Blocks\u0020is\u0020a\u0020collection\u0020of\u0020blocks\u0020that\u0020are\u0020filled\u0020with\u0020data.",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_all"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Ablock\u0028\u0029",
            "name": "block",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_block"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_count"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Adone\u0028\u0029",
            "name": "done",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_done"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Blocks\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Blocks.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream",
            "name": "MemorySourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\MemorySourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-MemorySourceStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode",
            "name": "Mode",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AAPPEND_READ_WRITE",
            "name": "APPEND_READ_WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_APPEND_READ_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AAPPEND_WRITE",
            "name": "APPEND_WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_APPEND_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003ACREATE_READ_WRITE",
            "name": "CREATE_READ_WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_CREATE_READ_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003ACREATE_WRITE",
            "name": "CREATE_WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_CREATE_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AREAD",
            "name": "READ",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_READ"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AREAD_WRITE",
            "name": "READ_WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_READ_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AWRITE",
            "name": "WRITE",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_WRITE"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Mode\u003A\u003AWRITE_READ",
            "name": "WRITE_READ",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-Mode.html#enumcase_WRITE_READ"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream",
            "name": "NativeLocalDestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003AopenAppend\u0028\u0029",
            "name": "openAppend",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_openAppend"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003AopenBlank\u0028\u0029",
            "name": "openBlank",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_openBlank"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalDestinationStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalDestinationStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream",
            "name": "NativeLocalSourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_open"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\NativeLocalSourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-NativeLocalSourceStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\ResourceContext",
            "name": "ResourceContext",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-ResourceContext.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\ResourceContext\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-ResourceContext.html#method_from"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\ResourceContext\u003A\u003Aresource\u0028\u0029",
            "name": "resource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-ResourceContext.html#method_resource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper",
            "name": "StreamWrapper",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_register"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_close\u0028\u0029",
            "name": "stream_close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_eof"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_flush\u0028\u0029",
            "name": "stream_flush",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_flush"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_lock\u0028\u0029",
            "name": "stream_lock",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_lock"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_open"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_seek"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_stat"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_tell"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_stream_write"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003Aurl_stat\u0028\u0029",
            "name": "url_stat",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#method_url_stat"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\StreamWrapper\u003A\u003APROTOCOL",
            "name": "PROTOCOL",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-StreamWrapper.html#constant_PROTOCOL"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream",
            "name": "VoidStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper",
            "name": "VoidStreamWrapper",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_register"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_close\u0028\u0029",
            "name": "stream_close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_eof\u0028\u0029",
            "name": "stream_eof",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_eof"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_flush\u0028\u0029",
            "name": "stream_flush",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_flush"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_lock\u0028\u0029",
            "name": "stream_lock",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_lock"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_open\u0028\u0029",
            "name": "stream_open",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_open"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_read\u0028\u0029",
            "name": "stream_read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_seek\u0028\u0029",
            "name": "stream_seek",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_seek"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_stat\u0028\u0029",
            "name": "stream_stat",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_stat"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_tell\u0028\u0029",
            "name": "stream_tell",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_tell"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Astream_write\u0028\u0029",
            "name": "stream_write",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_stream_write"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003Aurl_stat\u0028\u0029",
            "name": "url_stat",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#method_url_stat"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003APROTOCOL",
            "name": "PROTOCOL",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#constant_PROTOCOL"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\VoidStreamWrapper\u003A\u003A\u0024context",
            "name": "context",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream-VoidStreamWrapper.html#property_context"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream",
            "name": "Stream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Stream.html#method_path"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-filesystem-dsl.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-filesystem-exception.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\Memory",
            "name": "Memory",
            "summary": "",
            "url": "namespaces/flow-filesystem-local-memory.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local",
            "name": "Local",
            "summary": "",
            "url": "namespaces/flow-filesystem-local.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StdOut",
            "name": "StdOut",
            "summary": "",
            "url": "namespaces/flow-filesystem-local-stdout.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Local\\StreamFilter",
            "name": "StreamFilter",
            "summary": "",
            "url": "namespaces/flow-filesystem-local-streamfilter.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path\\Filter",
            "name": "Filter",
            "summary": "",
            "url": "namespaces/flow-filesystem-path-filter.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Path",
            "name": "Path",
            "summary": "",
            "url": "namespaces/flow-filesystem-path.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream\\Block",
            "name": "Block",
            "summary": "",
            "url": "namespaces/flow-filesystem-stream-block.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Stream",
            "name": "Stream",
            "summary": "",
            "url": "namespaces/flow-filesystem-stream.html"
        }            ]
);
