Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\from_parquet\u0028\u0029",
            "name": "from_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_from_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\to_parquet\u0028\u0029",
            "name": "to_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_to_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\array_to_generator\u0028\u0029",
            "name": "array_to_generator",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_array_to_generator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\empty_generator\u0028\u0029",
            "name": "empty_generator",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_empty_generator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\schema_to_parquet\u0028\u0029",
            "name": "schema_to_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_schema_to_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\schema_from_parquet\u0028\u0029",
            "name": "schema_from_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_schema_from_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetEncoder",
            "name": "ParquetEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetEncoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetEncoder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor",
            "name": "ParquetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AunionByName\u0028\u0029",
            "name": "unionByName",
            "summary": "Reconcile\u0020every\u0020listed\u0020file\u0027s\u0020schema\u0020instead\u0020of\u0020trusting\u0020the\u0020first\u0020one.",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_unionByName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithByteOrder\u0028\u0029",
            "name": "withByteOrder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withByteOrder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithColumns\u0028\u0029",
            "name": "withColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithEngine\u0028\u0029",
            "name": "withEngine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withEngine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithOffset\u0028\u0029",
            "name": "withOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithOptions\u0028\u0029",
            "name": "withOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader",
            "name": "ParquetLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003ApartitionBy\u0028\u0029",
            "name": "partitionBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_partitionBy"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Adiscard\u0028\u0029",
            "name": "discard",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_discard"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AsaveMode\u0028\u0029",
            "name": "saveMode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_saveMode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithCompressions\u0028\u0029",
            "name": "withCompressions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withCompressions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithEngine\u0028\u0029",
            "name": "withEngine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withEngine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithOptions\u0028\u0029",
            "name": "withOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile",
            "name": "ParquetSourceFile",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html#method_close"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "Pruning\u0020belongs\u0020to\u0020the\u0020describer,\u0020not\u0020the\u0020fold\u003A\u0020it\u0020is\u0020applied\u0020per\u0020file,\u0020before\u0020the\u0020merge.",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetSourceFile\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetSourceFile.html#property_file"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter\u003A\u003AtoFlow\u0028\u0029",
            "name": "toFlow",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html#method_toFlow"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter\u003A\u003AtoParquet\u0028\u0029",
            "name": "toParquet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html#method_toParquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter\u003A\u003AparquetToFlowType\u0028\u0029",
            "name": "parquetToFlowType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html#method_parquetToFlowType"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ElementsValueConverter",
            "name": "ElementsValueConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ElementsValueConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ElementsValueConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ElementsValueConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ElementsValueConverter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ElementsValueConverter.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ElementsValueConverter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ElementsValueConverter.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\JsonValueConverter",
            "name": "JsonValueConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-JsonValueConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\JsonValueConverter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-JsonValueConverter.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\JsonValueConverter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-JsonValueConverter.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\StructValueConverter",
            "name": "StructValueConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-StructValueConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\StructValueConverter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-StructValueConverter.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\StructValueConverter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-StructValueConverter.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\StructValueConverter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-StructValueConverter.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\UuidValueConverter",
            "name": "UuidValueConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-UuidValueConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\UuidValueConverter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-UuidValueConverter.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\UuidValueConverter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-UuidValueConverter.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ValueConverter",
            "name": "ValueConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ValueConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ValueConverter\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ValueConverter.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ValueConverter\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ValueConverter.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ValueConverters",
            "name": "ValueConverters",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ValueConverters.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter\\ValueConverters\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ValueConverter-ValueConverters.html#method_for"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet",
            "name": "Parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ValueConverter",
            "name": "ValueConverter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet-valueconverter.html"
        }            ]
);
