Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\from_parquet\u0028\u0029",
            "name": "from_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_from_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\to_parquet\u0028\u0029",
            "name": "to_parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html#function_to_parquet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor",
            "name": "ParquetExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithByteOrder\u0028\u0029",
            "name": "withByteOrder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withByteOrder"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithColumns\u0028\u0029",
            "name": "withColumns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withColumns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithOffset\u0028\u0029",
            "name": "withOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetExtractor\u003A\u003AwithOptions\u0028\u0029",
            "name": "withOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetExtractor.html#method_withOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader",
            "name": "ParquetLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithCompressions\u0028\u0029",
            "name": "withCompressions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withCompressions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithOptions\u0028\u0029",
            "name": "withOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withOptions"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\ParquetLoader\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-ParquetLoader.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-RowsNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\RowsNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-RowsNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\RowsNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-RowsNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter\u003A\u003AtoFlow\u0028\u0029",
            "name": "toFlow",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html#method_toFlow"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet\\SchemaConverter\u003A\u003AtoParquet\u0028\u0029",
            "name": "toParquet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Parquet-SchemaConverter.html#method_toParquet"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Parquet",
            "name": "Parquet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-parquet.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
