Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DesintationStream\\AsyncAWSS3BlockLifecycle",
            "name": "AsyncAWSS3BlockLifecycle",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DesintationStream-AsyncAWSS3BlockLifecycle.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DesintationStream\\AsyncAWSS3BlockLifecycle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DesintationStream-AsyncAWSS3BlockLifecycle.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DesintationStream\\AsyncAWSS3BlockLifecycle\u003A\u003Afilled\u0028\u0029",
            "name": "filled",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DesintationStream-AsyncAWSS3BlockLifecycle.html#method_filled"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream",
            "name": "AsyncAWSS3DestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003AopenAppend\u0028\u0029",
            "name": "openAppend",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_openAppend"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003AopenBlank\u0028\u0029",
            "name": "openBlank",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_openBlank"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DestinationStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3DestinationStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem",
            "name": "AsyncAWSS3Filesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3Filesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3Filesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\\Range",
            "name": "Range",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream-Range.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\\Range\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020to\u0020initialize\u0020offset\u0020and\u0020limit.",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream-Range.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\\Range\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "Returns\u0020the\u0020Range\u0020header\u0020string.",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream-Range.html#method_toString"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream",
            "name": "AsyncAWSS3SourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-AsyncAWSS3SourceStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\BlockList",
            "name": "BlockList",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-BlockList.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\BlockList\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-BlockList.html#method_add"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\BlockList\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-BlockList.html#method_count"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\BlockList\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-BlockList.html#method_toArray"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\ContentTypeDetector",
            "name": "ContentTypeDetector",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-ContentTypeDetector.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\ContentTypeDetector\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-ContentTypeDetector.html#method_from"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\DSL\\aws_s3_client\u0028\u0029",
            "name": "aws_s3_client",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws-dsl.html#function_aws_s3_client"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\DSL\\aws_s3_filesystem\u0028\u0029",
            "name": "aws_s3_filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws-dsl.html#function_aws_s3_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options\u003A\u003AblockFactory\u0028\u0029",
            "name": "blockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html#method_blockFactory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options\u003A\u003ApartSize\u0028\u0029",
            "name": "partSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html#method_partSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options\u003A\u003AtmpDir\u0028\u0029",
            "name": "tmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html#method_tmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\Options\u003A\u003AwithBlockSize\u0028\u0029",
            "name": "withBlockSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-Options.html#method_withBlockSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\PathOption",
            "name": "PathOption",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-PathOption.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\PathOption\u003A\u003ABUCKET",
            "name": "BUCKET",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-AsyncAWS-PathOption.html#constant_BUCKET"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3DesintationStream",
            "name": "AsyncAWSS3DesintationStream",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws-asyncawss3desintationstream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS",
            "name": "AsyncAWS",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge.html"
        },                {
            "fqsen": "\\Flow\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\AsyncAWSS3SourceStream",
            "name": "AsyncAWSS3SourceStream",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws-asyncawss3sourcestream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\AsyncAWS\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-asyncaws-dsl.html"
        }            ]
);
