Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector",
            "name": "CSVDetector",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector\u003A\u003Adetect\u0028\u0029",
            "name": "detect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html#method_detect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDialect",
            "name": "CSVDialect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDialect.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDialect\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDialect.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDialect\u003A\u003A\u0024separator",
            "name": "separator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDialect.html#property_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDialect\u003A\u003A\u0024enclosure",
            "name": "enclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDialect.html#property_enclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDialect\u003A\u003A\u0024escape",
            "name": "escape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDialect.html#property_escape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEnclosureScan",
            "name": "CSVEnclosureScan",
            "summary": "CSVRecordBoundary\u0027s\u0020rules\u0020as\u0020a\u0020byte\u0020walk,\u0020for\u0020the\u0020buffers\u0020PCRE\u0020gives\u0020up\u0020on.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEnclosureScan.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEnclosureScan\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEnclosureScan.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEnclosureScan\u003A\u003AendsOutsideAnEnclosure\u0028\u0029",
            "name": "endsOutsideAnEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEnclosureScan.html#method_endsOutsideAnEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEnclosureScan\u003A\u003ABLANKS",
            "name": "BLANKS",
            "summary": "isspace\u0028\u0029\u0020in\u0020the\u0020C\u0020locale,\u0020which\u0020is\u0020what\u0020fgetcsv\u0020skips\u0020before\u0020an\u0020opening\u0020enclosure.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEnclosureScan.html#constant_BLANKS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder",
            "name": "CSVEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder\u003A\u003AencodeHeader\u0028\u0029",
            "name": "encodeHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html#method_encodeHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVEncoder\u003A\u003Aheaders\u0028\u0029",
            "name": "headers",
            "summary": "Null\u0020before\u0020the\u0020first\u0020decoded\u0020line\u003A\u0020a\u00200\u002Dbyte\u0020source\u0020resolves\u0020no\u0020header,\u0020which\u0020is\u0020not\u0020the\u0020same\u0020as\u0020a\nheader\u0020of\u0020zero\u0020columns.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVEncoder.html#method_headers"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor",
            "name": "CSVExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AinferSchema\u0028\u0029",
            "name": "inferSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_inferSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003ApartitionSchema\u0028\u0029",
            "name": "partitionSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_partitionSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Astatistics\u0028\u0029",
            "name": "statistics",
            "summary": "Rows\u0020come\u0020from\u0020the\u0020sample\u0020schema\u0020inference\u0020already\u0020read\u003B\u0020without\u0020one\u0020they\u0020are\u0020unknown,\u0020a\u0020sniff\u0020is\u0020never\u0020run\njust\u0020for\u0020them.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_statistics"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithBOMRemoval\u0028\u0029",
            "name": "withBOMRemoval",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withBOMRemoval"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithCharactersReadInLine\u0028\u0029",
            "name": "withCharactersReadInLine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withCharactersReadInLine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEmptyToNull\u0028\u0029",
            "name": "withEmptyToNull",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEmptyToNull"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEnclosure\u0028\u0029",
            "name": "withEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEscape\u0028\u0029",
            "name": "withEscape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEscape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithSeparator\u0028\u0029",
            "name": "withSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader",
            "name": "CSVFileReader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader\u003A\u003Abatches\u0028\u0029",
            "name": "batches",
            "summary": "Abandoning\u0020the\u0020generator\u0020closes\u0020the\u0020source.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html#method_batches"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader\u003A\u003Acolumns\u0028\u0029",
            "name": "columns",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html#method_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader\u003A\u003Aheader\u0028\u0029",
            "name": "header",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html#method_header"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileReader\u003A\u003Asamples\u0028\u0029",
            "name": "samples",
            "summary": "\u0024rowBudget\u0020is\u0020unused\u003A\u0020SchemaInferrer\u0020hands\u0020each\u0020unit\u0020its\u0020remaining\u0020budget\u0020through\u0020sniffColumnTypes\u0028\u0029.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileReader.html#method_samples"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileSample",
            "name": "CSVFileSample",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileSample.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileSample\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileSample.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileSample\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "The\u0020source\u0020is\u0020opened\u0020on\u0020the\u0020first\u0020advance\u003B\u0020abandoning\u0020the\u0020generator\u0020closes\u0020it.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileSample.html#method_getIterator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileSample\u003A\u003AsniffColumnTypes\u0028\u0029",
            "name": "sniffColumnTypes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileSample.html#method_sniffColumnTypes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVFileSample\u003A\u003Asampled\u0028\u0029",
            "name": "sampled",
            "summary": "What\u0020the\u0020last\u0020sniffColumnTypes\u0028\u0029\u0020read\u003B\u0020null\u0020until\u0020one\u0020ran.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVFileSample.html#method_sampled"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVHeader",
            "name": "CSVHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVHeader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVHeader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u0024source\u0020is\u0020a\u0020plain\u0020label,\u0020never\u0020a\u0020Path\u0020or\u0020a\u0020SourceFile,\u0020so\u0020a\u0020sampler\u0020with\u0020no\u0020file\u0020can\u0020supply\u0020its\u0020own.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVHeader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVHeader\u003A\u003A\u0024names",
            "name": "names",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVHeader.html#property_names"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVHeader\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVHeader.html#property_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLineReader",
            "name": "CSVLineReader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLineReader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLineReader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLineReader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLineReader\u003A\u003AlastRecordBytes\u0028\u0029",
            "name": "lastRecordBytes",
            "summary": "The\u0020bytes\u0020the\u0020record\u0020readLines\u0028\u0029\u0020yielded\u0020last\u0020took\u0020in\u0020the\u0020stream,\u0020line\u0020endings\u0020and\u0020BOM\u0020included.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLineReader.html#method_lastRecordBytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLineReader\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLineReader.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader",
            "name": "CSVLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003ApartitionBy\u0028\u0029",
            "name": "partitionBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_partitionBy"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Adiscard\u0028\u0029",
            "name": "discard",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_discard"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AsaveMode\u0028\u0029",
            "name": "saveMode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_saveMode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithDateFormat\u0028\u0029",
            "name": "withDateFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withDateFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithEnclosure\u0028\u0029",
            "name": "withEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithEscape\u0028\u0029",
            "name": "withEscape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withEscape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithNewLineSeparator\u0028\u0029",
            "name": "withNewLineSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withNewLineSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithSeparator\u0028\u0029",
            "name": "withSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource",
            "name": "CSVOpenSource",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_close"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003AproducedBytes\u0028\u0029",
            "name": "producedBytes",
            "summary": "The\u0020bytes,\u0020as\u0020read,\u0020of\u0020the\u0020rows\u0020producedRows\u0028\u0029\u0020counts\u003A\u0020line\u0020endings\u0020included,\u0020the\u0020header\u0020record\u0020excluded.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_producedBytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003AproducedRows\u0028\u0029",
            "name": "producedRows",
            "summary": "Rows\u0020read\u0020from\u0020the\u0020source\u0020so\u0020far\u0020by\u0020records\u0028\u0029\u0020or\u0020sniff\u0028\u0029\u0020\u002D\u0020it\u0020may\u0020be\u0020more\u0020than\u0020a\u0020consumer\u0020took.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_producedRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003Acolumns\u0028\u0029",
            "name": "columns",
            "summary": "This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003Arecords\u0028\u0029",
            "name": "records",
            "summary": "This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_records"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVOpenSource\u003A\u003Asniff\u0028\u0029",
            "name": "sniff",
            "summary": "SchemaInferrer\u003A\u003Asniff\u0028\u0029\u0020over\u0020records\u0028\u0029.\u0020This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVOpenSource.html#method_sniff"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions",
            "name": "CSVReadOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithCharactersReadInLine\u0028\u0029",
            "name": "withCharactersReadInLine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withCharactersReadInLine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithEmptyToNull\u0028\u0029",
            "name": "withEmptyToNull",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withEmptyToNull"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithEnclosure\u0028\u0029",
            "name": "withEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithEscape\u0028\u0029",
            "name": "withEscape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withEscape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024withHeader",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithRemoveBOM\u0028\u0029",
            "name": "withRemoveBOM",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withRemoveBOM"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003AwithSeparator\u0028\u0029",
            "name": "withSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#method_withSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024emptyToNull",
            "name": "emptyToNull",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_emptyToNull"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024removeBOM",
            "name": "removeBOM",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_removeBOM"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024separator",
            "name": "separator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024enclosure",
            "name": "enclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_enclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024escape",
            "name": "escape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_escape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVReadOptions\u003A\u003A\u0024charactersReadInLine",
            "name": "charactersReadInLine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVReadOptions.html#property_charactersReadInLine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRecordBoundary",
            "name": "CSVRecordBoundary",
            "summary": "A\u0020record\u0020is\u0020complete\u0020when\u0020the\u0020buffer\u0020ends\u0020outside\u0020an\u0020enclosure.\u0020An\u0020enclosure\u0020only\u0020OPENS\u0020at\u0020a\u0020field\u0020start\u0020\u002D\u0020buffer\nstart\u0020or\u0020just\u0020after\u0020the\u0020separator,\u0020blanks\u0020allowed\u0020\u002D\u0020which\u0020is\u0020what\u0020fgetcsv\u0020does\u0020and\u0020what\u0020counting\u0020enclosures\u0020cannot\nexpress.\u0020Possessive\u0020quantifiers\u0020throughout\u003A\u0020the\u0020pattern\u0020must\u0020stay\u0020linear\u0020on\u0020a\u0020multi\u002Dmegabyte\u0020buffer.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRecordBoundary.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRecordBoundary\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRecordBoundary.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRecordBoundary\u003A\u003AisComplete\u0028\u0029",
            "name": "isComplete",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRecordBoundary.html#method_isComplete"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRowNormalizer",
            "name": "CSVRowNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRowNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRowNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRowNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVRowNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "Normalize\u0020CSV\u0020row\u0020data\u0020to\u0020match\u0020the\u0020expected\u0020number\u0020of\u0020headers.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVRowNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles",
            "name": "CSVSampledFiles",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003AestimatedRows\u0028\u0029",
            "name": "estimatedRows",
            "summary": "Listed\u0020bytes\u0020over\u0020the\u0020mean\u0020bytes\u0020of\u0020the\u0020sampled\u0020rows\u003B\u0020exact\u0020when\u0020the\u0020samples\u0020read\u0020every\u0020row\u0020of\u0020every\u0020listed\u0020file.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#method_estimatedRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#property_files"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003A\u0024rows",
            "name": "rows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#property_rows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003A\u0024bytes",
            "name": "bytes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#property_bytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledFiles\u003A\u003A\u0024whole",
            "name": "whole",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledFiles.html#property_whole"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledRows",
            "name": "CSVSampledRows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledRows.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledRows\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledRows.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledRows\u003A\u003A\u0024bytes",
            "name": "bytes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledRows.html#property_bytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledRows\u003A\u003A\u0024rows",
            "name": "rows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledRows.html#property_rows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSampledRows\u003A\u003A\u0024wholeFile",
            "name": "wholeFile",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSampledRows.html#property_wholeFile"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSamples",
            "name": "CSVSamples",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSamples.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSamples\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSamples.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSamples\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Keeps\u0020only\u0020the\u0020samples\u0020the\u0020consumer\u0020pulled\u003A\u0020a\u0020listing\u0020the\u0020inference\u0020stopped\u0020short\u0020of\u0020costs\u0020nothing.",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSamples.html#method_getIterator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSamples\u003A\u003AsampledFiles\u0028\u0029",
            "name": "sampledFiles",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSamples.html#method_sampledFiles"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSourceOpener",
            "name": "CSVSourceOpener",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSourceOpener.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSourceOpener\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSourceOpener.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVSourceOpener\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVSourceOpener.html#method_open"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option",
            "name": "Option",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_isValid"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_parse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_reset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Ascore\u0028\u0029",
            "name": "score",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_score"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024separator",
            "name": "separator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024enclosure",
            "name": "enclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_enclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024escape",
            "name": "escape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_escape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_all"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Abest\u0028\u0029",
            "name": "best",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_best"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003AonlyValid\u0028\u0029",
            "name": "onlyValid",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_onlyValid"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_parse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_reset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Exception\\CantDetectCSVOptions",
            "name": "CantDetectCSVOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Exception-CantDetectCSVOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\from_csv\u0028\u0029",
            "name": "from_csv",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_from_csv"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\to_csv\u0028\u0029",
            "name": "to_csv",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_to_csv"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\csv_detect_separator\u0028\u0029",
            "name": "csv_detect_separator",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_csv_detect_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource",
            "name": "NativeCSVOpenSource",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003AisSupported\u0028\u0029",
            "name": "isSupported",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_isSupported"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_close"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003Acolumns\u0028\u0029",
            "name": "columns",
            "summary": "This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003AproducedBytes\u0028\u0029",
            "name": "producedBytes",
            "summary": "The\u0020bytes,\u0020as\u0020read,\u0020of\u0020the\u0020rows\u0020producedRows\u0028\u0029\u0020counts\u003A\u0020line\u0020endings\u0020included,\u0020the\u0020header\u0020record\u0020excluded.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_producedBytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003AproducedRows\u0028\u0029",
            "name": "producedRows",
            "summary": "Rows\u0020read\u0020from\u0020the\u0020source\u0020so\u0020far\u0020by\u0020records\u0028\u0029\u0020or\u0020sniff\u0028\u0029\u0020\u002D\u0020it\u0020may\u0020be\u0020more\u0020than\u0020a\u0020consumer\u0020took.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_producedRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003Arecords\u0028\u0029",
            "name": "records",
            "summary": "This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_records"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003Asniff\u0028\u0029",
            "name": "sniff",
            "summary": "SchemaInferrer\u003A\u003Asniff\u0028\u0029\u0020over\u0020records\u0028\u0029.\u0020This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#method_sniff"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\NativeCSVOpenSource\u003A\u003ACHUNK",
            "name": "CHUNK",
            "summary": "Each\u0020chunk\u0020is\u0020held\u0020as\u0020a\u0020PHP\u0020string,\u0020so\u0020it\u0020sets\u0020the\u0020path\u0027s\u0020peak\u0020memory.\u002032\u0020KB\u0020measured\u002012.0\u0020MB\u0020real\u0020peak\u0020\u002D\u0020the\u0020PHP\npath\u0027s\u0020own\u0020\u002D\u0020on\u0020a\u002057\u0020MB\u0020\/\u002011\u002Dcolumn\u0020file\u0020\u0028\u007E600\u0020B\/row\u0029\u0020and\u0020a\u002054\u0020MB\u0020\/\u00205\u002Dcolumn\u0020file\u0020\u0028\u007E4\u0020KB\/row\u0029\u003B\u002064\u0020KB\u0020already\nreached\u002014.0\u0020MB\u0020on\u0020the\u0020wide\u0020one.\u0020The\u0020headroom\u0020depends\u0020on\u0020the\u0020file\u0020shape.",
            "url": "classes/Flow-ETL-Adapter-CSV-NativeCSVOpenSource.html#constant_CHUNK"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource",
            "name": "PhpCSVOpenSource",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_close"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003Acolumns\u0028\u0029",
            "name": "columns",
            "summary": "This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_columns"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003Arecords\u0028\u0029",
            "name": "records",
            "summary": "CSVLineReader\u003A\u003AreadLines\u0028\u0029\u0020already\u0020joins\u0020a\u0020quoted\u0020multi\u002Dline\u0020record,\u0020so\u0020never\u0020re\u002Dsplit\u0020or\u0020re\u002Djoin\u0020here.",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_records"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003AproducedBytes\u0028\u0029",
            "name": "producedBytes",
            "summary": "The\u0020bytes,\u0020as\u0020read,\u0020of\u0020the\u0020rows\u0020producedRows\u0028\u0029\u0020counts\u003A\u0020line\u0020endings\u0020included,\u0020the\u0020header\u0020record\u0020excluded.",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_producedBytes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003AproducedRows\u0028\u0029",
            "name": "producedRows",
            "summary": "Rows\u0020read\u0020from\u0020the\u0020source\u0020so\u0020far\u0020by\u0020records\u0028\u0029\u0020or\u0020sniff\u0028\u0029\u0020\u002D\u0020it\u0020may\u0020be\u0020more\u0020than\u0020a\u0020consumer\u0020took.",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_producedRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\PhpCSVOpenSource\u003A\u003Asniff\u0028\u0029",
            "name": "sniff",
            "summary": "SchemaInferrer\u003A\u003Asniff\u0028\u0029\u0020over\u0020records\u0028\u0029.\u0020This\u0020instance\u0020is\u0020consumed\u0020afterwards.",
            "url": "classes/Flow-ETL-Adapter-CSV-PhpCSVOpenSource.html#method_sniff"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV",
            "name": "CSV",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector",
            "name": "Detector",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv-detector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv-exception.html"
        }            ]
);
