Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector",
            "name": "CSVDetector",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVDetector\u003A\u003Adetect\u0028\u0029",
            "name": "detect",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVDetector.html#method_detect"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor",
            "name": "CSVExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithBOMRemoval\u0028\u0029",
            "name": "withBOMRemoval",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withBOMRemoval"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithCharactersReadInLine\u0028\u0029",
            "name": "withCharactersReadInLine",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withCharactersReadInLine"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEmptyToNull\u0028\u0029",
            "name": "withEmptyToNull",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEmptyToNull"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEnclosure\u0028\u0029",
            "name": "withEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithEscape\u0028\u0029",
            "name": "withEscape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withEscape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVExtractor\u003A\u003AwithSeparator\u0028\u0029",
            "name": "withSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVExtractor.html#method_withSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader",
            "name": "CSVLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithEnclosure\u0028\u0029",
            "name": "withEnclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withEnclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithEscape\u0028\u0029",
            "name": "withEscape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withEscape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithNewLineSeparator\u0028\u0029",
            "name": "withNewLineSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withNewLineSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003AwithSeparator\u0028\u0029",
            "name": "withSeparator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_withSeparator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\CSVLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-CSVLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option",
            "name": "Option",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_isValid"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_parse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_reset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003Ascore\u0028\u0029",
            "name": "score",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#method_score"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024separator",
            "name": "separator",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024enclosure",
            "name": "enclosure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_enclosure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Option\u003A\u003A\u0024escape",
            "name": "escape",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Option.html#property_escape"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_all"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Abest\u0028\u0029",
            "name": "best",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_best"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003AonlyValid\u0028\u0029",
            "name": "onlyValid",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_onlyValid"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_parse"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector\\Options\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Detector-Options.html#method_reset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Exception\\CantDetectCSVOptions",
            "name": "CantDetectCSVOptions",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-Exception-CantDetectCSVOptions.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\from_csv\u0028\u0029",
            "name": "from_csv",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_from_csv"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\to_csv\u0028\u0029",
            "name": "to_csv",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_to_csv"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\csv_detect_separator\u0028\u0029",
            "name": "csv_detect_separator",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html#function_csv_detect_separator"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer\\EntryNormalizer",
            "name": "EntryNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer-EntryNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer\\EntryNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer-EntryNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer\\EntryNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer-EntryNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-CSV-RowsNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV",
            "name": "CSV",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Detector",
            "name": "Detector",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv-detector.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv-exception.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\CSV\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-csv-rowsnormalizer.html"
        }            ]
);
