Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute",
            "name": "XMLAttribute",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#property_value"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode",
            "name": "XMLNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AflatNode\u0028\u0029",
            "name": "flatNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_flatNode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AnestedNode\u0028\u0029",
            "name": "nestedNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_nestedNode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_append"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AappendAttribute\u0028\u0029",
            "name": "appendAttribute",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_appendAttribute"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AappendChild\u0028\u0029",
            "name": "appendChild",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_appendChild"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AhasChildren\u0028\u0029",
            "name": "hasChildren",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_hasChildren"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AhasValue\u0028\u0029",
            "name": "hasValue",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_hasValue"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_value"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_attributes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024children",
            "name": "children",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_children"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType",
            "name": "XMLNodeType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType\u003A\u003AFLAT",
            "name": "FLAT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html#enumcase_FLAT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType\u003A\u003ANESTED",
            "name": "NESTED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html#enumcase_NESTED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\from_xml\u0028\u0029",
            "name": "from_xml",
            "summary": "In\u0020order\u0020to\u0020iterate\u0020only\u0020over\u0020\u003Celement\u003E\u0020nodes\u0020use\u0020\u0060from_xml\u0028\u0024file\u0029\u002D\u003EwithXMLNodePath\u0028\u0027root\/elements\/element\u0027\u0029\u0060.",
            "url": "namespaces/flow-etl-adapter-xml.html#function_from_xml"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\to_xml\u0028\u0029",
            "name": "to_xml",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml.html#function_to_xml"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader",
            "name": "XMLLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithAttributePrefix\u0028\u0029",
            "name": "withAttributePrefix",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withAttributePrefix"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithListElementName\u0028\u0029",
            "name": "withListElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withListElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementKeyName\u0028\u0029",
            "name": "withMapElementKeyName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementKeyName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementName\u0028\u0029",
            "name": "withMapElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementValueName\u0028\u0029",
            "name": "withMapElementValueName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementValueName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithRootElementName\u0028\u0029",
            "name": "withRootElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withRootElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithRowElementName\u0028\u0029",
            "name": "withRowElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withRowElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithXMLAttributes\u0028\u0029",
            "name": "withXMLAttributes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withXMLAttributes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwriteXML\u0028\u0029",
            "name": "writeXML",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_writeXML"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer",
            "name": "PHPValueNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024attributePrefix",
            "name": "attributePrefix",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_attributePrefix"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024dateTimeFormat",
            "name": "dateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_dateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024listElementName",
            "name": "listElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_listElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024mapElementName",
            "name": "mapElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_mapElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024mapElementKeyName",
            "name": "mapElementKeyName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_mapElementKeyName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\\PHPValueNormalizer\u003A\u003A\u0024mapElementValueName",
            "name": "mapElementValueName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer-PHPValueNormalizer.html#property_mapElementValueName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer",
            "name": "EntryNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer-EntryNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\u003A\u003Anormalize\u0028\u0029",
            "name": "normalize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RowsNormalizer.html#method_normalize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor",
            "name": "XMLParserExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "In\u0020order\u0020to\u0020iterate\u0020only\u0020over\u0020\u003Celement\u003E\u0020nodes\u0020use\u0020\u0060\u0024loader\u002D\u003EwithXMLNodePath\u0028\u0027root\/elements\/element\u0027\u0029\u0060.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AcharacterDataHandler\u0028\u0029",
            "name": "characterDataHandler",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_characterDataHandler"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AendElementHandler\u0028\u0029",
            "name": "endElementHandler",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_endElementHandler"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AstartElementHandler\u0028\u0029",
            "name": "startElementHandler",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_startElementHandler"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithBufferSize\u0028\u0029",
            "name": "withBufferSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withBufferSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithXMLNodePath\u0028\u0029",
            "name": "withXMLNodePath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withXMLNodePath"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor",
            "name": "XMLReaderExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\DOMDocumentWriter",
            "name": "DOMDocumentWriter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-DOMDocumentWriter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\DOMDocumentWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-DOMDocumentWriter.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter",
            "name": "XMLWriter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter.html#method_write"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction",
            "name": "Abstraction",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-abstraction.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML",
            "name": "XML",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader",
            "name": "Loader",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-loader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer\\EntryNormalizer",
            "name": "EntryNormalizer",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-rowsnormalizer-entrynormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RowsNormalizer",
            "name": "RowsNormalizer",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-rowsnormalizer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter",
            "name": "XMLWriter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-xmlwriter.html"
        }            ]
);
