Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute",
            "name": "XMLAttribute",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLAttribute\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLAttribute.html#property_value"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode",
            "name": "XMLNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AflatNode\u0028\u0029",
            "name": "flatNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_flatNode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003Anested\u0028\u0029",
            "name": "nested",
            "summary": "A\u0020nested\u0020node\u0020built\u0020with\u0020all\u0020its\u0020attributes\u0020and\u0020children\u0020at\u0020once\u0020\u002D\u0020append\u0028\u0029\u0020copies\u0020the\u0020whole\u0020node\u0020per\u0020call.",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_nested"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AnestedNode\u0028\u0029",
            "name": "nestedNode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_nestedNode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_append"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AappendAttribute\u0028\u0029",
            "name": "appendAttribute",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_appendAttribute"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AappendChild\u0028\u0029",
            "name": "appendChild",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_appendChild"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AhasChildren\u0028\u0029",
            "name": "hasChildren",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_hasChildren"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003AhasValue\u0028\u0029",
            "name": "hasValue",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#method_hasValue"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_value"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_type"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024attributes",
            "name": "attributes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_attributes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNode\u003A\u003A\u0024children",
            "name": "children",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNode.html#property_children"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType",
            "name": "XMLNodeType",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType\u003A\u003AFLAT",
            "name": "FLAT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html#enumcase_FLAT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction\\XMLNodeType\u003A\u003ANESTED",
            "name": "NESTED",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Abstraction-XMLNodeType.html#enumcase_NESTED"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\from_xml\u0028\u0029",
            "name": "from_xml",
            "summary": "In\u0020order\u0020to\u0020iterate\u0020only\u0020over\u0020\u003Celement\u003E\u0020nodes\u0020use\u0020\u0060from_xml\u0028\u0024file\u0029\u002D\u003EwithXMLNodePath\u0028\u0027root\/elements\/element\u0027\u0029\u0060.",
            "url": "namespaces/flow-etl-adapter-xml.html#function_from_xml"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\to_xml\u0028\u0029",
            "name": "to_xml",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml.html#function_to_xml"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader",
            "name": "XMLLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003ApartitionBy\u0028\u0029",
            "name": "partitionBy",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_partitionBy"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Adiscard\u0028\u0029",
            "name": "discard",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_discard"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Adestination\u0028\u0029",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_destination"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AsaveMode\u0028\u0029",
            "name": "saveMode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_saveMode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithAttributePrefix\u0028\u0029",
            "name": "withAttributePrefix",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withAttributePrefix"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithDateFormat\u0028\u0029",
            "name": "withDateFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withDateFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithListElementName\u0028\u0029",
            "name": "withListElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withListElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementKeyName\u0028\u0029",
            "name": "withMapElementKeyName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementKeyName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementName\u0028\u0029",
            "name": "withMapElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithMapElementValueName\u0028\u0029",
            "name": "withMapElementValueName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withMapElementValueName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithRootElementName\u0028\u0029",
            "name": "withRootElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withRootElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithRowElementName\u0028\u0029",
            "name": "withRowElementName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withRowElementName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003AwithXMLAttributes\u0028\u0029",
            "name": "withXMLAttributes",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_withXMLAttributes"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader\\XMLLoader\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-Loader-XMLLoader.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RootlessDocument",
            "name": "RootlessDocument",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-RootlessDocument.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\RootlessDocument\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "An\u0020optional\u0020UTF\u002D8\u0020BOM,\u0020then\u0020only\u0020whitespace,\u0020comments\u0020and\u0020processing\u0020instructions\u0020\u002D\u0020what\u0020libxml\u00202.12\u0020and\u0020later\nreport\u0020as\u0020an\u0020empty\u0020document.\u0020Reading\u0020stops\u0020at\u0020the\u0020first\u0020byte\u0020that\u0020proves\u0020the\u0020document\u0020has\u0020more.",
            "url": "classes/Flow-ETL-Adapter-XML-RootlessDocument.html#method_matches"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLEncoder",
            "name": "XMLEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLEncoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLEncoder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLNodes",
            "name": "XMLNodes",
            "summary": "libxml\u0020builds\u0020each\u0020node\u0027s\u0020DOM\u0020in\u0020C,\u0020so\u0020no\u0020element,\u0020attribute\u0020or\u0020text\u0020of\u0020the\u0020document\u0020passes\u0020through\u0020PHP.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLNodes.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLNodes\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLNodes.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLNodes\u003A\u003Aof\u0028\u0029",
            "name": "of",
            "summary": "Each\u0020element\u0020on\u0020the\u0020path\u0020as\u0020a\u0020document\u0020of\u0020its\u0020own,\u0020declaring\u0020every\u0020namespace\u0020it\u0020uses.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLNodes.html#method_of"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor",
            "name": "XMLParserExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "To\u0020iterate\u0020only\u0020over\u0020\u003Celement\u003E\u0020nodes,\u0020use\u0020\u0060\u0024loader\u002D\u003EwithXMLNodePath\u0028\u0027root\/elements\/element\u0027\u0029\u0060.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithBufferSize\u0028\u0029",
            "name": "withBufferSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withBufferSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLParserExtractor\u003A\u003AwithXMLNodePath\u0028\u0029",
            "name": "withXMLNodePath",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLParserExtractor.html#method_withXMLNodePath"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor",
            "name": "XMLReaderExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "In\u0020order\u0020to\u0020iterate\u0020only\u0020over\u0020\u003Celement\u003E\u0020nodes\u0020us\u0020root\/elements\/element.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003AisRepeatable\u0028\u0029",
            "name": "isRepeatable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_isRepeatable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003Aschema\u0028\u0029",
            "name": "schema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLReaderExtractor\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLReaderExtractor.html#method_withSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\DOMDocumentWriter",
            "name": "DOMDocumentWriter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-DOMDocumentWriter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\DOMDocumentWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-DOMDocumentWriter.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\StringXMLWriter",
            "name": "StringXMLWriter",
            "summary": "DOMDocumentWriter\u0027s\u0020output\u0020on\u0020libxml\u00202.14\u0020and\u0020later,\u0020byte\u0020for\u0020byte,\u0020without\u0020building\u0020a\u0020DOM\u0020for\u0020every\u0020row\u003A\u0020libxml\u0027s\nescaping,\u0020a\u0020control\u0020character\u0020written\u0020as\u0020U\u002BFFFD,\u0020a\u0020value\u0020cut\u0020at\u0020its\u0020first\u0020NUL,\u0020and\u0020a\u0020name\u0020DOM\u0020refuses\u0020refused\u0020with\nDOM\u0027s\u0020exception.",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-StringXMLWriter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\\StringXMLWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter-StringXMLWriter.html#method_write"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter",
            "name": "XMLWriter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-XML-XMLWriter.html#method_write"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Abstraction",
            "name": "Abstraction",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-abstraction.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML",
            "name": "XML",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\Loader",
            "name": "Loader",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-loader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\XML\\XMLWriter",
            "name": "XMLWriter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-xml-xmlwriter.html"
        }            ]
);
