Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\to_meilisearch_bulk_index\u0028\u0029",
            "name": "to_meilisearch_bulk_index",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-meilisearch.html#function_to_meilisearch_bulk_index"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\to_meilisearch_bulk_update\u0028\u0029",
            "name": "to_meilisearch_bulk_update",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-meilisearch.html#function_to_meilisearch_bulk_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\meilisearch_hits_to_rows\u0028\u0029",
            "name": "meilisearch_hits_to_rows",
            "summary": "Transforms\u0020Meilisearch\u0020results\u0020into\u0020clear\u0020Flow\u0020Rows.",
            "url": "namespaces/flow-etl-adapter-meilisearch.html#function_meilisearch_hits_to_rows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\from_meilisearch\u0028\u0029",
            "name": "from_meilisearch",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-meilisearch.html#function_from_meilisearch"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\HitsIntoRowsTransformer",
            "name": "HitsIntoRowsTransformer",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-HitsIntoRowsTransformer.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\HitsIntoRowsTransformer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-HitsIntoRowsTransformer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\HitsIntoRowsTransformer\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-HitsIntoRowsTransformer.html#method_transform"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchExtractor",
            "name": "MeilisearchExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchLoader",
            "name": "MeilisearchLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchLoader\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchLoader.html#method_update"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\MeilisearchLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-MeilisearchLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams",
            "name": "SearchParams",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003AasArray\u0028\u0029",
            "name": "asArray",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method_asArray"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003AgetLimit\u0028\u0029",
            "name": "getLimit",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method_getLimit"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003AgetOffset\u0028\u0029",
            "name": "getOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method_getOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003AgetQuery\u0028\u0029",
            "name": "getQuery",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method_getQuery"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchParams\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchParams.html#method_set"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults",
            "name": "SearchResults",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults\u003A\u003Apages\u0028\u0029",
            "name": "pages",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html#method_pages"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html#method_size"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults\u003A\u003AtoRows\u0028\u0029",
            "name": "toRows",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html#method_toRows"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP\\SearchResults\u003A\u003Atotal\u0028\u0029",
            "name": "total",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Meilisearch-MeilisearchPHP-SearchResults.html#method_total"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch",
            "name": "Meilisearch",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-meilisearch.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Meilisearch\\MeilisearchPHP",
            "name": "MeilisearchPHP",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-meilisearch-meilisearchphp.html"
        }            ]
);
