Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\\AzureBlobBlockLifecycle",
            "name": "AzureBlobBlockLifecycle",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream-AzureBlobBlockLifecycle.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\\AzureBlobBlockLifecycle\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream-AzureBlobBlockLifecycle.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\\AzureBlobBlockLifecycle\u003A\u003Afilled\u0028\u0029",
            "name": "filled",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream-AzureBlobBlockLifecycle.html#method_filled"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream",
            "name": "AzureBlobDestinationStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003AopenAppend\u0028\u0029",
            "name": "openAppend",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_openAppend"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003AopenBlank\u0028\u0029",
            "name": "openBlank",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_openBlank"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_append"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003AfromResource\u0028\u0029",
            "name": "fromResource",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_fromResource"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobDestinationStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem",
            "name": "AzureBlobFilesystem",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003AappendTo\u0028\u0029",
            "name": "appendTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_appendTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003AgetSystemTmpDir\u0028\u0029",
            "name": "getSystemTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_getSystemTmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_list"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003Amv\u0028\u0029",
            "name": "mv",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_mv"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003Aprotocol\u0028\u0029",
            "name": "protocol",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_protocol"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003AreadFrom\u0028\u0029",
            "name": "readFrom",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_readFrom"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003Arm\u0028\u0029",
            "name": "rm",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_rm"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_status"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobFilesystem\u003A\u003AwriteTo\u0028\u0029",
            "name": "writeTo",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobFilesystem.html#method_writeTo"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream",
            "name": "AzureBlobSourceStream",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_close"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_content"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003AisOpen\u0028\u0029",
            "name": "isOpen",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_isOpen"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Aiterate\u0028\u0029",
            "name": "iterate",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_iterate"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_path"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_read"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003AreadLines\u0028\u0029",
            "name": "readLines",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_readLines"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobSourceStream\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-AzureBlobSourceStream.html#method_size"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\DSL\\azure_filesystem_options\u0028\u0029",
            "name": "azure_filesystem_options",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-azure-dsl.html#function_azure_filesystem_options"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\DSL\\azure_filesystem\u0028\u0029",
            "name": "azure_filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-azure-dsl.html#function_azure_filesystem"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options",
            "name": "Options",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AblockFactory\u0028\u0029",
            "name": "blockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_blockFactory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AblockSize\u0028\u0029",
            "name": "blockSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_blockSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AlistBlobOptions\u0028\u0029",
            "name": "listBlobOptions",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_listBlobOptions"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AtmpDir\u0028\u0029",
            "name": "tmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_tmpDir"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithBlockFactory\u0028\u0029",
            "name": "withBlockFactory",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withBlockFactory"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithBlockSize\u0028\u0029",
            "name": "withBlockSize",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withBlockSize"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithListBlobInclude\u0028\u0029",
            "name": "withListBlobInclude",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withListBlobInclude"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithListBlobMaxResults\u0028\u0029",
            "name": "withListBlobMaxResults",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withListBlobMaxResults"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithListBlobShowOnly\u0028\u0029",
            "name": "withListBlobShowOnly",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withListBlobShowOnly"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\Options\u003A\u003AwithTmpDir\u0028\u0029",
            "name": "withTmpDir",
            "summary": "",
            "url": "classes/Flow-Filesystem-Bridge-Azure-Options.html#method_withTmpDir"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\AzureBlobDestinationStream",
            "name": "AzureBlobDestinationStream",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-azure-azureblobdestinationstream.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure",
            "name": "Azure",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-azure.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge.html"
        },                {
            "fqsen": "\\Flow\\Filesystem",
            "name": "Filesystem",
            "summary": "",
            "url": "namespaces/flow-filesystem.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Filesystem\\Bridge\\Azure\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-filesystem-bridge-azure-dsl.html"
        }            ]
);
