Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Attribute\\AsCatalogProvider",
            "name": "AsCatalogProvider",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Attribute-AsCatalogProvider.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Attribute\\AsCatalogProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Attribute-AsCatalogProvider.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\CatalogProvider\\ArrayCatalogProvider",
            "name": "ArrayCatalogProvider",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-CatalogProvider-ArrayCatalogProvider.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\CatalogProvider\\ArrayCatalogProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-CatalogProvider-ArrayCatalogProvider.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\CatalogProvider\\ArrayCatalogProvider\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-CatalogProvider-ArrayCatalogProvider.html#method_get"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\CreateDatabaseCommand",
            "name": "CreateDatabaseCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-CreateDatabaseCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\CreateDatabaseCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-CreateDatabaseCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\CurrentCommand",
            "name": "CurrentCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-CurrentCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\CurrentCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-CurrentCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\DiffCommand",
            "name": "DiffCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-DiffCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\DiffCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-DiffCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\DropDatabaseCommand",
            "name": "DropDatabaseCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-DropDatabaseCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\DropDatabaseCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-DropDatabaseCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\ExecuteCommand",
            "name": "ExecuteCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-ExecuteCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\ExecuteCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-ExecuteCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\FormatSqlCommand",
            "name": "FormatSqlCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-FormatSqlCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\FormatSqlCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-FormatSqlCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\GenerateCommand",
            "name": "GenerateCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-GenerateCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\GenerateCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-GenerateCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\LatestCommand",
            "name": "LatestCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-LatestCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\LatestCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-LatestCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\ListCommand",
            "name": "ListCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-ListCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\ListCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-ListCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\MigrateCommand",
            "name": "MigrateCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-MigrateCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\MigrateCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-MigrateCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\RunSqlCommand",
            "name": "RunSqlCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-RunSqlCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\RunSqlCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-RunSqlCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\SessionPurgeCommand",
            "name": "SessionPurgeCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-SessionPurgeCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\SessionPurgeCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-SessionPurgeCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\StatusCommand",
            "name": "StatusCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-StatusCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\StatusCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-StatusCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\UpToDateCommand",
            "name": "UpToDateCommand",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-UpToDateCommand.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command\\UpToDateCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Command-UpToDateCommand.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Connection\\ConnectionParametersFactory",
            "name": "ConnectionParametersFactory",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Connection-ConnectionParametersFactory.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Connection\\ConnectionParametersFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Connection-ConnectionParametersFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler\\CatalogProviderPass",
            "name": "CatalogProviderPass",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-DependencyInjection-Compiler-CatalogProviderPass.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler\\CatalogProviderPass\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-DependencyInjection-Compiler-CatalogProviderPass.html#method_process"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler\\CommandLocatorPass",
            "name": "CommandLocatorPass",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-DependencyInjection-Compiler-CommandLocatorPass.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler\\CommandLocatorPass\u003A\u003Aprocess\u0028\u0029",
            "name": "process",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-DependencyInjection-Compiler-CommandLocatorPass.html#method_process"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler\\CommandLocatorPass\u003A\u003ALOCATOR_SERVICE_ID",
            "name": "LOCATOR_SERVICE_ID",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-DependencyInjection-Compiler-CommandLocatorPass.html#constant_LOCATOR_SERVICE_ID"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle",
            "name": "FlowPostgreSqlBundle",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "The\u0020bundle\u0020class\u0020lives\u0020directly\u0020in\u0020its\u0020package\u0020root\u0020rather\u0020than\u0020the\u0020\u0022modern\u0022\u0020\u0060\u003Croot\u003E\/src\/\u0060\nlayout\u0020that\u0020\u007B\u0040see\u0020AbstractBundle\u003A\u003AgetPath\u0028\u0029\u007D\u0020assumes\u0020\u0028it\u0020returns\u0020\u0060dirname\u0028file,\u00202\u0029\u0060\u0029,\u0020so\u0020the\ndefault\u0020overshoots\u0020by\u0020one\u0020directory\u0020and\u0020Twig\u0020never\u0020registers\u0020the\u0020\u0060\u0040FlowPostgreSql\u0060\u0020view\nnamespace.\u0020Pin\u0020the\u0020path\u0020to\u0020this\u0020directory\u0020so\u0020\u0060Resources\/views\u0060\u0020resolves.",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html#method_getPath"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle\u003A\u003Abuild\u0028\u0029",
            "name": "build",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html#method_build"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html#method_configure"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle\u003A\u003AloadExtension\u0028\u0029",
            "name": "loadExtension",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html#method_loadExtension"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\FlowPostgreSqlBundle\u003A\u003ASERVICE_CONTAINER",
            "name": "SERVICE_CONTAINER",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-FlowPostgreSqlBundle.html#constant_SERVICE_CONTAINER"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Generator\\TwigMigrationGenerator",
            "name": "TwigMigrationGenerator",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Generator-TwigMigrationGenerator.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Generator\\TwigMigrationGenerator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Generator-TwigMigrationGenerator.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Generator\\TwigMigrationGenerator\u003A\u003AgenerateDataMigration\u0028\u0029",
            "name": "generateDataMigration",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Generator-TwigMigrationGenerator.html#method_generateDataMigration"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Generator\\TwigMigrationGenerator\u003A\u003AgenerateSchemaMigration\u0028\u0029",
            "name": "generateSchemaMigration",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Generator-TwigMigrationGenerator.html#method_generateSchemaMigration"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Messenger\\FlowPostgreSqlTransportFactory",
            "name": "FlowPostgreSqlTransportFactory",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Messenger-FlowPostgreSqlTransportFactory.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Messenger\\FlowPostgreSqlTransportFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Messenger-FlowPostgreSqlTransportFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Messenger\\FlowPostgreSqlTransportFactory\u003A\u003AcreateTransport\u0028\u0029",
            "name": "createTransport",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Messenger-FlowPostgreSqlTransportFactory.html#method_createTransport"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Messenger\\FlowPostgreSqlTransportFactory\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Messenger-FlowPostgreSqlTransportFactory.html#method_supports"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector",
            "name": "FlowMigrationsDataCollector",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_collect"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_reset"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getName"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getConnection"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetMigrations\u0028\u0029",
            "name": "getMigrations",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getMigrations"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetConfiguration\u0028\u0029",
            "name": "getConfiguration",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getConfiguration"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getError"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetExecutedCount\u0028\u0029",
            "name": "getExecutedCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getExecutedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetPendingCount\u0028\u0029",
            "name": "getPendingCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getPendingCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetUnavailableCount\u0028\u0029",
            "name": "getUnavailableCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getUnavailableCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowMigrationsDataCollector\u003A\u003AgetTotalCount\u0028\u0029",
            "name": "getTotalCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowMigrationsDataCollector.html#method_getTotalCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector",
            "name": "FlowPostgreSqlDataCollector",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003Acollect\u0028\u0029",
            "name": "collect",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_collect"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AlateCollect\u0028\u0029",
            "name": "lateCollect",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_lateCollect"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_reset"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getName"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetQueries\u0028\u0029",
            "name": "getQueries",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getQueries"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetConnections\u0028\u0029",
            "name": "getConnections",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getConnections"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetQueryCount\u0028\u0029",
            "name": "getQueryCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getQueryCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetRetainedCount\u0028\u0029",
            "name": "getRetainedCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getRetainedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetFailedCount\u0028\u0029",
            "name": "getFailedCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getFailedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetDuplicateCount\u0028\u0029",
            "name": "getDuplicateCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getDuplicateCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\FlowPostgreSqlDataCollector\u003A\u003AgetTotalDurationMs\u0028\u0029",
            "name": "getTotalDurationMs",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-FlowPostgreSqlDataCollector.html#method_getTotalDurationMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient",
            "name": "ProfilerClient",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AbeginTransaction\u0028\u0029",
            "name": "beginTransaction",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_beginTransaction"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_close"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Acommit\u0028\u0029",
            "name": "commit",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_commit"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aconverters\u0028\u0029",
            "name": "converters",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_converters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Acursor\u0028\u0029",
            "name": "cursor",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_cursor"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_execute"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aexplain\u0028\u0029",
            "name": "explain",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_explain"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetch"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchAll"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchAllInto\u0028\u0029",
            "name": "fetchAllInto",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchAllInto"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchInto\u0028\u0029",
            "name": "fetchInto",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchInto"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchOne\u0028\u0029",
            "name": "fetchOne",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchOne"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchOneInto\u0028\u0029",
            "name": "fetchOneInto",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchOneInto"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchScalar\u0028\u0029",
            "name": "fetchScalar",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchScalar"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchScalarBool\u0028\u0029",
            "name": "fetchScalarBool",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchScalarBool"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchScalarFloat\u0028\u0029",
            "name": "fetchScalarFloat",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchScalarFloat"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchScalarInt\u0028\u0029",
            "name": "fetchScalarInt",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchScalarInt"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchScalarString\u0028\u0029",
            "name": "fetchScalarString",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchScalarString"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchSingle\u0028\u0029",
            "name": "fetchSingle",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchSingle"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AfetchSingleInto\u0028\u0029",
            "name": "fetchSingleInto",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_fetchSingleInto"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AgetTransactionNestingLevel\u0028\u0029",
            "name": "getTransactionNestingLevel",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_getTransactionNestingLevel"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AisAutoCommit\u0028\u0029",
            "name": "isAutoCommit",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_isAutoCommit"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AisConnected\u0028\u0029",
            "name": "isConnected",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_isConnected"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AlastInsertId\u0028\u0029",
            "name": "lastInsertId",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_lastInsertId"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Alisten\u0028\u0029",
            "name": "listen",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_listen"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aparameters\u0028\u0029",
            "name": "parameters",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_parameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003ArollBack\u0028\u0029",
            "name": "rollBack",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_rollBack"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003AsetAutoCommit\u0028\u0029",
            "name": "setAutoCommit",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_setAutoCommit"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Atransaction\u0028\u0029",
            "name": "transaction",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_transaction"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Aunlisten\u0028\u0029",
            "name": "unlisten",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_unlisten"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\ProfilerClient\u003A\u003Await\u0028\u0029",
            "name": "wait",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-ProfilerClient.html#method_wait"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder",
            "name": "QueryRecorder",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_add"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003AfailedCount\u0028\u0029",
            "name": "failedCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_failedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003Aqueries\u0028\u0029",
            "name": "queries",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_queries"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003ArecordedCount\u0028\u0029",
            "name": "recordedCount",
            "summary": "Total\u0020queries\u0020passed\u0020to\u0020add\u0028\u0029,\u0020including\u0020entries\u0020already\u0020evicted.",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_recordedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_reset"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003AretainedCount\u0028\u0029",
            "name": "retainedCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_retainedCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorder\u003A\u003AtotalDurationMs\u0028\u0029",
            "name": "totalDurationMs",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorder.html#method_totalDurationMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions",
            "name": "QueryRecorderOptions",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003A\u0024includeParameters",
            "name": "includeParameters",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#property_includeParameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003A\u0024maxQueries",
            "name": "maxQueries",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#property_maxQueries"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003A\u0024maxQueryLength",
            "name": "maxQueryLength",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#property_maxQueryLength"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003A\u0024maxRetainedParameters",
            "name": "maxRetainedParameters",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#property_maxRetainedParameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003AretainsParameters\u0028\u0029",
            "name": "retainsParameters",
            "summary": "Parameters\u0020with\u0020nothing\u0020to\u0020drop\u0020count\u0020as\u0020retained,\u0020so\u0020a\u0020parameterless\u0020query\u0020is\u0020never\nreported\u0020as\u0020truncated.",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#method_retainsParameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003AretainsStatement\u0028\u0029",
            "name": "retainsStatement",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#method_retainsStatement"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\QueryRecorderOptions\u003A\u003AtruncateStatement\u0028\u0029",
            "name": "truncateStatement",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-QueryRecorderOptions.html#method_truncateStatement"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery",
            "name": "RecordedQuery",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024sql",
            "name": "sql",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_sql"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_parameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024durationMs",
            "name": "durationMs",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_durationMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024rowCount",
            "name": "rowCount",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_rowCount"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024failed",
            "name": "failed",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_failed"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_error"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_connection"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024caller",
            "name": "caller",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_caller"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024parametersTruncated",
            "name": "parametersTruncated",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_parametersTruncated"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler\\RecordedQuery\u003A\u003A\u0024statementTruncated",
            "name": "statementTruncated",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Profiler-RecordedQuery.html#property_statementTruncated"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository\\FilesystemMigrationRepository",
            "name": "FilesystemMigrationRepository",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Repository-FilesystemMigrationRepository.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository\\FilesystemMigrationRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Repository-FilesystemMigrationRepository.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository\\FilesystemMigrationRepository\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Repository-FilesystemMigrationRepository.html#method_all"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository\\FilesystemMigrationRepository\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Repository-FilesystemMigrationRepository.html#method_get"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository\\FilesystemMigrationRepository\u003A\u003Ahas\u0028\u0029",
            "name": "has",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Repository-FilesystemMigrationRepository.html#method_has"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Sql\\SqlFileFinder",
            "name": "SqlFileFinder",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Sql-SqlFileFinder.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Sql\\SqlFileFinder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Sql-SqlFileFinder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Sql\\SqlFileFinder\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Resolves\u0020a\u0020Path\u0020\u0028file,\u0020directory,\u0020or\u0020glob\u0029\u0020into\u0020a\u0020list\u0020of\u0020\u0060.sql\u0060\u0020files.",
            "url": "classes/Flow-Bridge-Symfony-PostgreSqlBundle-Sql-SqlFileFinder.html#method_find"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Attribute",
            "name": "Attribute",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-attribute.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\CatalogProvider",
            "name": "CatalogProvider",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-catalogprovider.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-command.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Connection",
            "name": "Connection",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-connection.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection\\Compiler",
            "name": "Compiler",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-dependencyinjection-compiler.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\DependencyInjection",
            "name": "DependencyInjection",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-dependencyinjection.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle",
            "name": "PostgreSqlBundle",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony",
            "name": "Symfony",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Generator",
            "name": "Generator",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-generator.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Messenger",
            "name": "Messenger",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-messenger.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Profiler",
            "name": "Profiler",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-profiler.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-repository.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\PostgreSqlBundle\\Sql",
            "name": "Sql",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-postgresqlbundle-sql.html"
        }            ]
);
