Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream",
            "name": "DataStream",
            "summary": "FlowStreamedResponse\u0020builder.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_open"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Aas\u0028\u0029",
            "name": "as",
            "summary": "Set\u0020the\u0020filename\u0020for\u0020the\u0020response.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_as"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Aconfig\u0028\u0029",
            "name": "config",
            "summary": "Set\u0020the\u0020Config\u0020for\u0020the\u0020DataFrame\u0020execution.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_config"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Aheaders\u0028\u0029",
            "name": "headers",
            "summary": "Set\u0020additional\u0020headers.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_headers"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003AonComplete\u0028\u0029",
            "name": "onComplete",
            "summary": "Set\u0020a\u0020closure\u0020to\u0020be\u0020called\u0020after\u0020streaming\u0020completes.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_onComplete"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Aresponse\u0028\u0029",
            "name": "response",
            "summary": "Create\u0020regular\u0020response\u0020where\u0020whole\u0020dataset\u0020is\u0020loaded\u0020into\u0020the\u0020memory.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_response"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Astatus\u0028\u0029",
            "name": "status",
            "summary": "Set\u0020the\u0020HTTP\u0020status\u0020code.\u0020Default\u0020is\u0020200.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_status"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003AstreamedResponse\u0028\u0029",
            "name": "streamedResponse",
            "summary": "Send\u0020the\u0020data\u0020stream\u0020to\u0020the\u0020output.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_streamedResponse"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "Apply\u0020transformations\u0020to\u0020the\u0020data\u0020stream.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_transform"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\DataStream\u003A\u003AwithoutHeader\u0028\u0029",
            "name": "withoutHeader",
            "summary": "Remove\u0020a\u0020specific\u0020header\u0020if\u0020it\u0020exists.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-DataStream.html#method_withoutHeader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_stream_open\u0028\u0029",
            "name": "http_stream_open",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_stream_open"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_json_output\u0028\u0029",
            "name": "http_json_output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_json_output"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_csv_output\u0028\u0029",
            "name": "http_csv_output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_csv_output"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_xml_output\u0028\u0029",
            "name": "http_xml_output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_xml_output"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_parquet_output\u0028\u0029",
            "name": "http_parquet_output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_parquet_output"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\http_on_complete\u0028\u0029",
            "name": "http_on_complete",
            "summary": "Create\u0020a\u0020StreamClosure\u0020from\u0020a\u0020callable.",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html#function_http_on_complete"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput",
            "name": "CSVOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003AmemoryLoader\u0028\u0029",
            "name": "memoryLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method_memoryLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003AstdoutLoader\u0028\u0029",
            "name": "stdoutLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method_stdoutLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput",
            "name": "JsonOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003AmemoryLoader\u0028\u0029",
            "name": "memoryLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method_memoryLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003AstdoutLoader\u0028\u0029",
            "name": "stdoutLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method_stdoutLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput",
            "name": "ParquetOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003AmemoryLoader\u0028\u0029",
            "name": "memoryLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method_memoryLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003AstdoutLoader\u0028\u0029",
            "name": "stdoutLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method_stdoutLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type",
            "name": "Type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AtoContentTypeHeader\u0028\u0029",
            "name": "toContentTypeHeader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#method_toContentTypeHeader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003ACSV",
            "name": "CSV",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_CSV"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_JSON"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003APARQUET",
            "name": "PARQUET",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_PARQUET"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_TEXT"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AXML",
            "name": "XML",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_XML"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput",
            "name": "XMLOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003AmemoryLoader\u0028\u0029",
            "name": "memoryLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method_memoryLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003AstdoutLoader\u0028\u0029",
            "name": "stdoutLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method_stdoutLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output",
            "name": "Output",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\u003A\u003AmemoryLoader\u0028\u0029",
            "name": "memoryLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html#method_memoryLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\u003A\u003AstdoutLoader\u0028\u0029",
            "name": "stdoutLoader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html#method_stdoutLoader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowBufferedResponse",
            "name": "FlowBufferedResponse",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowBufferedResponse.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowBufferedResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowBufferedResponse.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowBufferedResponse\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowBufferedResponse.html#method_getContent"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowBufferedResponse\u003A\u003AsendContent\u0028\u0029",
            "name": "sendContent",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowBufferedResponse.html#method_sendContent"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowStreamedResponse",
            "name": "FlowStreamedResponse",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowStreamedResponse.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response\\FlowStreamedResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Response-FlowStreamedResponse.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\StreamClosure",
            "name": "StreamClosure",
            "summary": "Interface\u0020for\u0020closures\u0020that\u0020are\u0020called\u0020after\u0020streaming\u0020completes.",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-StreamClosure.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\StreamClosure\u003A\u003AonComplete\u0028\u0029",
            "name": "onComplete",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-StreamClosure.html#method_onComplete"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation",
            "name": "HttpFoundation",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony",
            "name": "Symfony",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output",
            "name": "Output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation-output.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Response",
            "name": "Response",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation-response.html"
        }            ]
);
