Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\FlowStreamedResponse",
            "name": "FlowStreamedResponse",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-FlowStreamedResponse.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\FlowStreamedResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-FlowStreamedResponse.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput",
            "name": "CSVOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003Aloader\u0028\u0029",
            "name": "loader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method_loader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\CSVOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-CSVOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput",
            "name": "JsonOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003Aloader\u0028\u0029",
            "name": "loader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method_loader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\JsonOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-JsonOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput",
            "name": "ParquetOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003Aloader\u0028\u0029",
            "name": "loader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method_loader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\ParquetOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-ParquetOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type",
            "name": "Type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AtoContentTypeHeader\u0028\u0029",
            "name": "toContentTypeHeader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#method_toContentTypeHeader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003ACSV",
            "name": "CSV",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_CSV"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AJSON",
            "name": "JSON",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_JSON"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003APARQUET",
            "name": "PARQUET",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_PARQUET"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003ATEXT",
            "name": "TEXT",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_TEXT"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\Type\u003A\u003AXML",
            "name": "XML",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-Type.html#enumcase_XML"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput",
            "name": "XMLOutput",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003Aloader\u0028\u0029",
            "name": "loader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method_loader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\\XMLOutput\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output-XMLOutput.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output",
            "name": "Output",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\u003A\u003Aloader\u0028\u0029",
            "name": "loader",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html#method_loader"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Output.html#method_type"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\MaskColumns",
            "name": "MaskColumns",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-MaskColumns.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\MaskColumns\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-MaskColumns.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\MaskColumns\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-MaskColumns.html#method_transform"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\Transformations",
            "name": "Transformations",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-Transformations.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\Transformations\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-Transformations.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation\\Transformations\u003A\u003Atransform\u0028\u0029",
            "name": "transform",
            "summary": "",
            "url": "classes/Flow-Bridge-Symfony-HttpFoundation-Transformation-Transformations.html#method_transform"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation",
            "name": "HttpFoundation",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony",
            "name": "Symfony",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Output",
            "name": "Output",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation-output.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\Symfony\\HttpFoundation\\Transformation",
            "name": "Transformation",
            "summary": "",
            "url": "namespaces/flow-bridge-symfony-httpfoundation-transformation.html"
        }            ]
);
