Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory\\SharedKeyFactory",
            "name": "SharedKeyFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-AuthorizationFactory-SharedKeyFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory\\SharedKeyFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-AuthorizationFactory-SharedKeyFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory\\SharedKeyFactory\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-AuthorizationFactory-SharedKeyFactory.html#method_for"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory",
            "name": "AuthorizationFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-AuthorizationFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-AuthorizationFactory.html#method_for"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block",
            "name": "Block",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003Acommited\u0028\u0029",
            "name": "commited",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#method_commited"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003Alatest\u0028\u0029",
            "name": "latest",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#method_latest"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003Auncommited\u0028\u0029",
            "name": "uncommited",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#method_uncommited"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#property_id"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#property_state"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\Block\u003A\u003A\u0024size",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-Block.html#property_size"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockList",
            "name": "BlockList",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockList.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockList.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockList\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockList.html#method_all"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockList\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockList.html#method_append"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockList\u003A\u003Alast\u0028\u0029",
            "name": "last",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockList.html#method_last"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockState",
            "name": "BlockState",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockState.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockState\u003A\u003ACOMMITTED",
            "name": "COMMITTED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockState.html#enumcase_COMMITTED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockState\u003A\u003ALATEST",
            "name": "LATEST",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockState.html#enumcase_LATEST"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob\\BlockState\u003A\u003AUNCOMMITTED",
            "name": "UNCOMMITTED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-BlockBlob-BlockState.html#enumcase_UNCOMMITTED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\Configuration",
            "name": "Configuration",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-Configuration.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\Configuration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-Configuration.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\Configuration\u003A\u003A\u0024account",
            "name": "account",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-Configuration.html#property_account"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\Configuration\u003A\u003A\u0024container",
            "name": "container",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-Configuration.html#property_container"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions",
            "name": "CopyBlobOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithDeleteSnapshots\u0028\u0029",
            "name": "withDeleteSnapshots",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withDeleteSnapshots"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithDeleteType\u0028\u0029",
            "name": "withDeleteType",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withDeleteType"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithSnapshot\u0028\u0029",
            "name": "withSnapshot",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withSnapshot"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob\\CopyBlobOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CopyBlob-CopyBlobOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions",
            "name": "CreateContainerOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AwithPublicAccess\u0028\u0029",
            "name": "withPublicAccess",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_withPublicAccess"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\CreateContainerOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-CreateContainerOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\PublicAccess",
            "name": "PublicAccess",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-PublicAccess.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\PublicAccess\u003A\u003ABLOB",
            "name": "BLOB",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-PublicAccess.html#enumcase_BLOB"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer\\PublicAccess\u003A\u003ACONTAINER",
            "name": "CONTAINER",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-CreateContainer-PublicAccess.html#enumcase_CONTAINER"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions",
            "name": "DeleteBlobOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithDeleteSnapshots\u0028\u0029",
            "name": "withDeleteSnapshots",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withDeleteSnapshots"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithDeleteType\u0028\u0029",
            "name": "withDeleteType",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withDeleteType"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithSnapshot\u0028\u0029",
            "name": "withSnapshot",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withSnapshot"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteBlobOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteBlobOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteSnapshots",
            "name": "DeleteSnapshots",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteSnapshots.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteSnapshots\u003A\u003AINCLUDE",
            "name": "INCLUDE",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteSnapshots.html#enumcase_INCLUDE"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteSnapshots\u003A\u003AONLY",
            "name": "ONLY",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteSnapshots.html#enumcase_ONLY"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteType",
            "name": "DeleteType",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteType.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob\\DeleteType\u003A\u003APERMANENT",
            "name": "PERMANENT",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteBlob-DeleteType.html#enumcase_PERMANENT"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions",
            "name": "DeleteContainerOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer\\DeleteContainerOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-DeleteContainer-DeleteContainerOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\BlobContent",
            "name": "BlobContent",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-BlobContent.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\BlobContent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-BlobContent.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\BlobContent\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-BlobContent.html#method_content"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\BlobContent\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-BlobContent.html#method_length"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\BlobContent\u003A\u003Astream\u0028\u0029",
            "name": "stream",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-BlobContent.html#method_stream"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions",
            "name": "GetBlobOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithEncryption\u0028\u0029",
            "name": "withEncryption",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withEncryption"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithOrigin\u0028\u0029",
            "name": "withOrigin",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withOrigin"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithRange\u0028\u0029",
            "name": "withRange",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withRange"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithRangeGetContentCrc64\u0028\u0029",
            "name": "withRangeGetContentCrc64",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withRangeGetContentCrc64"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithRangeGetContentMd5\u0028\u0029",
            "name": "withRangeGetContentMd5",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withRangeGetContentMd5"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithSnapshot\u0028\u0029",
            "name": "withSnapshot",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withSnapshot"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\GetBlobOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-GetBlobOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\Range",
            "name": "Range",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-Range.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\Range\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-Range.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob\\Range\u003A\u003AtoString\u0028\u0029",
            "name": "toString",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlob-Range.html#method_toString"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\BlobProperties",
            "name": "BlobProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-BlobProperties.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\BlobProperties\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-BlobProperties.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\BlobProperties\u003A\u003Acontent\u0028\u0029",
            "name": "content",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-BlobProperties.html#method_content"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\BlobProperties\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-BlobProperties.html#method_size"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions",
            "name": "GetBlobPropertiesOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithEncryption\u0028\u0029",
            "name": "withEncryption",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withEncryption"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithSnapshot\u0028\u0029",
            "name": "withSnapshot",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withSnapshot"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties\\GetBlobPropertiesOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlobProperties-GetBlobPropertiesOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\BlockListType",
            "name": "BlockListType",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-BlockListType.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\BlockListType\u003A\u003AALL",
            "name": "ALL",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-BlockListType.html#enumcase_ALL"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\BlockListType\u003A\u003ACOMMITTED",
            "name": "COMMITTED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-BlockListType.html#enumcase_COMMITTED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\BlockListType\u003A\u003AUNCOMMITTED",
            "name": "UNCOMMITTED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-BlockListType.html#enumcase_UNCOMMITTED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions",
            "name": "GetBlockBlobBlockListOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithBlockListType\u0028\u0029",
            "name": "withBlockListType",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withBlockListType"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithSnapshot\u0028\u0029",
            "name": "withSnapshot",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withSnapshot"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList\\GetBlockBlobBlockListOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetBlockBlobBlockList-GetBlockBlobBlockListOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\ContainerProperties",
            "name": "ContainerProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-ContainerProperties.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\ContainerProperties\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-ContainerProperties.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions",
            "name": "GetContainerPropertiesOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AwithLeaseId\u0028\u0029",
            "name": "withLeaseId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_withLeaseId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties\\GetContainerPropertiesOptions\u003A\u003AwithVersionId\u0028\u0029",
            "name": "withVersionId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-GetContainerProperties-GetContainerPropertiesOptions.html#method_withVersionId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\Blob",
            "name": "Blob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-Blob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\Blob\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-Blob.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\Blob\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-Blob.html#method_name"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\Blob\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-Blob.html#method_size"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions",
            "name": "ListBlobOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithDelimiter\u0028\u0029",
            "name": "withDelimiter",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withDelimiter"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithInclude\u0028\u0029",
            "name": "withInclude",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withInclude"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithMarker\u0028\u0029",
            "name": "withMarker",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withMarker"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithMaxResults\u0028\u0029",
            "name": "withMaxResults",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withMaxResults"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithPrefix\u0028\u0029",
            "name": "withPrefix",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withPrefix"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithShowOnly\u0028\u0029",
            "name": "withShowOnly",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withShowOnly"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\ListBlobOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-ListBlobOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude",
            "name": "OptionInclude",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ACOPY",
            "name": "COPY",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_COPY"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ADELETED",
            "name": "DELETED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_DELETED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ADELETED_WITH_VERSIONS",
            "name": "DELETED_WITH_VERSIONS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_DELETED_WITH_VERSIONS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003AIMMUTABILITY_POLICY",
            "name": "IMMUTABILITY_POLICY",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_IMMUTABILITY_POLICY"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ALEGAL_HOLD",
            "name": "LEGAL_HOLD",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_LEGAL_HOLD"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003AMETADATA",
            "name": "METADATA",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_METADATA"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003APERMISSIONS",
            "name": "PERMISSIONS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_PERMISSIONS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ASNAPSHOTS",
            "name": "SNAPSHOTS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_SNAPSHOTS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003ATAGS",
            "name": "TAGS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_TAGS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003AUNCOMMITTED_BLOBS",
            "name": "UNCOMMITTED_BLOBS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_UNCOMMITTED_BLOBS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionInclude\u003A\u003AVERSIONS",
            "name": "VERSIONS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionInclude.html#enumcase_VERSIONS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionShowOnly",
            "name": "OptionShowOnly",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionShowOnly.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionShowOnly\u003A\u003ADELETED",
            "name": "DELETED",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionShowOnly.html#enumcase_DELETED"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionShowOnly\u003A\u003AFILES",
            "name": "FILES",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionShowOnly.html#enumcase_FILES"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs\\OptionShowOnly\u003A\u003AFOLDERS",
            "name": "FOLDERS",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-ListBlobs-OptionShowOnly.html#enumcase_FOLDERS"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions",
            "name": "PutBlockBlobOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AwithEncryption\u0028\u0029",
            "name": "withEncryption",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_withEncryption"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob\\PutBlockBlobOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlob-PutBlockBlobOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions",
            "name": "PutBlockBlobBlockOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AwithEncryption\u0028\u0029",
            "name": "withEncryption",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_withEncryption"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock\\PutBlockBlobBlockOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlock-PutBlockBlobBlockOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions",
            "name": "PutBlockBlobBlockListOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AwithContentLength\u0028\u0029",
            "name": "withContentLength",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_withContentLength"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AwithEncryption\u0028\u0029",
            "name": "withEncryption",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_withEncryption"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AwithRequestId\u0028\u0029",
            "name": "withRequestId",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_withRequestId"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AwithTimeoutSeconds\u0028\u0029",
            "name": "withTimeoutSeconds",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_withTimeoutSeconds"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\PutBlockBlobBlockListOptions\u003A\u003AwithVersion\u0028\u0029",
            "name": "withVersion",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-PutBlockBlobBlockListOptions.html#method_withVersion"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\SimpleXMLSerializer",
            "name": "SimpleXMLSerializer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-SimpleXMLSerializer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\SimpleXMLSerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-SimpleXMLSerializer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList\\SimpleXMLSerializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-PutBlockBlobBlockList-SimpleXMLSerializer.html#method_serialize"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzureURLFactory",
            "name": "AzureURLFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzureURLFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzureURLFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzureURLFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzureURLFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzureURLFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzuriteURLFactory",
            "name": "AzuriteURLFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzuriteURLFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzuriteURLFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzuriteURLFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory\\AzuriteURLFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService-URLFactory-AzuriteURLFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService",
            "name": "BlobService",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AcopyBlob\u0028\u0029",
            "name": "copyBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_copyBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AdeleteBlob\u0028\u0029",
            "name": "deleteBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_deleteBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AdeleteContainer\u0028\u0029",
            "name": "deleteContainer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_deleteContainer"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AgetBlob\u0028\u0029",
            "name": "getBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_getBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AgetBlobProperties\u0028\u0029",
            "name": "getBlobProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_getBlobProperties"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AgetBlockBlobBlockList\u0028\u0029",
            "name": "getBlockBlobBlockList",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_getBlockBlobBlockList"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AgetContainerProperties\u0028\u0029",
            "name": "getContainerProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_getContainerProperties"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AlistBlobs\u0028\u0029",
            "name": "listBlobs",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_listBlobs"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AputBlockBlob\u0028\u0029",
            "name": "putBlockBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_putBlockBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AputBlockBlobBlock\u0028\u0029",
            "name": "putBlockBlobBlock",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_putBlockBlobBlock"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AputBlockBlobBlockList\u0028\u0029",
            "name": "putBlockBlobBlockList",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_putBlockBlobBlockList"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AputContainer\u0028\u0029",
            "name": "putContainer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#method_putContainer"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobService.html#constant_VERSION"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface",
            "name": "BlobServiceInterface",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AcopyBlob\u0028\u0029",
            "name": "copyBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_copyBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AdeleteBlob\u0028\u0029",
            "name": "deleteBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_deleteBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AdeleteContainer\u0028\u0029",
            "name": "deleteContainer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_deleteContainer"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AgetBlob\u0028\u0029",
            "name": "getBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_getBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AgetBlobProperties\u0028\u0029",
            "name": "getBlobProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_getBlobProperties"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AgetBlockBlobBlockList\u0028\u0029",
            "name": "getBlockBlobBlockList",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_getBlockBlobBlockList"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AgetContainerProperties\u0028\u0029",
            "name": "getContainerProperties",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_getContainerProperties"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AlistBlobs\u0028\u0029",
            "name": "listBlobs",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_listBlobs"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AputBlockBlob\u0028\u0029",
            "name": "putBlockBlob",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_putBlockBlob"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AputBlockBlobBlock\u0028\u0029",
            "name": "putBlockBlobBlock",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_putBlockBlobBlock"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AputBlockBlobBlockList\u0028\u0029",
            "name": "putBlockBlobBlockList",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_putBlockBlobBlockList"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobServiceInterface\u003A\u003AputContainer\u0028\u0029",
            "name": "putContainer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-BlobServiceInterface.html#method_putContainer"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azurite_url_factory\u0028\u0029",
            "name": "azurite_url_factory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azurite_url_factory"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azure_shared_key_authorization_factory\u0028\u0029",
            "name": "azure_shared_key_authorization_factory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azure_shared_key_authorization_factory"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azure_blob_service_config\u0028\u0029",
            "name": "azure_blob_service_config",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azure_blob_service_config"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azure_url_factory\u0028\u0029",
            "name": "azure_url_factory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azure_url_factory"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azure_http_factory\u0028\u0029",
            "name": "azure_http_factory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azure_http_factory"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL\\azure_blob_service\u0028\u0029",
            "name": "azure_blob_service",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html#function_azure_blob_service"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\EndpointOptions",
            "name": "EndpointOptions",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-EndpointOptions.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\EndpointOptions\u003A\u003AtoHeaders\u0028\u0029",
            "name": "toHeaders",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-EndpointOptions.html#method_toHeaders"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\EndpointOptions\u003A\u003AtoURIParameters\u0028\u0029",
            "name": "toURIParameters",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-EndpointOptions.html#method_toURIParameters"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Endpoints\\UserAgentHeader",
            "name": "UserAgentHeader",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Endpoints-UserAgentHeader.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Endpoints\\UserAgentHeader\u003A\u003AuserAgentHeader\u0028\u0029",
            "name": "userAgentHeader",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Endpoints-UserAgentHeader.html#method_userAgentHeader"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Endpoints\\UserAgentHeader\u003A\u003AwithUserAgent\u0028\u0029",
            "name": "withUserAgent",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Endpoints-UserAgentHeader.html#method_withUserAgent"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\AzureException",
            "name": "AzureException",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-AzureException.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\AzureException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-AzureException.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\AzureException\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-AzureException.html#property_request"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\AzureException\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-AzureException.html#property_response"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-Exception.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory",
            "name": "HttpFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method_delete"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method_get"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method_post"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method_put"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\HttpFactory\u003A\u003Astream\u0028\u0029",
            "name": "stream",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-HttpFactory.html#method_stream"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer\\SimpleXMLNormalizer",
            "name": "SimpleXMLNormalizer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Normalizer-SimpleXMLNormalizer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer\\SimpleXMLNormalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Normalizer-SimpleXMLNormalizer.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer\\SimpleXMLNormalizer\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Normalizer-SimpleXMLNormalizer.html#method_toArray"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer",
            "name": "Normalizer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Normalizer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Normalizer.html#method_toArray"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\RequestIdFactory",
            "name": "RequestIdFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-RequestIdFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\RequestIdFactory\u003A\u003Afor\u0028\u0029",
            "name": "for",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-RequestIdFactory.html#method_for"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Serializer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\URLFactory",
            "name": "URLFactory",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-URLFactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\URLFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Azure-SDK-URLFactory.html#method_create"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\AuthorizationFactory",
            "name": "AuthorizationFactory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-authorizationfactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK",
            "name": "SDK",
            "summary": "",
            "url": "namespaces/flow-azure-sdk.html"
        },                {
            "fqsen": "\\Flow\\Azure",
            "name": "Azure",
            "summary": "",
            "url": "namespaces/flow-azure.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\BlockBlob",
            "name": "BlockBlob",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-blockblob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService",
            "name": "BlobService",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CopyBlob",
            "name": "CopyBlob",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-copyblob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\CreateContainer",
            "name": "CreateContainer",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-createcontainer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteBlob",
            "name": "DeleteBlob",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-deleteblob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\DeleteContainer",
            "name": "DeleteContainer",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-deletecontainer.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlob",
            "name": "GetBlob",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-getblob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlobProperties",
            "name": "GetBlobProperties",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-getblobproperties.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetBlockBlobBlockList",
            "name": "GetBlockBlobBlockList",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-getblockblobblocklist.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\GetContainerProperties",
            "name": "GetContainerProperties",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-getcontainerproperties.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\ListBlobs",
            "name": "ListBlobs",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-listblobs.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlob",
            "name": "PutBlockBlob",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-putblockblob.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlock",
            "name": "PutBlockBlobBlock",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-putblockblobblock.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\PutBlockBlobBlockList",
            "name": "PutBlockBlobBlockList",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-putblockblobblocklist.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\BlobService\\URLFactory",
            "name": "URLFactory",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-blobservice-urlfactory.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-dsl.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Endpoints",
            "name": "Endpoints",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-endpoints.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-exception.html"
        },                {
            "fqsen": "\\Flow\\Azure\\SDK\\Normalizer",
            "name": "Normalizer",
            "summary": "",
            "url": "namespaces/flow-azure-sdk-normalizer.html"
        }            ]
);
