Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration",
            "name": "Configuration",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AfromParameters\u0028\u0029",
            "name": "fromParameters",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#method_fromParameters"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_BATCH_SIZE",
            "name": "DEFAULT_BATCH_SIZE",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_BATCH_SIZE"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_CONNECT_TIMEOUT_MS",
            "name": "DEFAULT_CONNECT_TIMEOUT_MS",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_CONNECT_TIMEOUT_MS"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_ENDPOINT",
            "name": "DEFAULT_ENDPOINT",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_ENDPOINT"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_FILE_PERMISSIONS",
            "name": "DEFAULT_FILE_PERMISSIONS",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_FILE_PERMISSIONS"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_MESSAGE_PREFIX",
            "name": "DEFAULT_MESSAGE_PREFIX",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_MESSAGE_PREFIX"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_SHUTDOWN_TIMEOUT_MS",
            "name": "DEFAULT_SHUTDOWN_TIMEOUT_MS",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_SHUTDOWN_TIMEOUT_MS"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ADEFAULT_TIMEOUT_MS",
            "name": "DEFAULT_TIMEOUT_MS",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_DEFAULT_TIMEOUT_MS"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AERROR_HANDLER_LOG",
            "name": "ERROR_HANDLER_LOG",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_ERROR_HANDLER_LOG"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AERROR_HANDLER_NOOP",
            "name": "ERROR_HANDLER_NOOP",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_ERROR_HANDLER_NOOP"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AERROR_HANDLER_STREAM",
            "name": "ERROR_HANDLER_STREAM",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_ERROR_HANDLER_STREAM"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AERROR_HANDLER_SYSLOG",
            "name": "ERROR_HANDLER_SYSLOG",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_ERROR_HANDLER_SYSLOG"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003AERROR_HANDLER_UDP_SYSLOG",
            "name": "ERROR_HANDLER_UDP_SYSLOG",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_ERROR_HANDLER_UDP_SYSLOG"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ATRANSPORT_CURL",
            "name": "TRANSPORT_CURL",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_TRANSPORT_CURL"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ATRANSPORT_GRPC",
            "name": "TRANSPORT_GRPC",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_TRANSPORT_GRPC"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003ATRANSPORT_STREAM",
            "name": "TRANSPORT_STREAM",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#constant_TRANSPORT_STREAM"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024serviceName",
            "name": "serviceName",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_serviceName"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024transport",
            "name": "transport",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_transport"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024emitTraces",
            "name": "emitTraces",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_emitTraces"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024emitMetrics",
            "name": "emitMetrics",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_emitMetrics"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024emitTestSpans",
            "name": "emitTestSpans",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_emitTestSpans"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024emitTestCaseSpans",
            "name": "emitTestCaseSpans",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_emitTestCaseSpans"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024batchSize",
            "name": "batchSize",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_batchSize"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024errorHandler",
            "name": "errorHandler",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_errorHandler"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024memoryRealUsage",
            "name": "memoryRealUsage",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_memoryRealUsage"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Configuration\u003A\u003A\u0024resourceAttributes",
            "name": "resourceAttributes",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Configuration.html#property_resourceAttributes"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig",
            "name": "CurlTransportConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_endpoint"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_headers"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024timeoutMs",
            "name": "timeoutMs",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_timeoutMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024connectTimeoutMs",
            "name": "connectTimeoutMs",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_connectTimeoutMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024shutdownTimeoutMs",
            "name": "shutdownTimeoutMs",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_shutdownTimeoutMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024compression",
            "name": "compression",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_compression"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024followRedirects",
            "name": "followRedirects",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_followRedirects"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024maxRedirects",
            "name": "maxRedirects",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_maxRedirects"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024proxy",
            "name": "proxy",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_proxy"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024sslVerifyPeer",
            "name": "sslVerifyPeer",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_sslVerifyPeer"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024sslVerifyHost",
            "name": "sslVerifyHost",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_sslVerifyHost"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024sslCertPath",
            "name": "sslCertPath",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_sslCertPath"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024sslKeyPath",
            "name": "sslKeyPath",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_sslKeyPath"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024caInfoPath",
            "name": "caInfoPath",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_caInfoPath"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\CurlTransportConfig\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-CurlTransportConfig.html#property_serializer"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\ErrorLogHandlerConfig",
            "name": "ErrorLogHandlerConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-ErrorLogHandlerConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\ErrorLogHandlerConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-ErrorLogHandlerConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\ErrorLogHandlerConfig\u003A\u003A\u0024messageType",
            "name": "messageType",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-ErrorLogHandlerConfig.html#property_messageType"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\ErrorLogHandlerConfig\u003A\u003A\u0024expandNewlines",
            "name": "expandNewlines",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-ErrorLogHandlerConfig.html#property_expandNewlines"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\ErrorLogHandlerConfig\u003A\u003A\u0024messagePrefix",
            "name": "messagePrefix",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-ErrorLogHandlerConfig.html#property_messagePrefix"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig",
            "name": "GrpcTransportConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#property_endpoint"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#property_headers"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A\u0024insecure",
            "name": "insecure",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#property_insecure"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A\u0024timeoutMs",
            "name": "timeoutMs",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#property_timeoutMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\GrpcTransportConfig\u003A\u003A\u0024shutdownTimeoutMs",
            "name": "shutdownTimeoutMs",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-GrpcTransportConfig.html#property_shutdownTimeoutMs"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\NullErrorHandlerConfig",
            "name": "NullErrorHandlerConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-NullErrorHandlerConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes",
            "name": "PHPUnitTelemetryAttributes",
            "summary": "Flow\u002Dspecific\u0020PHPUnit\u0020attribute\u0020keys.",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_SUITE_IS_ROOT",
            "name": "ATTR_SUITE_IS_ROOT",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_SUITE_IS_ROOT"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_SUITE_TEST_COUNT",
            "name": "ATTR_SUITE_TEST_COUNT",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_SUITE_TEST_COUNT"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_TEST_CLASS",
            "name": "ATTR_TEST_CLASS",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_TEST_CLASS"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_TEST_ID",
            "name": "ATTR_TEST_ID",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_TEST_ID"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_TEST_MEMORY_DELTA",
            "name": "ATTR_TEST_MEMORY_DELTA",
            "summary": "Value\u0020expressed\u0020in\u0020bytes.",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_TEST_MEMORY_DELTA"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_TEST_MEMORY_PEAK",
            "name": "ATTR_TEST_MEMORY_PEAK",
            "summary": "Value\u0020expressed\u0020in\u0020bytes.",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_TEST_MEMORY_PEAK"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\PHPUnitTelemetryAttributes\u003A\u003AATTR_TEST_METHOD",
            "name": "ATTR_TEST_METHOD",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-PHPUnitTelemetryAttributes.html#constant_ATTR_TEST_METHOD"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack",
            "name": "SpanStack",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_clear"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_current"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003AgetSuiteSpan\u0028\u0029",
            "name": "getSuiteSpan",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_getSuiteSpan"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003AisEmpty\u0028\u0029",
            "name": "isEmpty",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_isEmpty"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003Apop\u0028\u0029",
            "name": "pop",
            "summary": "Detaches\u0020the\u0020entry\u0027s\u0020context\u0020scope\u0020before\u0020returning\u0020it,\u0020so\u0020the\u0020stack\u0020owns\u0020the\u0020LIFO\u0020ordering\u0020that\nScope\u003A\u003Adetach\u0028\u0029\u0020requires.",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_pop"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_push"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003AremoveSuiteSpan\u0028\u0029",
            "name": "removeSuiteSpan",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_removeSuiteSpan"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SpanStack\u003A\u003AsetSuiteSpan\u0028\u0029",
            "name": "setSuiteSpan",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SpanStack.html#method_setSuiteSpan"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig",
            "name": "StreamErrorHandlerConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig\u003A\u003A\u0024destination",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html#property_destination"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig\u003A\u003A\u0024filePermissions",
            "name": "filePermissions",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html#property_filePermissions"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig\u003A\u003A\u0024createDirectories",
            "name": "createDirectories",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html#property_createDirectories"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamErrorHandlerConfig\u003A\u003A\u0024messagePrefix",
            "name": "messagePrefix",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamErrorHandlerConfig.html#property_messagePrefix"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamTransportConfig",
            "name": "StreamTransportConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamTransportConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamTransportConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamTransportConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamTransportConfig\u003A\u003A\u0024destination",
            "name": "destination",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamTransportConfig.html#property_destination"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamTransportConfig\u003A\u003A\u0024filePermissions",
            "name": "filePermissions",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamTransportConfig.html#property_filePermissions"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\StreamTransportConfig\u003A\u003A\u0024createDirectories",
            "name": "createDirectories",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-StreamTransportConfig.html#property_createDirectories"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestErroredSubscriber",
            "name": "TestErroredSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestErroredSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestErroredSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestErroredSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestErroredSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestErroredSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFailedSubscriber",
            "name": "TestFailedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFailedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFailedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFailedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFailedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFailedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFinishedSubscriber",
            "name": "TestFinishedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFinishedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFinishedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFinishedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestFinishedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestFinishedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestMarkedIncompleteSubscriber",
            "name": "TestMarkedIncompleteSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestMarkedIncompleteSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestMarkedIncompleteSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestMarkedIncompleteSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestMarkedIncompleteSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestMarkedIncompleteSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPassedSubscriber",
            "name": "TestPassedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPassedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPassedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPassedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPassedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPassedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPreparationStartedSubscriber",
            "name": "TestPreparationStartedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPreparationStartedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPreparationStartedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPreparationStartedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestPreparationStartedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestPreparationStartedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSkippedSubscriber",
            "name": "TestSkippedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSkippedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSkippedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSkippedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSkippedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSkippedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteFinishedSubscriber",
            "name": "TestSuiteFinishedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteFinishedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteFinishedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteFinishedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteFinishedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteFinishedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteStartedSubscriber",
            "name": "TestSuiteStartedSubscriber",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteStartedSubscriber.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteStartedSubscriber\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteStartedSubscriber.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber\\TestSuiteStartedSubscriber\u003A\u003Anotify\u0028\u0029",
            "name": "notify",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-Subscriber-TestSuiteStartedSubscriber.html#method_notify"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SuiteOutcomeStack",
            "name": "SuiteOutcomeStack",
            "summary": "Aggregates\u0020finished\u002Dtest\u0020statuses\u0020per\u0020open\u0020test\u0020suite\u0020so\u0020the\u0020suite\u0020span\u0020can\u0020carry\u0020the\u0020official\n\u0060test.suite.run.status\u0060\u0020attribute.\u0020Suites\u0020nest,\u0020so\u0020every\u0020finished\u0020test\u0020counts\u0020towards\u0020all\ncurrently\u0020open\u0020suites.",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SuiteOutcomeStack.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SuiteOutcomeStack\u003A\u003Apop\u0028\u0029",
            "name": "pop",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SuiteOutcomeStack.html#method_pop"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SuiteOutcomeStack\u003A\u003Apush\u0028\u0029",
            "name": "push",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SuiteOutcomeStack.html#method_push"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SuiteOutcomeStack\u003A\u003ArecordStatus\u0028\u0029",
            "name": "recordStatus",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SuiteOutcomeStack.html#method_recordStatus"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SuiteOutcomeStack\u003A\u003Asize\u0028\u0029",
            "name": "size",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SuiteOutcomeStack.html#method_size"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig",
            "name": "SyslogErrorHandlerConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig\u003A\u003A\u0024ident",
            "name": "ident",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html#property_ident"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig\u003A\u003A\u0024facility",
            "name": "facility",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html#property_facility"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig\u003A\u003A\u0024logOpts",
            "name": "logOpts",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html#property_logOpts"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\SyslogErrorHandlerConfig\u003A\u003A\u0024severity",
            "name": "severity",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-SyslogErrorHandlerConfig.html#property_severity"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TelemetryExtension",
            "name": "TelemetryExtension",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TelemetryExtension.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TelemetryExtension\u003A\u003Abootstrap\u0028\u0029",
            "name": "bootstrap",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TelemetryExtension.html#method_bootstrap"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TelemetryFactory",
            "name": "TelemetryFactory",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TelemetryFactory.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TelemetryFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TelemetryFactory.html#method_create"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestMemoryRegistry",
            "name": "TestMemoryRegistry",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestMemoryRegistry.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestMemoryRegistry\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestMemoryRegistry.html#method_clear"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestMemoryRegistry\u003A\u003AgetStart\u0028\u0029",
            "name": "getStart",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestMemoryRegistry.html#method_getStart"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestMemoryRegistry\u003A\u003AsetStart\u0028\u0029",
            "name": "setStart",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestMemoryRegistry.html#method_setStart"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestStatusRegistry",
            "name": "TestStatusRegistry",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestStatusRegistry.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestStatusRegistry\u003A\u003Aclear\u0028\u0029",
            "name": "clear",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestStatusRegistry.html#method_clear"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestStatusRegistry\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestStatusRegistry.html#method_getMessage"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestStatusRegistry\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestStatusRegistry.html#method_getStatus"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\TestStatusRegistry\u003A\u003AsetStatus\u0028\u0029",
            "name": "setStatus",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-TestStatusRegistry.html#method_setStatus"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig",
            "name": "UdpSyslogErrorHandlerConfig",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#method___construct"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#property_host"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A\u0024port",
            "name": "port",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#property_port"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A\u0024ident",
            "name": "ident",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#property_ident"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A\u0024facility",
            "name": "facility",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#property_facility"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\UdpSyslogErrorHandlerConfig\u003A\u003A\u0024severity",
            "name": "severity",
            "summary": "",
            "url": "classes/Flow-Bridge-PHPUnit-Telemetry-UdpSyslogErrorHandlerConfig.html#property_severity"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry",
            "name": "Telemetry",
            "summary": "",
            "url": "namespaces/flow-bridge-phpunit-telemetry.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit",
            "name": "PHPUnit",
            "summary": "",
            "url": "namespaces/flow-bridge-phpunit.html"
        },                {
            "fqsen": "\\Flow\\Bridge",
            "name": "Bridge",
            "summary": "",
            "url": "namespaces/flow-bridge.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\Bridge\\PHPUnit\\Telemetry\\Subscriber",
            "name": "Subscriber",
            "summary": "",
            "url": "namespaces/flow-bridge-phpunit-telemetry-subscriber.html"
        }            ]
);
