Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\DSL\\from_excel\u0028\u0029",
            "name": "from_excel",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel-dsl.html#function_from_excel"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\DSL\\is_valid_excel_sheet_name\u0028\u0029",
            "name": "is_valid_excel_sheet_name",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel-dsl.html#function_is_valid_excel_sheet_name"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor",
            "name": "ExcelExtractor",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003Aclosure\u0028\u0029",
            "name": "closure",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_closure"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_extract"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003Asource\u0028\u0029",
            "name": "source",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_source"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003AwithConvertEmptyToNull\u0028\u0029",
            "name": "withConvertEmptyToNull",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_withConvertEmptyToNull"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_withHeader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003AwithOffset\u0028\u0029",
            "name": "withOffset",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_withOffset"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003AwithReader\u0028\u0029",
            "name": "withReader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_withReader"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelExtractor\u003A\u003AwithSheetName\u0028\u0029",
            "name": "withSheetName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelExtractor.html#method_withSheetName"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelReader",
            "name": "ExcelReader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelReader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelReader\u003A\u003AODS",
            "name": "ODS",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelReader.html#enumcase_ODS"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\ExcelReader\u003A\u003AXLSX",
            "name": "XLSX",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-ExcelReader.html#enumcase_XLSX"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Function\\IsValidExcelSheetName",
            "name": "IsValidExcelSheetName",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Function-IsValidExcelSheetName.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Function\\IsValidExcelSheetName\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Function-IsValidExcelSheetName.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Function\\IsValidExcelSheetName\u003A\u003Aeval\u0028\u0029",
            "name": "eval",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Function-IsValidExcelSheetName.html#method_eval"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetNameAssertion",
            "name": "SheetNameAssertion",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetNameAssertion.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetNameAssertion\u003A\u003Aassert\u0028\u0029",
            "name": "assert",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetNameAssertion.html#method_assert"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetNameAssertion\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetNameAssertion.html#method_isValid"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetsManager",
            "name": "SheetsManager",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetsManager.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetsManager\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetsManager.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetsManager\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetsManager.html#method_first"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet\\SheetsManager\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Excel-Sheet-SheetsManager.html#method_get"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\DSL",
            "name": "DSL",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel-dsl.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel",
            "name": "Excel",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Function",
            "name": "Function",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel-function.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Excel\\Sheet",
            "name": "Sheet",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-excel-sheet.html"
        }            ]
);
