Search.appendIndex(
    [
                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\to_seal_upsert\u0028\u0029",
            "name": "to_seal_upsert",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-seal.html#function_to_seal_upsert"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\to_seal_delete\u0028\u0029",
            "name": "to_seal_delete",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-seal.html#function_to_seal_delete"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\to_seal_schema\u0028\u0029",
            "name": "to_seal_schema",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-seal.html#function_to_seal_schema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\seal_schema_to_flow\u0028\u0029",
            "name": "seal_schema_to_flow",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-seal.html#function_seal_schema_to_flow"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\Operation",
            "name": "Operation",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-Operation.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\Operation\u003A\u003ADELETE",
            "name": "DELETE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-Operation.html#enumcase_DELETE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\Operation\u003A\u003AUPSERT",
            "name": "UPSERT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-Operation.html#enumcase_UPSERT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SchemaConverter",
            "name": "SchemaConverter",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SchemaConverter.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SchemaConverter\u003A\u003AtoFlowSchema\u0028\u0029",
            "name": "toFlowSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SchemaConverter.html#method_toFlowSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SchemaConverter\u003A\u003AtoSealSchema\u0028\u0029",
            "name": "toSealSchema",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SchemaConverter.html#method_toSealSchema"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealEncoder",
            "name": "SealEncoder",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealEncoder.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealEncoder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealEncoder.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealEncoder.html#method_decode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealEncoder.html#method_encode"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader",
            "name": "SealLoader",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method___construct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method_load"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003AwithBulkSize\u0028\u0029",
            "name": "withBulkSize",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method_withBulkSize"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003AwithDateFormat\u0028\u0029",
            "name": "withDateFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method_withDateFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003AwithDateTimeFormat\u0028\u0029",
            "name": "withDateTimeFormat",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method_withDateTimeFormat"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealLoader\u003A\u003AwithIdentifierEntry\u0028\u0029",
            "name": "withIdentifierEntry",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealLoader.html#method_withIdentifierEntry"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata",
            "name": "SealMetadata",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Adistinct\u0028\u0029",
            "name": "distinct",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_distinct"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Afacet\u0028\u0029",
            "name": "facet",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_facet"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Afilterable\u0028\u0029",
            "name": "filterable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_filterable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Aidentifier\u0028\u0029",
            "name": "identifier",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_identifier"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Asearchable\u0028\u0029",
            "name": "searchable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_searchable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003Asortable\u0028\u0029",
            "name": "sortable",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#method_sortable"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003ADISTINCT",
            "name": "DISTINCT",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_DISTINCT"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003AFACET",
            "name": "FACET",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_FACET"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003AFILTERABLE",
            "name": "FILTERABLE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_FILTERABLE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003AIDENTIFIER",
            "name": "IDENTIFIER",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_IDENTIFIER"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003ASEARCHABLE",
            "name": "SEARCHABLE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_SEARCHABLE"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal\\SealMetadata\u003A\u003ASORTABLE",
            "name": "SORTABLE",
            "summary": "",
            "url": "classes/Flow-ETL-Adapter-Seal-SealMetadata.html#enumcase_SORTABLE"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter\\Seal",
            "name": "Seal",
            "summary": "",
            "url": "namespaces/flow-etl-adapter-seal.html"
        },                {
            "fqsen": "\\Flow\\ETL\\Adapter",
            "name": "Adapter",
            "summary": "",
            "url": "namespaces/flow-etl-adapter.html"
        },                {
            "fqsen": "\\Flow\\ETL",
            "name": "ETL",
            "summary": "",
            "url": "namespaces/flow-etl.html"
        },                {
            "fqsen": "\\Flow",
            "name": "Flow",
            "summary": "",
            "url": "namespaces/flow.html"
        }            ]
);
